/*******************************************************************************
**  FILE-NAME: Mka_Cfg.c                                                    **
**                                                                            **
**  MODULE-NAME: Mka                                                          **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.5.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../151_MKa_TESTING/Code_Compliance/Config/Mka_Config_1/PC_Config/xml/Mka_Config_1.arxml
 *   ../../../151_MKa_DELIVERY/ssc/generator/KPIT_AUTOSAR_R24-11_MKA_BSWMD.arxml
 *   ../../../151_MKa_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2026 Apr 08 16:46:43 IST
 */
/*******************************************************************************
**                   MISRA-C/QAC:2012 violations Section                      **
********************************************************************************
* #page misra_violations MISRA-C:2012 violations
*
*******************************************************************************/


/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "Platform_Types.h"   
#include "Mka_Cfg.h"  
#include "Mka_internal.h"
#include "Mka.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (MKA_VERSION_AR_RELEASE_MAJOR_VERSION != MKA_AR_RELEASE_MAJOR_VERSION)
  #error "MKA Code : Mismatch in Specification Major Version"
#endif

#if (MKA_VERSION_AR_RELEASE_MINOR_VERSION != MKA_AR_RELEASE_MINOR_VERSION)
  #error "MKA Code : Mismatch in Specification Minor Version"
#endif

#if (MKA_VERSION_AR_RELEASE_REVISION_VERSION != MKA_AR_RELEASE_REVISION_VERSION)
  #error "MKA Code : Mismatch in Specification Revision Version"
#endif

#if (MKA_VERSION_SW_MAJOR_VERSION != MKA_SW_MAJOR_VERSION)
  #error "MKA Code : Mismatch in Software Major Version"
#endif

#if (MKA_VERSION_SW_MINOR_VERSION != MKA_SW_MINOR_VERSION)
  #error "MKA Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/
     /* Design_ID          : MKA_SDD_XXXX  */
     #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     const Mka_KayParticipants Mka_KayParticipant[MKA_TOTAL_NUM_KAY_PARTICIPANT] =
     {
     	/* Details of MkaKayParticipant_0 */
     	{
     	  
     	  /* ucMkaCryptoAlgoRefConfigIdx */
     	  0,
     	  
     	  /* usMkaCryptoCknCakKeyRefCsmKeyId */
     	  0,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmJobId */
     	  2,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvGenerateJobRefCsmJobId */
     	  3,
     	  
     	  /* usMkaCryptoIcvDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmJobId */
     	  4,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmJobId */
     	  5,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyUnwrapJobRefCsmJobId */
     	  6,
     	  
     	  /* usMkaCryptoUnwrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyWrapJobRefCsmJobId */
     	  7,
     	  
     	  /* usMkaCryptoWrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoRandomJobRefCsmJobId */
     	  8,
     	  
     	  /* usMkaCryptoRandomDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoSakkeyRefCsmKeyId */
     	  9,
     	  
     	  /* usMkaCryptoSakKeyRefCsmKeyId */
     	  0,
     	  
     	  /* usMkaCryptoKekKeyRefCsmKeyId */
     	  2,
     	  
     	  /* usMkaCryptoICKKeyRefCsmKeyId */
     	  0,
     	  
     	  /* blMkaParticipantActivate */
     	  STD_ON,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  1,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CSM_128,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x00}
     	},
     	/* Details of MkaKayParticipant_1 */
     	{
     	  
     	  /* ucMkaCryptoAlgoRefConfigIdx */
     	  1,
     	  
     	  /* usMkaCryptoCknCakKeyRefCsmKeyId */
     	  1,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmJobId */
     	  2,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvGenerateJobRefCsmJobId */
     	  3,
     	  
     	  /* usMkaCryptoIcvDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmJobId */
     	  4,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmJobId */
     	  5,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyUnwrapJobRefCsmJobId */
     	  6,
     	  
     	  /* usMkaCryptoUnwrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyWrapJobRefCsmJobId */
     	  7,
     	  
     	  /* usMkaCryptoWrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoRandomJobRefCsmJobId */
     	  8,
     	  
     	  /* usMkaCryptoRandomDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoSakkeyRefCsmKeyId */
     	  9,
     	  
     	  /* usMkaCryptoSakKeyRefCsmKeyId */
     	  0,
     	  
     	  /* usMkaCryptoKekKeyRefCsmKeyId */
     	  2,
     	  
     	  /* usMkaCryptoICKKeyRefCsmKeyId */
     	  MKA_INVALID,
     	  
     	  /* blMkaParticipantActivate */
     	  STD_ON,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  1,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CSM_128,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x01}
     	},
     	/* Details of MkaKayParticipant_2 */
     	{
     	  
     	  /* ucMkaCryptoAlgoRefConfigIdx */
     	  2,
     	  
     	  /* usMkaCryptoCknCakKeyRefCsmKeyId */
     	  2,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmJobId */
     	  1,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvGenerateJobRefCsmJobId */
     	  2,
     	  
     	  /* usMkaCryptoIcvDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmJobId */
     	  3,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmJobId */
     	  4,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyUnwrapJobRefCsmJobId */
     	  5,
     	  
     	  /* usMkaCryptoUnwrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyWrapJobRefCsmJobId */
     	  6,
     	  
     	  /* usMkaCryptoWrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoRandomJobRefCsmJobId */
     	  7,
     	  
     	  /* usMkaCryptoRandomDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoSakkeyRefCsmKeyId */
     	  8,
     	  
     	  /* usMkaCryptoSakKeyRefCsmKeyId */
     	  0,
     	  
     	  /* usMkaCryptoKekKeyRefCsmKeyId */
     	  2,
     	  
     	  /* usMkaCryptoICKKeyRefCsmKeyId */
     	  MKA_INVALID,
     	  
     	  /* blMkaParticipantActivate */
     	  STD_ON,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_INVALID,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_INVALID,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CSM_NO_VALUE,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_CRYPTO_NO_VALUE,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x02}
     	},
     	/* Details of MkaKayParticipant_0 */
     	{
     	  
     	  /* ucMkaCryptoAlgoRefConfigIdx */
     	  1,
     	  
     	  /* usMkaCryptoCknCakKeyRefCsmKeyId */
     	  3,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmJobId */
     	  2,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvGenerateJobRefCsmJobId */
     	  3,
     	  
     	  /* usMkaCryptoIcvDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmJobId */
     	  4,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmJobId */
     	  5,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyUnwrapJobRefCsmJobId */
     	  6,
     	  
     	  /* usMkaCryptoUnwrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyWrapJobRefCsmJobId */
     	  7,
     	  
     	  /* usMkaCryptoWrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoRandomJobRefCsmJobId */
     	  8,
     	  
     	  /* usMkaCryptoRandomDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoSakkeyRefCsmKeyId */
     	  9,
     	  
     	  /* usMkaCryptoSakKeyRefCsmKeyId */
     	  3,
     	  
     	  /* usMkaCryptoKekKeyRefCsmKeyId */
     	  3,
     	  
     	  /* usMkaCryptoICKKeyRefCsmKeyId */
     	  MKA_INVALID,
     	  
     	  /* blMkaParticipantActivate */
     	  STD_ON,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  1,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CSM_128,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x03}
     	},
     	/* Details of MkaKayParticipant_1 */
     	{
     	  
     	  /* ucMkaCryptoAlgoRefConfigIdx */
     	  2,
     	  
     	  /* usMkaCryptoCknCakKeyRefCsmKeyId */
     	  4,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmJobId */
     	  2,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvGenerateJobRefCsmJobId */
     	  3,
     	  
     	  /* usMkaCryptoIcvDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmJobId */
     	  4,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmJobId */
     	  5,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyUnwrapJobRefCsmJobId */
     	  6,
     	  
     	  /* usMkaCryptoUnwrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyWrapJobRefCsmJobId */
     	  7,
     	  
     	  /* usMkaCryptoWrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoRandomJobRefCsmJobId */
     	  8,
     	  
     	  /* usMkaCryptoRandomDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoSakkeyRefCsmKeyId */
     	  9,
     	  
     	  /* usMkaCryptoSakKeyRefCsmKeyId */
     	  0,
     	  
     	  /* usMkaCryptoKekKeyRefCsmKeyId */
     	  2,
     	  
     	  /* usMkaCryptoICKKeyRefCsmKeyId */
     	  MKA_INVALID,
     	  
     	  /* blMkaParticipantActivate */
     	  STD_ON,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  1,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CSM_128,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x04}
     	},
     	/* Details of MkaKayParticipant_0 */
     	{
     	  
     	  /* ucMkaCryptoAlgoRefConfigIdx */
     	  1,
     	  
     	  /* usMkaCryptoCknCakKeyRefCsmKeyId */
     	  5,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmJobId */
     	  2,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvGenerateJobRefCsmJobId */
     	  3,
     	  
     	  /* usMkaCryptoIcvDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmJobId */
     	  4,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmJobId */
     	  5,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyUnwrapJobRefCsmJobId */
     	  6,
     	  
     	  /* usMkaCryptoUnwrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyWrapJobRefCsmJobId */
     	  7,
     	  
     	  /* usMkaCryptoWrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoRandomJobRefCsmJobId */
     	  8,
     	  
     	  /* usMkaCryptoRandomDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoSakkeyRefCsmKeyId */
     	  9,
     	  
     	  /* usMkaCryptoSakKeyRefCsmKeyId */
     	  1,
     	  
     	  /* usMkaCryptoKekKeyRefCsmKeyId */
     	  2,
     	  
     	  /* usMkaCryptoICKKeyRefCsmKeyId */
     	  MKA_INVALID,
     	  
     	  /* blMkaParticipantActivate */
     	  STD_ON,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  1,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CSM_128,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x05}
     	},
     	/* Details of MkaKayParticipant_1 */
     	{
     	  
     	  /* ucMkaCryptoAlgoRefConfigIdx */
     	  2,
     	  
     	  /* usMkaCryptoCknCakKeyRefCsmKeyId */
     	  6,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmJobId */
     	  2,
     	  
     	  /* usMkaCryptoIckDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvGenerateJobRefCsmJobId */
     	  3,
     	  
     	  /* usMkaCryptoIcvDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmJobId */
     	  4,
     	  
     	  /* usMkaCryptoIcvVerifyJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmJobId */
     	  5,
     	  
     	  /* usMkaCryptoKekDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyUnwrapJobRefCsmJobId */
     	  6,
     	  
     	  /* usMkaCryptoUnwrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKeyWrapJobRefCsmJobId */
     	  8,
     	  
     	  /* usMkaCryptoWrapJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoRandomJobRefCsmJobId */
     	  9,
     	  
     	  /* usMkaCryptoRandomDeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoSakkeyRefCsmKeyId */
     	  10,
     	  
     	  /* usMkaCryptoSakKeyRefCsmKeyId */
     	  0,
     	  
     	  /* usMkaCryptoKekKeyRefCsmKeyId */
     	  2,
     	  
     	  /* usMkaCryptoICKKeyRefCsmKeyId */
     	  MKA_INVALID,
     	  
     	  /* blMkaParticipantActivate */
     	  STD_ON,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  1,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCrypto128_256_DeriveJobRefCsmProcessingType */
     	  MKA_CSM_128,
     	  
     	  /* usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  MKA_CRYPTO_PROCESSING_SYNC,
     	  
     	  /* usMkaCryptoKekDeriveJobRefProcessingModel */
     	  {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0x06}
     	}
     };
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     /* Design_ID          : MKA_SDD_XXXX  */
     #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     const Mka_PaeConfigurationType Mka_GaaPaeConfigurations[MKA_TOTAL_NUM_MKA_PAE_CONFIGURATION] =
     {
     	/* Details of MkaPaeConfiguration_0_MacSecProps */
     	{
     	  
     	  /* blMkaAutoStart */
     	  MKA_FALSE,
     	  
     	  /* ucMkaPaeConfigurationIdx */
     	  0,
     	  
     	  /* usMkaRetryBaseDelay */
     	  1.0,
     	  
     	  /* usMkaRetryCyclicDelay */
     	  1.0,
     	  
     	  /* usMkaSakRekeyTimeSpan */
     	  600.0
     	},
     	/* Details of MkaPaeConfiguration_1_MacSecProps */
     	{
     	  
     	  /* blMkaAutoStart */
     	  MKA_FALSE,
     	  
     	  /* ucMkaPaeConfigurationIdx */
     	  1,
     	  
     	  /* usMkaRetryBaseDelay */
     	  1.0,
     	  
     	  /* usMkaRetryCyclicDelay */
     	  1.0,
     	  
     	  /* usMkaSakRekeyTimeSpan */
     	  300.0
     	},
     	/* Details of MkaPaeConfiguration_2_MacSecProps */
     	{
     	  
     	  /* blMkaAutoStart */
     	  MKA_FALSE,
     	  
     	  /* ucMkaPaeConfigurationIdx */
     	  1,
     	  
     	  /* usMkaRetryBaseDelay */
     	  1.0,
     	  
     	  /* usMkaRetryCyclicDelay */
     	  1.0,
     	  
     	  /* usMkaSakRekeyTimeSpan */
     	  50.0
     	}
     };
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
      #define MKA_START_SEC_CONST_16
      #include "Mka_MemMap.h"
      /* Design ID :  MKA_SDD_XXXX */
      const uint16 Mka_GaaMkaBypassEtherType[MKA_TOTAL_NUM_OF_MKA_BYPASS_ETHERTYPE] = 
      {  
      	    	    100, 200, 300, 40, 20, 30, 40, 1, 2, 3, 4, 5, 6, 7
      };              
     #define MKA_STOP_SEC_CONST_16
     #include "Mka_MemMap.h"
          
      #define MKA_START_SEC_CONST_16
      #include "Mka_MemMap.h"
     /* Design ID :  MKA_SDD_XXXX */
      const uint16 Mka_GaaMkaBypassVlanType[MKA_TOTAL_NUM_OF_MKA_BYPASS_VLAN_TYPE] = 
      {   
      	    1, 2, 3, 4, 5, 6, 2, 3, 4, 1, 2, 3, 4, 5, 6, 67
      };              
     #define MKA_STOP_SEC_CONST_16
     #include "Mka_MemMap.h"
          
 #define MKA_START_SEC_CONST_16
 #include "Mka_MemMap.h"
/* Design ID :  MKA_SDD_XXXX */
 const uint8 Mka_GaaMkaDstAddressType[MKA_TOTAL_NUM_MKA_PAE_CONFIGURATION][6] = 
 {  
 	
 	{ 0x44 },
 	{ 0x52 },
 	{ 0x55 }

 };              
#define MKA_STOP_SEC_CONST_16
#include "Mka_MemMap.h"
     
      #define MKA_START_SEC_CONST_16
      #include "Mka_MemMap.h"
     /* Design ID :  MKA_SDD_XXXX */
      const uint8 Mka_GaaMkaSrcAddressType[MKA_TOTAL_NUM_MKA_PAE_CONFIGURATION][6] = 
      {  
      	
      	{ 0x23 },
      	{ 0x50 },
      	{ 0x45 }
     
      };              
     #define MKA_STOP_SEC_CONST_16
     #include "Mka_MemMap.h"
          
     /* Design_ID          : MKA_SDD_XXXX  */
     #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     const Mka_PaeInstanceType  Mka_GaaPaeInstances[MKA_TOTAL_NUM_MKA_PAE_INSTANCE] =
     {
     	/* Details of MkaPaeInstance_0_MacSecProps */
     	{
     	  
     	  /* ucMkaEthIfControllerIndex */
     	  0,
     	  
     	  /* pMkaBypassEtherType */
     	  &Mka_GaaMkaBypassEtherType[0],
     	  
     	  /* pMkaBypassVlan */
     	  &Mka_GaaMkaBypassVlanType[0],
     	  
     	  /* usMkaDstMacAddress */
     	  &Mka_GaaMkaDstAddressType[0][0],
     	  
     	  /* usMkaEAlogMismatchInstance */
     	  MKA_DEM_INVALID,
     	  
     	  /* usMkaEKeyMismatchInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* usMkaEKeyNotPresentInstance */
     	  DemConf_DemEventParameter_DemEventParameter_1,
     	  
     	  /* usMkaETimeoutInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* pMkaKayParticipants */
     	  &Mka_KayParticipant[0],
     	  
     	  /* ucindexofKayParticipant */
     	  0,
     	  
     	  /* ucMkaKeyServerPriority */
     	  0,
     	  
     	  /* ddMkaRole */
     	  MKA_KEY_SERVER,
     	  
     	  /* usMkaSrcMacAddress */
     	  &Mka_GaaMkaSrcAddressType[0][0],
     	  
     	  /* usMkaOnFailPermissiveMode */
     	  MKA_PERMISSIVE_MODE_NEVER,
     	  
     	  /* ucMkaOnFailPermissiveModeTimeout */
     	  255.0,
     	  
     	  /* ucMkaPaeConfRefIndex */
     	  0,
     	  
     	  /* ucMkaSwitchPortIndex */
     	  1,
     	  
     	  /* ucMkaPaeIdx */
     	  0,
     	  
     	  /* ucnoofKayParticipant */
     	  3
     	},
     	/* Details of MkaPaeInstance_1_MacSecProps */
     	{
     	  
     	  /* ucMkaEthIfControllerIndex */
     	  MKA_INVALID,
     	  
     	  /* pMkaBypassEtherType */
     	  &Mka_GaaMkaBypassEtherType[4],
     	  
     	  /* pMkaBypassVlan */
     	  &Mka_GaaMkaBypassVlanType[6],
     	  
     	  /* usMkaDstMacAddress */
     	  &Mka_GaaMkaDstAddressType[0][0],
     	  
     	  /* usMkaEAlogMismatchInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* usMkaEKeyMismatchInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* usMkaEKeyNotPresentInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* usMkaETimeoutInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* pMkaKayParticipants */
     	  &Mka_KayParticipant[3],
     	  
     	  /* ucindexofKayParticipant */
     	  3,
     	  
     	  /* ucMkaKeyServerPriority */
     	  45,
     	  
     	  /* ddMkaRole */
     	  MKA_KEY_SERVER,
     	  
     	  /* usMkaSrcMacAddress */
     	  &Mka_GaaMkaSrcAddressType[0][0],
     	  
     	  /* usMkaOnFailPermissiveMode */
     	  MKA_PERMISSIVE_MODE_NEVER,
     	  
     	  /* ucMkaOnFailPermissiveModeTimeout */
     	  200.0,
     	  
     	  /* ucMkaPaeConfRefIndex */
     	  1,
     	  
     	  /* ucMkaSwitchPortIndex */
     	  0,
     	  
     	  /* ucMkaPaeIdx */
     	  1,
     	  
     	  /* ucnoofKayParticipant */
     	  2
     	},
     	/* Details of MkaPaeInstance_2_MacSecProps */
     	{
     	  
     	  /* ucMkaEthIfControllerIndex */
     	  MKA_INVALID,
     	  
     	  /* pMkaBypassEtherType */
     	  &Mka_GaaMkaBypassEtherType[7],
     	  
     	  /* pMkaBypassVlan */
     	  &Mka_GaaMkaBypassVlanType[9],
     	  
     	  /* usMkaDstMacAddress */
     	  &Mka_GaaMkaDstAddressType[0][0],
     	  
     	  /* usMkaEAlogMismatchInstance */
     	  DemConf_DemEventParameter_DemEventParameter_1,
     	  
     	  /* usMkaEKeyMismatchInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* usMkaEKeyNotPresentInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* usMkaETimeoutInstance */
     	  DemConf_DemEventParameter_DemEventParameter_0,
     	  
     	  /* pMkaKayParticipants */
     	  &Mka_KayParticipant[5],
     	  
     	  /* ucindexofKayParticipant */
     	  5,
     	  
     	  /* ucMkaKeyServerPriority */
     	  52,
     	  
     	  /* ddMkaRole */
     	  MKA_PEER,
     	  
     	  /* usMkaSrcMacAddress */
     	  &Mka_GaaMkaSrcAddressType[0][0],
     	  
     	  /* usMkaOnFailPermissiveMode */
     	  MKA_PERMISSIVE_MODE_NEVER,
     	  
     	  /* ucMkaOnFailPermissiveModeTimeout */
     	  100.0,
     	  
     	  /* ucMkaPaeConfRefIndex */
     	  2,
     	  
     	  /* ucMkaSwitchPortIndex */
     	  0,
     	  
     	  /* ucMkaPaeIdx */
     	  2,
     	  
     	  /* ucnoofKayParticipant */
     	  2
     	}
     };
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     /* Design_ID          : MKA_SDD_XXXX  */
     #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     const Mka_CipherSuitesType Mka_GaaCipherSuites_MkaCryptoAlgoConfig_0_MacSecCryptoAlgoConfig[MKA_TOTAL_NUM_CIPHER_SUITES_MKA_CRYPTO_ALGO_CONFIG_0__MAC_SEC_CRYPTO_ALGO_CONFIG] =
     {
     	/* Details of MkaCipherSuites_0 */
     	{
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  GCM_AES_XPN_256,
     	  
     	  /* ddmkaMacSecCipherSuitePrio */
     	  2
     	},
     	/* Details of MkaCipherSuites_1 */
     	{
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  GCM_AES_XPN_128,
     	  
     	  /* ddmkaMacSecCipherSuitePrio */
     	  3
     	},
     	/* Details of MkaCipherSuites_2 */
     	{
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  GCM_AES_256,
     	  
     	  /* ddmkaMacSecCipherSuitePrio */
     	  2
     	},
     	/* Details of MkaCipherSuites_3 */
     	{
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  GCM_AES_128,
     	  
     	  /* ddmkaMacSecCipherSuitePrio */
     	  1
     	}
     };
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     /* Design_ID          : MKA_SDD_XXXX  */
     #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     const Mka_CipherSuitesType Mka_GaaCipherSuites_MkaCryptoAlgoConfig_1_MacSecCryptoAlgoConfig[MKA_TOTAL_NUM_CIPHER_SUITES_MKA_CRYPTO_ALGO_CONFIG_1__MAC_SEC_CRYPTO_ALGO_CONFIG] =
     {
     	/* Details of MkaCipherSuites_0 */
     	{
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  GCM_AES_XPN_128,
     	  
     	  /* ddmkaMacSecCipherSuitePrio */
     	  2
     	},
     	/* Details of MkaCipherSuites_1 */
     	{
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  GCM_AES_XPN_256,
     	  
     	  /* ddmkaMacSecCipherSuitePrio */
     	  4
     	}
     };
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     /* Design_ID          : MKA_SDD_XXXX  */
     #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     const Mka_CipherSuitesType Mka_GaaCipherSuites_MkaCryptoAlgoConfig_2_MacSecCryptoAlgoConfig[MKA_TOTAL_NUM_CIPHER_SUITES_MKA_CRYPTO_ALGO_CONFIG_2__MAC_SEC_CRYPTO_ALGO_CONFIG] =
     {
     	/* Details of MkaCipherSuites_0 */
     	{
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  GCM_AES_128,
     	  
     	  /* ddmkaMacSecCipherSuitePrio */
     	  1
     	}
     };
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     /* Design_ID          : MKA_SDD_XXXX  */
     #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     const Mka_CryptoAlgoConfigType  Mka_GaaCryptoAlgoConfig[MKA_TOTAL_NUM_MKA_PAE_CONFIGURATION] =
     {
     	/* Details of MkaCryptoAlgoConfig_0_MacSecCryptoAlgoConfig */
     	{
     	  
     	  /* pMkaCipherSuites */
     	  &Mka_GaaCipherSuites_MkaCryptoAlgoConfig_0_MacSecCryptoAlgoConfig[0],
     	  
     	  /* ucMkanoofciphersuites */
     	  4,
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  0,
     	  
     	  /* ddMkaMacSecCapability */
     	  INTEGRITY_WITHOUT_CONFIDENTIALITY,
     	  
     	  /* ddMkaMacSecConfidentialityOffset */
     	  CONFIDENTIALITY_OFFSET_50,
     	  
     	  /* blMkaMacSecReplayProtection */
     	  true,
     	  
     	  /* usMkaMacSecReplayProtectionWindow */
     	  100
     	},
     	/* Details of MkaCryptoAlgoConfig_1_MacSecCryptoAlgoConfig */
     	{
     	  
     	  /* pMkaCipherSuites */
     	  &Mka_GaaCipherSuites_MkaCryptoAlgoConfig_1_MacSecCryptoAlgoConfig[0],
     	  
     	  /* ucMkanoofciphersuites */
     	  2,
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  1,
     	  
     	  /* ddMkaMacSecCapability */
     	  INTEGRITY_AND_CONFIDENTIALITY,
     	  
     	  /* ddMkaMacSecConfidentialityOffset */
     	  CONFIDENTIALITY_OFFSET_30,
     	  
     	  /* blMkaMacSecReplayProtection */
     	  true,
     	  
     	  /* usMkaMacSecReplayProtectionWindow */
     	  50
     	},
     	/* Details of MkaCryptoAlgoConfig_2_MacSecCryptoAlgoConfig */
     	{
     	  
     	  /* pMkaCipherSuites */
     	  &Mka_GaaCipherSuites_MkaCryptoAlgoConfig_2_MacSecCryptoAlgoConfig[0],
     	  
     	  /* ucMkanoofciphersuites */
     	  1,
     	  
     	  /* ucMkaCryptoAlgoConfigIdx */
     	  2,
     	  
     	  /* ddMkaMacSecCapability */
     	  INTEGRITY_WITHOUT_CONFIDENTIALITY,
     	  
     	  /* ddMkaMacSecConfidentialityOffset */
     	  CONFIDENTIALITY_OFFSET_30,
     	  
     	  /* blMkaMacSecReplayProtection */
     	  true,
     	  
     	  /* usMkaMacSecReplayProtectionWindow */
     	  100
     	}
     };
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"

     
     
     
     

/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
