/*******************************************************************************
**  FILE-NAME: EthIf_Lcfg.c                                                 **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_5/PB_Config/xml/EthIf_Config_5.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:43:09 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/**
  *
  * #section EthIf_Cfg_C_REF_1
  * Violates MISRA 2012 Advisory Rule 20.1,
  * #include directives should only be preceded by preprocessor directives or
  * comments.
  *
**/

/* PRQA S 0380 EOF */
/* violates Number of macro definitions exceeds 4095 - program does not */
/* conform strictly to ISO:C99 */ /*invalid QAC as total number of macros in */
/* code are less than 4095*/

/* Violates #ref EthIf_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
/* PRQA S 5087 EOF */
/* PRQA S 1290 EOF */
/* PRQA S 5002 EOF */
/* PRQA S 1582 EOF */
/* PRQA S 4640 EOF */
/******************************************************************************/
#include "EthIf.h"
#include "EthIf_Cfg.h"
#include "EthIf_IntTypes.h"
#include "TcpIp.h"
#include "EthSM.h"
#include "EthIf_Version.h"
#include "Cdd.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (ETHIF_VERSION_AR_RELEASE_MAJOR_VERSION != ETHIF_AR_RELEASE_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Major Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_MINOR_VERSION != ETHIF_AR_RELEASE_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Minor Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_REVISION_VERSION != ETHIF_AR_RELEASE_REVISION_VERSION)
  #error "ETHIF Code : Mismatch in Specification Revision Version"
#endif

#if (ETHIF_VERSION_SW_MAJOR_VERSION != ETHIF_SW_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Major Version"
#endif

#if (ETHIF_VERSION_SW_MINOR_VERSION != ETHIF_SW_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/



/* Design ID : ETHIF_SDD_0619*/
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_WakeupSourceType
  EthIf_GaaWakeupSource[ETHIF_TOTAL_NUM_OF_WAKEUPSOURCE] =
{
/* EthIf_WakeupSourceType - EthTrcvWakeupMap_0 */
{
  
  /* WakeupSource */
  0x2U,
  
  /* pTrcvDriver */
  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
  
  /* Referred Trcv Idx */
  0x00U
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"





/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
