/*******************************************************************************
**  FILE-NAME: Mka_Cfg.h                                                    **
**                                                                            **
**  MODULE-NAME: Mka                                                          **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.5.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../151_MKa_TESTING/Code_Compliance/Config/Mka_Config_1/PC_Config/xml/Mka_Config_1.arxml
 *   ../../../151_MKa_DELIVERY/ssc/generator/KPIT_AUTOSAR_R24-11_MKA_BSWMD.arxml
 *   ../../../151_MKa_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2026 Apr 08 16:46:43 IST
 */
#ifndef MKA_CFG_H
#define MKA_CFG_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "Std_Types.h"
#include "Dem_Cfg.h"     


/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define MKA_AR_RELEASE_MAJOR_VERSION    4
#define MKA_AR_RELEASE_MINOR_VERSION    10
#define MKA_AR_RELEASE_REVISION_VERSION 0
#define MKA_SW_MAJOR_VERSION            0
#define MKA_SW_MINOR_VERSION            5
#define MKA_SW_PATCH_VERSION            0
#define MKA_VENDOR_ID                   (uint16)0
#define MKA_MODULE_ID                   (uint16)151

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/
/* Pre-compile for the development error detection and notification on or off*/
/* Design_ID          : MKA_SDD_XXXX  */
#define MKA_DEV_ERROR_DETECT                             STD_ON

#define MKA_INVALID                                      0x00

/*  Switches the reporting of security events to the IdsM:*/
/* Design_ID          : MKA_SDD_XXXX  */
#define MKA_ENABLE_SECURITY_EVENT_REPORTING               STD_OFF

/* */
/* Design_ID          : MKA_SDD_XXXX  */
#define MKA_HELLO_TIME                       2.0U

/* Time span [s] since last MKPDU was received from the other participant, to consider it alive. */
/* Design_ID          : MKA_SDD_XXXX  */
#define MKA_LIFE_TIME                        6.0U

/* The cycle time of the periodic main function of MKA. Defined in seconds. */
/* Design_ID          : MKA_SDD_XXXX  */
#define MKA_MAIN_FUNCTION_PERIOD              1.0U

/* During an SAK rekey, time [s] to retire the previous SAK in use..*/
/* Design_ID          : MKA_SDD_XXXX  */
#define MKA_SAK_RETIRE_TIME                   3.0U

/* Pre - Compile to Enables / Disables version info API.*/
/* Design_ID          : MKA_SDD_XXXX  */
#define MKA_VERSION_INFO_API                  STD_OFF	 

/* Design ID: MKA_SDD_XXXX */
/* Pre-compile option for variant-support */
#define MKA_PRE_COMPILE_SINGLE               STD_ON
     
#define MKA_TOTAL_NUM_MKA_PAE_CONFIGURATION               3U

#define MKA_TOTAL_NUM_MKA_PAE_INSTANCE               3U

#define MKA_TOTAL_NUM_CRYPTO_ALGO_CONFIG             3U


     #define MKA_TOTAL_NUM_CIPHER_SUITES_MKA_CRYPTO_ALGO_CONFIG_0__MAC_SEC_CRYPTO_ALGO_CONFIG       4U
     #define MKA_TOTAL_NUM_CIPHER_SUITES_MKA_CRYPTO_ALGO_CONFIG_1__MAC_SEC_CRYPTO_ALGO_CONFIG       2U
     #define MKA_TOTAL_NUM_CIPHER_SUITES_MKA_CRYPTO_ALGO_CONFIG_2__MAC_SEC_CRYPTO_ALGO_CONFIG       1U

#define MKA_TOTAL_NUM_CIPHER_SUITES                  7U

#define MKA_TOTAL_NUM_OF_MKA_BYPASS_ETHERTYPE       14U

#define MKA_TOTAL_NUM_OF_MKA_BYPASS_VLAN_TYPE        16U


#define MKA_TOTAL_NUM_KAY_PARTICIPANT                7U



/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/

/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/

 typedef enum ETag_Mka_MacSecEncyptionType
 {
 MKA_CSM_128 = 0,
 MKA_CSM_256,
 MKA_CSM_NO_VALUE
 } Mka_MacSecEncyptionType;
 
 typedef enum ETag_Mka_MacSecJobSYNASYNCType
 {
 MKA_CRYPTO_PROCESSING_SYNC = 0,
 MKA_CRYPTO_PROCESSING_ASYNC,
 MKA_CRYPTO_NO_VALUE
 } Mka_MacSecJobSYNASYNCType;
 /* In future We will move to Pctypes.h*/
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Structure to hold MKA PAE Configuration */
 
 typedef struct STag_Mka_PaeConfigurationType {
 
 boolean blMkaAutoStart;
 uint8 ucMkaPaeConfigurationIdx;
 uint16 usMkaRetryBaseDelay;                    /* type chnage derive data type to uint16 */
 uint16 usMkaRetryCyclicDelay;                  /* type chnage derive data type to uint16 */
 uint16 usMkaSakRekeyTimeSpan;                  /* type chnage derive data type to uint16 */
 
 }Mka_PaeConfigurationType;
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Structure to hold MKA KayParticipant reference */
 typedef struct STag_Mka_KayParticipants {
 /* ref of the MkaCryptoAlgoConfigIdx from MkaCryptoAlgoConfig  */
 	uint8 ucMkaCryptoAlgoRefConfigIdx;
 /* ref of the CsmKeyId  from CsmKeys  */	 	      
 	uint32 usMkaCryptoCknCakKeyRefCsmKeyId;
 /* ref of the CsmJobId from CsmJobs  */	
 	uint32 usMkaCryptoIckDeriveJobRefCsmJobId;
 /* ref of the CsmProcessingtype from ICK CsmJobs  */
 	uint8  usMkaCryptoIckDeriveJobRefCsmProcessingType;
 /* ref of the CsmJobId from CsmJobs  */		 	
 	uint32 usMkaCryptoIcvGenerateJobRefCsmJobId;
 /* ref of the CsmProcessingtype from Icv CsmJobs  */
 uint8  usMkaCryptoIcvDeriveJobRefCsmProcessingType;
 /* ref of the CsmJobId from CsmJobs  */	
 	uint32 usMkaCryptoIcvVerifyJobRefCsmJobId;
 /* ref of the CsmProcessingtype from IcvVerify CsmJobs  */
 uint8  usMkaCryptoIcvVerifyDeriveJobRefCsmProcessingType;
 /* ref of the CsmJobId from CsmJobs  */	
 	uint32 usMkaCryptoKekDeriveJobRefCsmJobId;
 /* ref of the CsmProcessingtype from Kek CsmJobs  */
 	uint8  usMkaCryptoKekDeriveJobRefCsmProcessingType;
 /* ref of the CsmJobId from CsmJobs  */	
    uint32 usMkaCryptoKeyUnwrapJobRefCsmJobId;
 /* ref of the CsmProcessingtype from unwrap CsmJobs  */
    uint8  usMkaCryptoUnwrapDeriveJobRefCsmProcessingType;
 /* ref of the CsmJobId from CsmJobs  */	
 	uint32 usMkaCryptoKeyWrapJobRefCsmJobId;
 /* ref of the CsmProcessingtype from Wrap CsmJobs  */
 uint8  usMkaCryptoWrapDeriveJobRefCsmProcessingType;
 /* ref of the CsmJobId from CsmJobs  */	
 	uint32 usMkaCryptoRandomJobRefCsmJobId;
 /* ref of the CsmProcessingtype from Random CsmJobs  */
    uint8  usMkaCryptoRandomDeriveJobRefCsmProcessingType;
 /* ref of the CsmJobId from CsmJobs  */	
 	uint32 usMkaCryptoSakDeriveJobRefCsmJobId;
 /* ref of the CsmProcessingtype from Sak CsmJobs  */
    uint8  usMkaCryptoSakDeriveJobRefCsmProcessingType;
 /* ref of the CsmKeyId  from CsmKeys  */	
 	uint32 usMkaCryptoSakKeyRefCsmKeyId;
 /* ref of the CsmKeyId  from CsmKeys  */	
    uint32 usMkaCryptoKekKeyRefCsmKeyId;
 /* ref of the CsmKeyId  from CsmKeys  */	
 	uint32 usMkaCryptoICKKeyRefCsmKeyId;
 	
 	boolean blMkaParticipantActivate;
 /*Ref to usMkaCryptoHashKey128DerivationJobId,usMkaCryptoHashKey256DerivationJobId*/
 	uint32 usMkaCryptoHashKey128_256DerivationJobId;
 /* ref of the CsmProcessingtype from 128_256 CsmJobs  */
 uint8  usMkaCrypto128_256_DeriveJobRefCsmProcessingType;
 	
 Mka_MacSecEncyptionType usMkaEncryptionType;
 
 Mka_MacSecJobSYNASYNCType usMkaSyncAsyncType;
 Mka_MacSecJobSYNASYNCType usMkaSyncAsyncKekType;
 
 /*32 byte array has to decalred*/
 uint8 Mka_Ckn[16];
 
 
 
 
 }Mka_KayParticipants;
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Enum to hold Mka_RoleType */
 typedef enum ETag_Mka_RoleType
 { 
 	MKA_KEY_SERVER = 0,
 	MKA_PEER = 255
 	
 }Mka_RoleType;
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Structure to hold MKA PAE Instances */
 typedef struct STag_Mka_PaeInstanceType {
 	
      uint8 ucMkaEthIfControllerIndex;
      
      const uint16 *pMkaBypassEtherType;                /* this parameter under MkaKay container */             
 	  
 	  const uint16 *pMkaBypassVlan;                    /* this parameter under MkaKay container */
 	
 	  const uint8 *usMkaDstMacAddress;                       /* this parameter under MkaKay container */
 	  
 	  uint16 usMkaEAlogMismatchInstance;               /* this parameter under MkaKay --> MkaKayDemEventParameterRefs  container */
 	  uint16 usMkaEKeyMismatchInstance;                /* this parameter under MkaKay --> MkaKayDemEventParameterRefs  container */
 	  uint16 usMkaEKeyNotPresentInstance;              /* this parameter under MkaKay --> MkaKayDemEventParameterRefs  container */
 	  uint16 usMkaETimeoutInstance;                    /* this parameter under MkaKay --> MkaKayDemEventParameterRefs  container */
 	  const Mka_KayParticipants *pMkaKayParticipants;
 	  uint8 ucindexofKayParticipant;
 	  uint8 ucMkaKeyServerPriority;                    /* this parameter under MkaKay container */
 	  Mka_RoleType ddMkaRole;                          /* this parameter under MkaKay container */
 	  const uint8 * usMkaSrcMacAddress;                       /* this parameter under MkaKay container */
 	  
 	  uint16 usMkaOnFailPermissiveMode;                /* type chnage derive data type to uint16 */
 	  uint8 ucMkaOnFailPermissiveModeTimeout;
 	  uint8 ucMkaPaeConfRefIndex;
 	  uint8 ucMkaSwitchPortIndex;
 	  uint8 ucMkaPaeIdx;
 	  uint8 ucnoofKayParticipant;
 	  
 	  
 }Mka_PaeInstanceType;
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Enum to hold Mka_MacSecCapablity */
 typedef enum ETag_Mka_MacSecCapablity
 {
   INTEGRITY_AND_CONFIDENTIALITY = 0,
   INTEGRITY_WITHOUT_CONFIDENTIALITY
 } Mka_MacSecCapablity;
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Enum to hold Mka_MacSecConfidentialityOffset */
 typedef enum ETag_Mka_MacSecConfidentialityOffset
 {
   CONFIDENTIALITY_OFFSET_0 = 0,
   CONFIDENTIALITY_OFFSET_30,
   CONFIDENTIALITY_OFFSET_50
 } Mka_MacSecConfidentialityOffset;
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Enum to hold Mka_MacSecCipherSuiteType */
 /*Enum has been initialized with value 1 to align with the TLV 112 frame and to avoid additional functions*/
 typedef enum ETag_Mka_MacSecCipherSuiteType
 {
   GCM_AES_128 = 1,
   GCM_AES_256,
   GCM_AES_XPN_128,
   GCM_AES_XPN_256
 } Mka_MacSecCipherSuiteType;
 
 
 
 
 typedef struct STag_Mka_CipherSuitesType 
 {
   Mka_MacSecCipherSuiteType ddMkaMacSecCipherSuite;
   uint8 ucMkaMacSecCipherSuitePrio;  	
 }Mka_CipherSuitesType;
 
 /* Design_ID          : MKA_SDD_XXXX */
 /* Structure to hold MKA Crypto Algo Configuration */
 typedef struct STag_Mka_CryptoAlgoConfigType {
 	  const Mka_CipherSuitesType *pMkaCipherSuites;
 		  uint8 ucnoofciphersuites;
 	  uint8 ucMkaCryptoAlgoConfigIdx;
 	  Mka_MacSecCapablity ddMkaMacSecCapability;
 	  Mka_MacSecConfidentialityOffset ddMkaMacSecConfidentialityOffset;
 	  boolean blMkaMacSecReplayProtection;
 	  uint8 usMkaMacSecReplayProtectionWindow;
 }Mka_CryptoAlgoConfigType;
 
   	/*******************************************************************************
   	**                            Array Declarations                              **
   	*******************************************************************************/
   	
   	/* Design_ID          : MKA_SDD_XXXX  */
   	#define MKA_START_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
   	extern const Mka_PaeConfigurationType Mka_GaaPaeConfigurations[MKA_TOTAL_NUM_MKA_PAE_CONFIGURATION];
   	#define MKA_STOP_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
   	
   	
   	/* Design_ID          : MKA_SDD_XXXX  */
   	#define MKA_START_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
   	extern const Mka_PaeInstanceType Mka_GaaPaeInstances[MKA_TOTAL_NUM_MKA_PAE_INSTANCE];
   	#define MKA_STOP_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
   	
   	
   	/* Design_ID          : MKA_SDD_XXXX  */
   	#define MKA_START_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
   	extern const Mka_CryptoAlgoConfigType  Mka_GaaCryptoAlgoConfig[MKA_TOTAL_NUM_CRYPTO_ALGO_CONFIG];
   	#define MKA_STOP_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
   	
   	/* Design_ID          : MKA_SDD_XXXX  */
   	#define MKA_START_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
   	extern const Mka_CipherSuitesType  Mka_GaaCipherSuites[MKA_TOTAL_NUM_CIPHER_SUITES];
   	#define MKA_STOP_SEC_CONST_UNSPECIFIED
   	#include "Mka_MemMap.h"
 
 #define MKA_START_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"
     extern const Mka_KayParticipants Mka_KayParticipant[MKA_TOTAL_NUM_KAY_PARTICIPANT];
     #define MKA_STOP_SEC_CONST_UNSPECIFIED
     #include "Mka_MemMap.h"

    

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/

#endif /* MKA_CFG_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
