/*******************************************************************************
**  FILE-NAME: Mka_External_Cfg.h                                           **
**                                                                            **
**  MODULE-NAME: Mka                                                          **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.5.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../151_MKa_TESTING/Code_Compliance/Config/Mka_Config_1/PC_Config/xml/Mka_Config_1.arxml
 *   ../../../151_MKa_DELIVERY/ssc/generator/KPIT_AUTOSAR_R24-11_MKA_BSWMD.arxml
 *   ../../../151_MKa_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2026 Apr 08 16:46:43 IST
 */
#ifndef MKA_EXTERNAL_CFG_H
#define MKA_EXTERNAL_CFG_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "Std_Types.h"
#include "Csm.h"    


/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define MKA_AR_RELEASE_MAJOR_VERSION    4
#define MKA_AR_RELEASE_MINOR_VERSION    10
#define MKA_AR_RELEASE_REVISION_VERSION 0
#define MKA_SW_MAJOR_VERSION            0
#define MKA_SW_MINOR_VERSION            5
#define MKA_SW_PATCH_VERSION            0
#define MKA_VENDOR_ID                   (uint16)0
#define MKA_MODULE_ID                   (uint16)151

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/

/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/

/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/

 	/* Design_ID          : MKA_SDD_XXXX */
   	#define MKA_START_SEC_MKA_CALLOUT_KEK_KDF_CODE
   	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
   	** Rule 20.1. */
   	#include "Mka_MemMap.h"
   	
     extern Std_ReturnType Mka_Callout_KEK_KDF( 
     					uint32 JobId, 
 					uint32 SrcKeyID, 
 					uint32 trgtKeyID, 
 					char Label[], 
 					const uint8* KeyName, 
 					uint16 KeyLength);
   	
   	#define MKA_STOP_SEC_MKA_CALLOUT_KEK_KDF_CODE
   	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
   	** Rule 20.1. */
   	#include "Mka_MemMap.h"
   	
   	
   	/* Design_ID          : MKA_SDD_XXXX */
   	#define MKA_START_SEC_MKA_CALLOUT_ICK_KDF_CODE
   	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
   	** Rule 20.1. */
   	#include "Mka_MemMap.h"
   	 extern Std_ReturnType Mka_Callout_ICK_KDF( 
 	 				uint32 JobId, 
 					uint32 SrcKeyID, 
 					uint32 trgtKeyID, 
 					char Label[], 
 					const uint8* KeyName, 
 					uint16 KeyLength);
   	#define MKA_STOP_SEC_MKA_CALLOUT_ICK_KDF_CODE
   	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
   	** Rule 20.1. */
   	#include "Mka_MemMap.h"
   	
   	#define MKA_START_SEC_MKA_CALLOUT_ICV_KDF_CODE
   	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
   	** Rule 20.1. */
   	#include "Mka_MemMap.h"
   	extern Std_ReturnType Mka_ICV_Generation_Callout(
   	                                  uint8 PaeIdx, 
   	                                  uint32 JobId, 
   	                                  uint32 ICKKey,
   	                                  const uint8*  dataPtr,
   	                                  uint32  dataLength,
   	                                  uint8*  resultPtr,
   	                                  uint32*  resultLengthPtr);
   	#define MKA_STOP_SEC_MKA_CALLOUT_ICV_KDF_CODE
   	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
   	** Rule 20.1. */
   	#include "Mka_MemMap.h" 
 
 
 
 	/* Design_ID          : MKA_SDD_XXXX */
    	#define MKA_START_SEC_MKA_CALLOUT_SAK_KDF_CODE
    	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
    	** Rule 20.1. */
    	#include "Mka_MemMap.h"
    	 extern Std_ReturnType Mka_Callout_SAK_KDF( 
 										uint32 JobId, 
 										uint32 SrcKeyID, 
 										uint32 trgtKeyID, 
 										char Label[], 
 										const uint8* KeyName, 
 										uint16 KeyLength);
    	#define MKA_STOP_SEC_MKA_CALLOUT_SAK_KDF_CODE
    	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
    	** Rule 20.1. */
    	#include "Mka_MemMap.h"
    	
    	
    	#define MKA_START_SEC_MKA_CAK_AVAILABLE_CALLOUT_CODE
    	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
    	** Rule 20.1. */
    	#include "Mka_MemMap.h"
    	extern Std_ReturnType Mka_CAK_Available_Callout( 
    											uint32 KeyId);
    	#define MKA_STOP_SEC_MKA_CAK_AVAILABLE_CALLOUT_CODE
    	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
    	** Rule 20.1. */
    	#include "Mka_MemMap.h"
 
    	/* Design_ID          : MKA_SDD_XXXX */
    	#define MKA_START_SEC_MKA_CALLOUT_RANDOM_CODE
    	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
    	** Rule 20.1. */
    	#include "Mka_MemMap.h"
    	
    	extern Std_ReturnType  Mka_Callout_Random_Generate(uint8 jobid, 
    	                                                    uint8 * Mka_Memberidentity_Ptr,
    	                                                    uint32 *Mka_MI_Length );
     #define MKA_STOP_SEC_MKA_CALLOUT_RANDOM_CODE
     /* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
     ** Rule 20.1. */
     #include "Mka_MemMap.h"
  
  
    	
 /* Design_ID          : MKA_SDD_XXXX */
    	#define MKA_START_SEC_MKA_CALLOUT_MACVERIFY_CODE
    	/* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
    	** Rule 20.1. */
    	#include "Mka_MemMap.h"
    	
 extern Std_ReturnType Mka_Callout_Mac_Verify(
    	    uint8 Jobid,
    	    Crypto_OperationModeType operationmode,
    	    const uint8 * dataptr,
    	    uint32 Length,
    	    const  uint8 *Macptr,
    	    uint32 Maclength,
    	    Crypto_VerifyResultType *verifyPtr);
    	    
     #define MKA_STOP_SEC_MKA_CALLOUT_MACVERIFY_CODE
     /* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
     ** Rule 20.1. */
     #include "Mka_MemMap.h"
 
 
 
 #define MKA_START_SEC_MKA_CALLOUT_UNWRAP_CODE
 /* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
 ** Rule 20.1. */
 #include "Mka_MemMap.h"
 
  extern Std_ReturnType   Mka_Callout_Unwrap(
    uint32 Jobid,
    uint32 TargetKeyId,
    const uint8 *CipherTextptr,
    uint32 Ciphertextlength,
    const uint8 *AuthenticatorPtr,
    uint32 Authenticatorlength,
    Crypto_VerifyResultType *verifyPtr);
 
 
  #define MKA_STOP_SEC_MKA_CALLOUT_UNWRAP_CODE
  /* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
  ** Rule 20.1. */
 #include "Mka_MemMap.h"
 
 
 
 
 #define MKA_START_SEC_MKA_CALLOUT_WRAP_CODE
 /* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
 ** Rule 20.1. */
 #include "Mka_MemMap.h"
 
   extern Std_ReturnType Mka_Callout_Wrap(
    uint32 Jobid,
    uint32 TargetKeyId,
    uint8  *CipherTextptr,
    uint32 *Ciphertextlength,
    uint8  *AuthenticatorPtr,
    uint32 *Authenticatorlength
    );
     
 #define MKA_STOP_SEC_MKA_CALLOUT_WRAP_CODE
  /* #violates #ref Mka_Callout_C_REF_1 Violates MISRA 2012 Advisory
  ** Rule 20.1. */
 #include "Mka_MemMap.h"


/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/

#endif /* MKA_EXTERNAL_CFG_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
