/*******************************************************************************
**  FILE-NAME: EthIf_Cfg.h                                                  **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_5/PB_Config/xml/EthIf_Config_5.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:43:09 IST
 */
#ifndef ETHIF_CFG_H
#define ETHIF_CFG_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "EcuM_Types.h"
#include "ComStack_Types.h"
#include "EthTrcv.h"


/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define ETHIF_AR_RELEASE_MAJOR_VERSION    4
#define ETHIF_AR_RELEASE_MINOR_VERSION    10
#define ETHIF_AR_RELEASE_REVISION_VERSION 0
#define ETHIF_SW_MAJOR_VERSION            0
#define ETHIF_SW_MINOR_VERSION            7
#define ETHIF_SW_PATCH_VERSION            0
#define ETHIF_VENDOR_ID                   (uint16)39
#define ETHIF_MODULE_ID                   (uint16)65

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/
/* Design_ID :  ETHIF_SDD_0401 */
/* Safetyksar inclusion required */
#define ETHIF_SAFE_KSAR                         STD_OFF
 /* Design ID : ETHIF_SDD_0592 */
 /*  Pre-compile option for variant-support */
 #define ETHIF_PRE_COMPILE_SINGLE                STD_OFF
 /* Design ID : ETHIF_SDD_0595*/
 /* Precompile option to check if Version Info API is Enabled */
 #define ETHIF_VERSIONINFO_API                   STD_ON
 /* Design ID : ETHIF_SDD_0709*/
 /* Precompile option to check if WETH API is Enabled */
 #define ETHIF_ENABLE_WETH_API                   STD_OFF
 /* Design ID : ETHIF_SDD_0588*/
 /* Precompile option to check if Development Error is Enabled */
 #define ETHIF_DEV_ERROR_DETECT                  STD_ON
 /* Design ID : ETHIF_SDD_0331*/
 /* Precompile option to check if Rx Polling is Enabled */
 #define ETHIF_ENABLE_RX_INTERRUPT               STD_OFF
 /* Design ID : ETHIF_SDD_0332*/
 /* Precompile option to check if Tx Polling is Enabled */
 #define ETHIF_ENABLE_TX_INTERRUPT               STD_ON
 /* Design ID : ETHIF_SDD_0590*/
 /* Precompile option to check if Get Baud Rate API is Enabled */
 #define ETHIF_GET_BAUDRATE                      STD_ON
 /* Design ID : ETHIF_SDD_0357*/
 /* Precompile option to check if Get Counter State API is Enabled */
 #define ETHIF_GET_COUNTER_STATE                 STD_ON
 /* Design ID : ETHIF_SDD_0350*/
 /* Precompile option to check if Global Time Support API is Enabled */
 #define ETHIF_GLOBALTIME_SUPPORT                STD_ON
 /* Design ID : ETHIF_SDD_0351*/
 /* Precompile option to check if Start Auto Negotiation API is Enabled */
 #define ETHIF_START_AUTO_NEGOTIATION            STD_ON
 /* Design ID : ETHIF_SDD_0322*/
 /* Precompile option to check if WakeUp Support is Enabled */
 #define ETHIF_WAKEUP_SUPPORT                    STD_ON
 /* Design ID : ETHIF_SDD_0320*/
 /* Value of EthIfTrcvLinkStateChgMainReload */
 #define ETHIF_TRCVLINKSTATECHGMAINRELOAD        2
 /* Design ID : ETHIF_SDD_0335*/
 /* Maximum number of iterations done in Mainfunction Rx */
 #define ETHIF_RXINDICATION_ITERATIONS           5
 /* Design ID : ETHIF_SDD_0569*/
 /* Design ID : ETHIF_SDD_0572 */
 /* Total number of controllers*/
 #define ETHIF_NUM_OF_CONTROLLERS                4U

 /* Design ID : ETHIF_SDD_0573 */
 /*Total number of physical controllers */
 #define ETHIF_NUM_OF_PHYSICAL_CONTROLLERS      1U

 #define ETHIF_NUM_OF_CLKUNIT                   1U

 #define ETHIF_CLKUNIT_INDEX                    1U

 /* Total number of ClkUnits */
 #define ETHIF_ETH_CLKUNIT_COUNT                2U

 /* Design ID : ETHIF_SDD_0575*/
 /* Total number of Transceivers*/
 #define ETHIF_NUM_OF_TRANSCEIVERS               1U

 /* Design ID : ETHIF_SDD_0574*/
 /* Total number of switches */
 #define ETHIF_NUM_OF_SWITCHES                   1U
 /* Design ID : ETHIF_SDD_0584*/
 /* Number of containers configured of EthIfTxConfirmationConfig */
 #define ETHIF_UL_TXCONFIRMATION_NUM             1U
 /* Design ID : ETHIF_SDD_0582 */
 /* Number of containers configured of EthIfTrcvLinkStateChgConfig */
 #define ETHIF_UL_LINKSTATECHANGE_NUM            1U
 /* Design ID : ETHIF_SDD_0582 */
 /* Number of containers configured of EthIfTrcvLinkStateChgConfig */
 #define ETHIF_MKA_LINKSTATECHANGE_NUM            0U
 /* Design ID : ETHIF_SDD_0583 */
 /* Number of containers configured of EthIfRxIndicationConfig */
 #define ETHIF_UL_RXINDICATION_NUM               2U
 /* Design ID : ETHIF_SDD_0571*/
 /* Number of containers configured of EthIfFrameOwnerConfig */
 #define ETHIF_NUM_FRAME_OWNER                   2U
 /* Design ID : ETHIF_SDD_0579 */
 /* Total number of Switch drivers */
 #define ETHIF_SWT_DRIVER_COUNT                  1U
 /* Design ID : ETHIF_SDD_0355*/
 /* period of main function EthIf_MainFunctionRx and EthIf_MainFunctionTx
    in seconds */
 #define ETHIF_MAIN_FUNC_PERIOD                  0.005


/* Precompile option for EthIf_GetPortMacAddr API */
#define ETHIF_GET_PORT_MAC_ADDR_API              STD_ON

/* Precompile option for EthIf_GetArlTable API */
#define ETHIF_GET_ARL_TABLE                     STD_ON

/* Precompile option for EthIf_StoreConfiguration API */
#define ETHIF_STORE_CONFIGURATION_API           STD_ON


  /* Precompile option for EthIf_ResetConfiguration API */
 #define ETHIF_RESET_CONFIGURATION_API           STD_ON

 /* Design ID : ETHIF_SDD_0586*/
 /* Macro to check whether VLAN is supported */
 #define ETHIF_VLAN_SUPPORT                      STD_ON
/* Design ID : ETHIF_SDD_0567*/
 /* Macro to check whether CDD is supported */
 #define ETHIF_CDD_SUPPORT                       STD_ON
  /* Design ID : ETHIF_SDD_0580*/
 /* Macro for total number of WakeupSource configured */
 #define ETHIF_TOTAL_NUM_OF_WAKEUPSOURCE         1U
 /* Design ID : ETHIF_SDD_0018 */
 /* Precompile option to check if SecurityEventReporting is Enabled */
 #define ETHIF_SECURITY_EVENT_ENABLED            STD_OFF

 /* Design ID : ETHIF_SDD_0019 */
 /* Precompile option to check if GetAndResetMeasurementData API is Enabled */
 #define ETHIF_MEASUREMENT_DATA_API            STD_OFF

 /* Design ID : ETHIF_SDD_0021 */
 /* Precompile option to check if GetCtrlIdxList API is Enabled */
 #define ETHIF_GET_CTRLIDXLIST_API            STD_ON

 /* Design ID : ETHIF_SDD_0022 */
 /* Precompile option to check if GetVlanId API is Enabled */
 #define ETHIF_GET_VLANID_SUPPORT            STD_ON



 #define ETHIF_NO_OF_TXPOOLS                 0
 #define ETHIF_NO_OF_RXPOOLS                 0
 #define ETHIF_RXPOOLIDX_MAP_SIZE            1
 #define ETHIF_NO_OF_TXPDUS                  0
 #define ETHIF_NO_OF_RXPDUS                  0
 #define ETHIF_RELEASERXBUFF_SUPPORT         STD_OFF
 #define ETHIF_METADATA_SUPPORT              STD_OFF

 /* Design ID : ETHIF_SDD_0xxx */
 /* Total number of PAE INSTANCES */
 #define ETHIF_NUM_OF_PAE_INSTANCES             0U

 /* Design ID : ETHIF_SDD_0xxx */
 /* Precompile option to check if Macsec is Enabled */
 #define ETHIF_MACSEC_SUPPORT_ENABLED             STD_OFF

 #define ETHIF_SW_MACSEC_CTRL_COUNT               0x0u


/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/
/* Handle IDs for EthIfCtrlIdx */
#define EthIfConf_EthIfController_EthIfController_0                          (uint8)0
#define EthIfConf_EthIfController_EthIfController_1                          (uint8)1
#define EthIfConf_EthIfController_EthIfController_2                          (uint8)2
#define EthIfConf_EthIfController_EthIfController_3                          (uint8)3

/* Handle IDs for EthIfPhysControllerIdx */
#define EthIfConf_EthIfPhysController_EthIfPhysController_0                      (uint8)0

/* Handle IDs for EthIfSwitchIdx */
#define EthIfConf_EthIfSwitch_EthIfSwitch_0                              (uint8)0

/* Handle IDs for EthIfTransceiverIdx */
#define EthIfConf_EthIfTransceiver_EthIfTransceiver_0                         (uint8)0

/* Handle IDs for EthIfClkUnitIdx  */
#define EthIfConf_EthIfPhysController_0_EthIfClkUnit_EthIfClkUnit_0   (uint8)0




/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/

/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/

#endif /* ETHIF_CFG_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
