/*******************************************************************************
**  FILE-NAME: EthIf_External.h                                             **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_1/PC_Config/xml/EthIf_Config_1.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:41:27 IST
 */
#ifndef ETHIF_EXTERNAL_H
#define ETHIF_EXTERNAL_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/

/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define ETHIF_AR_RELEASE_MAJOR_VERSION    4
#define ETHIF_AR_RELEASE_MINOR_VERSION    10
#define ETHIF_AR_RELEASE_REVISION_VERSION 0
#define ETHIF_SW_MAJOR_VERSION            0
#define ETHIF_SW_MINOR_VERSION            7
#define ETHIF_SW_PATCH_VERSION            0
#define ETHIF_VENDOR_ID                   (uint16)39
#define ETHIF_MODULE_ID                   (uint16)65

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/

/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/

/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/
#define ETHIF_START_SEC_CALLOUT_CODE
#include "EthIf_MemMap.h"
extern Std_ReturnType EthIf_ICV_Generation_Callout(
                      uint32 JobId, uint32 ICKKey,
                      const uint8 * dataPtr, uint32 dataLength,
                      uint8 * macPtr, uint32 * macLengthPtr);
#define ETHIF_STOP_SEC_CALLOUT_CODE
#include "EthIf_MemMap.h"

/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/

#endif /* ETHIF_EXTERNAL_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
