/*******************************************************************************
**  FILE-NAME: Tls_Cfg.c                                                    **
**                                                                            **
**  MODULE-NAME: Tls                                                          **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.4.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../170_Tls_TESTING/Code_Compliance/Config/Tls_Config_3/PC_Config/xml/Tls_Config_3.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/Csm/xml/Csm.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/KeyM/xml/KeyM.arxml
 *   ../../../170_Tls_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2026 Apr 22 15:04:47 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
        /*******************************************************************************
        **                      Parasoft violations Section                           **
        *******************************************************************************/
/** 
*
* #section Tls_Cfg_c_REF_1
* Violates MISRAC2012-RULE_20_1-a-4: Do not precede the #include directive with
* executable code
* Justification: Macros are defined by AUTOSAR standards and internal
* specifications.
*
* #section Tls_Cfg_c_REF_2
* Violates MISRAC2012-RULE_5_4-d-2: The '' macro has the same name (or the first
* 31 characters of the name) as the '' macro previously defined in the current
* file
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted
*
* #section Tls_Cfg_c_REF_3
* Violates MISRAC2012-RULE_5_4-c-2: The '' macro has the same name (or the first
* 31 characters of the name) as the '' macro previously defined in the current
* file
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted
*
* #section Tls_Cfg_c_REF_4
* Violates MISRAC2012-RULE_2_8-a-4:  A project should not contain unused variables with external linkage
* Justification: The global variable is declared with external linkage to allow access from other translation units
* Although it is not directly referenced within Tls_Cfg.c it is used in other static source files as 
  part of the TLS configuration. 
* This design is intentional and necessary for modularity and separation of configuration from implementation
*
* #section Tls_Cfg_c_REF_5
* Violates MISRAC2012-RULE_5_1-a-2: The '' macro has the same name (or the first
* 31 characters of the name) as the '' macro previously defined in the current
* file
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted
*
* #section Tls_Cfg_c_REF_6
* Violates MISRAC2012-RULE_1_1-b-2: More than 31 initial characters in an
* external identifier: 35
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted.
*
* #section Tls_Cfg_c_REF_7
* Violates MISRAC2012-RULE_1_1-a-2: More than 31 initial characters in an
* internal identifier: 34
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted.
*
* #section Tls_Cfg_c_REF_8
* Violates CERT_C-DCL06-a-3:  Use meaningful symbolic constants to represent literal values
* Justification: The message can be suppressed in case of generated file
*  Based on configuration size, array size is generated and hence exact value is being used instead of Macro.
*
        * #section Tls_Cfg_c_REF_9
        * Violates MISRAC2012-RULE_9_3-a-2:  Arrays shall not be partially initialized
        * Justification: This warning is generated for an array initialized with one value , 
* the rest elements are automatically initiallized with 0 for the global variable. No specific initiallization is mandatory.
*/


/* parasoft-begin-suppress MISRAC2012-RULE_20_1-a-4 "Reason: Tls_Cfg_c_REF_1" */
/* parasoft-begin-suppress MISRAC2012-RULE_5_4-d-2 "Reason: Tls_Cfg_c_REF_2" */
/* parasoft-begin-suppress MISRAC2012-RULE_5_4-c-2 "Reason: Tls_Cfg_c_REF_3" */
/* parasoft-begin-suppress MISRAC2012-RULE_5_1-a-2 "Reason: Tls_Cfg_c_REF_5" */
/* parasoft-begin-suppress MISRAC2012-RULE_1_1-b-2 "Reason: Tls_Cfg_c_REF_6" */
/* parasoft-begin-suppress MISRAC2012-RULE_1_1-a-2 "Reason: Tls_Cfg_c_REF_7" */

#include "KeyM.h"
	
	#include "Tls_Version.h"
	#include "Tls_InternalTypes.h"
	/* Include if any one of the PSK container has Dyanmic PSK configured*/
	#include "Tls_Generated_Callouts.h"
	#include "Csm.h"	
	#include "Tls_Internal.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (TLS_VERSION_AR_RELEASE_MAJOR_VERSION != TLS_AR_RELEASE_MAJOR_VERSION)
  #error "TLS Code : Mismatch in Specification Major Version"
#endif

#if (TLS_VERSION_AR_RELEASE_MINOR_VERSION != TLS_AR_RELEASE_MINOR_VERSION)
  #error "TLS Code : Mismatch in Specification Minor Version"
#endif

#if (TLS_VERSION_AR_RELEASE_REVISION_VERSION != TLS_AR_RELEASE_REVISION_VERSION)
  #error "TLS Code : Mismatch in Specification Revision Version"
#endif

#if (TLS_VERSION_SW_MAJOR_VERSION != TLS_SW_MAJOR_VERSION)
  #error "TLS Code : Mismatch in Software Major Version"
#endif

#if (TLS_VERSION_SW_MINOR_VERSION != TLS_SW_MINOR_VERSION)
  #error "TLS Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/
#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_ConfigType   Tls_GaaConfig[TLS_ONE] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of TlsConfig : TlsConfig_0 */
	{
	  
	  /* usTlsMaxConnections */
	  2U
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

/* Tls_GaaPSKLookUp , index value basically represents which PSK conatiners to be referred to */
#define TLS_START_SEC_CONST_8
#include "Tls_MemMap.h"
const uint8  Tls_GaaPSKLookUp[TLS_NUM_OF_REFFERED_PSK] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	1, 0, 4, 5, 12, 8, 9, 10, 11, 9
};
#define TLS_STOP_SEC_CONST_8
#include "Tls_MemMap.h"

/* Tls_GaaGroupArray , index value basically represents a connection , which represents which Group it is linked to */
#define TLS_START_SEC_CONST_16
#include "Tls_MemMap.h"
const uint16  Tls_GaaGroupArray[TLS_TOTAL_CONNECTIONS] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	0x0000, 0x0000, 0x0001, 0x0000, 0x0000, 0x0001
};
#define TLS_STOP_SEC_CONST_16
#include "Tls_MemMap.h"

/* Tls_GaaHSLookUp , index value basically represents which Handshake conatiners to be referred to */
#define TLS_START_SEC_CONST_16
#include "Tls_MemMap.h"
const uint16  Tls_GaaHSLookUp[TLS_NUM_OF_REFFERED_HANDSHAKE] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 2
};
#define TLS_STOP_SEC_CONST_16
#include "Tls_MemMap.h"

/* Tls_GaaCiphrWrkrLookUp , index value basically represents which TlsCipherSuiteWorker conatiners to be referred to */
#define TLS_START_SEC_CONST_16
#include "Tls_MemMap.h"
const uint16  Tls_GaaCiphrWrkrLookUp[TLS_NUM_OF_REFFERED_CIPHERSUITE_WORKER] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	3, 2, 0, 2, 0, 1, 3, 2, 0, 2, 0, 1
};
#define TLS_STOP_SEC_CONST_16
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const TlsConnectionStrType  Tls_GaaConnection[TLS_TOTAL_CONNECTIONS] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of TlsConnection : 0_TlsConnection_0 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_PSK,
	  
	  /* ddTlsConnectionType */
	  TLS_CLIENT,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_0,
	  
	  /* ulTlsCertIdnRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  3U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  0u,
	  
	  /* usTlsMaxFragmentLen */
	  1U,
	  
	  /* usHSWrkrIdx */
	  0u,
	  
	  /* usNumOfHSWorkers */
	  3u,
	  
	  /* usTlsWaitingTimeout */
	  2u,
	  
	  /* ddTlsConnectionId */
	  0U,
	  
	  /* ucPSKConnLookUpIdx */
	  0u,
	  
	  /* ucNumOfPreSharedKeys */
	  4U,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE,
	  
	  /* blTlsIsGrpEnbld */
	  TLS_TRUE
	},
	/* Details of TlsConnection : 1_TlsConnection_1 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_CERT,
	  
	  /* ddTlsConnectionType */
	  TLS_CLIENT,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_1,
	  
	  /* ulTlsCertIdnRefIdx */
	  0u,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  2U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  3u,
	  
	  /* usTlsMaxFragmentLen */
	  1U,
	  
	  /* usHSWrkrIdx */
	  3u,
	  
	  /* usNumOfHSWorkers */
	  2u,
	  
	  /* usTlsWaitingTimeout */
	  2u,
	  
	  /* ddTlsConnectionId */
	  1U,
	  
	  /* ucPSKConnLookUpIdx */
	  0xFFU,
	  
	  /* ucNumOfPreSharedKeys */
	  TLS_ZERO,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE,
	  
	  /* blTlsIsGrpEnbld */
	  TLS_TRUE
	},
	/* Details of TlsConnection : 2_TlsConnection_2 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_PSK,
	  
	  /* ddTlsConnectionType */
	  TLS_CLIENT,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_2,
	  
	  /* ulTlsCertIdnRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  1U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  5u,
	  
	  /* usTlsMaxFragmentLen */
	  1U,
	  
	  /* usHSWrkrIdx */
	  5u,
	  
	  /* usNumOfHSWorkers */
	  1u,
	  
	  /* usTlsWaitingTimeout */
	  3u,
	  
	  /* ddTlsConnectionId */
	  2U,
	  
	  /* ucPSKConnLookUpIdx */
	  4u,
	  
	  /* ucNumOfPreSharedKeys */
	  1U,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE,
	  
	  /* blTlsIsGrpEnbld */
	  TLS_TRUE
	},
	/* Details of TlsConnection : 3_TlsConnection_3 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_PSK,
	  
	  /* ddTlsConnectionType */
	  TLS_SERVER,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_3,
	  
	  /* ulTlsCertIdnRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  3U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  6u,
	  
	  /* usTlsMaxFragmentLen */
	  1U,
	  
	  /* usHSWrkrIdx */
	  6u,
	  
	  /* usNumOfHSWorkers */
	  3u,
	  
	  /* usTlsWaitingTimeout */
	  2u,
	  
	  /* ddTlsConnectionId */
	  3U,
	  
	  /* ucPSKConnLookUpIdx */
	  4u,
	  
	  /* ucNumOfPreSharedKeys */
	  4U,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE,
	  
	  /* blTlsIsGrpEnbld */
	  TLS_TRUE
	},
	/* Details of TlsConnection : 4_TlsConnection_4 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_CERT,
	  
	  /* ddTlsConnectionType */
	  TLS_SERVER,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_4,
	  
	  /* ulTlsCertIdnRefIdx */
	  1u,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  2U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  9u,
	  
	  /* usTlsMaxFragmentLen */
	  1U,
	  
	  /* usHSWrkrIdx */
	  9u,
	  
	  /* usNumOfHSWorkers */
	  2u,
	  
	  /* usTlsWaitingTimeout */
	  5u,
	  
	  /* ddTlsConnectionId */
	  4U,
	  
	  /* ucPSKConnLookUpIdx */
	  0xFFU,
	  
	  /* ucNumOfPreSharedKeys */
	  TLS_ZERO,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE,
	  
	  /* blTlsIsGrpEnbld */
	  TLS_TRUE
	},
	/* Details of TlsConnection : 5_TlsConnection_5 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_PSK,
	  
	  /* ddTlsConnectionType */
	  TLS_SERVER,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_5,
	  
	  /* ulTlsCertIdnRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  1U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  11u,
	  
	  /* usTlsMaxFragmentLen */
	  100U,
	  
	  /* usHSWrkrIdx */
	  11u,
	  
	  /* usNumOfHSWorkers */
	  1u,
	  
	  /* usTlsWaitingTimeout */
	  10u,
	  
	  /* ddTlsConnectionId */
	  5U,
	  
	  /* ucPSKConnLookUpIdx */
	  5u,
	  
	  /* ucNumOfPreSharedKeys */
	  1U,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE,
	  
	  /* blTlsIsGrpEnbld */
	  TLS_TRUE
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_PskIdentityType  Tls_GaaPskIdentity[TLS_NUM_OF_PSK_CONFIGURED] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of Tls_PskIdentity : 0_TlsPskIdentity_0 */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  CsmConf_CsmKey_PSK_0,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_0_PSK_0,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  20U,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0x4D, 0x79, 0x5F, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5F, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x64, 0x2D, 0x30}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_FALSE
	},
	/* Details of Tls_PskIdentity : 1_TlsPskIdentity_1 */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_1_PSK_1,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  &PSK_CBK1_TlsClientGetPskIdentity,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_TRUE
	},
	/* Details of Tls_PskIdentity : 2_TlsPskIdentity_10_server */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_10_PSK_10,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  &PSK_CBK4_TlsServerGetPskIdentity,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  &PSK_CBK4_TlsServerGetPskIdentityHint,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_TRUE
	},
	/* Details of Tls_PskIdentity : 3_TlsPskIdentity_11_server */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  CsmConf_CsmKey_PSK_11,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_11_PSK_11,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  20U,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0x4D, 0x79, 0x5F, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5F, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x64, 0x2D, 0x35}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_FALSE
	},
	/* Details of Tls_PskIdentity : 4_TlsPskIdentity_2 */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  CsmConf_CsmKey_PSK_2,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_2_PSK_2,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  20U,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0x4D, 0x79, 0x5F, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5F, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x64, 0x2D, 0x32}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_FALSE
	},
	/* Details of Tls_PskIdentity : 5_TlsPskIdentity_3 */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_3_PSK_3,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  &PSK_CBK3_TlsClientGetPskIdentity,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_TRUE
	},
	/* Details of Tls_PskIdentity : 6_TlsPskIdentity_4 */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_4_PSK_4,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  &PSK_CBK4_TlsClientGetPskIdentity,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_TRUE
	},
	/* Details of Tls_PskIdentity : 7_TlsPskIdentity_5 */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  CsmConf_CsmKey_PSK_5,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_5_PSK_5,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  20U,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0x4D, 0x79, 0x5F, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5F, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x64, 0x2D, 0x35}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_FALSE
	},
	/* Details of Tls_PskIdentity : 8_TlsPskIdentity_6_server */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  CsmConf_CsmKey_PSK_6,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_6_PSK_6,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  20U,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0x4D, 0x79, 0x5F, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5F, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x64, 0x2D, 0x30}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_FALSE
	},
	/* Details of Tls_PskIdentity : 9_TlsPskIdentity_7_server */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_7_PSK_7,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  &PSK_CBK1_TlsServerGetPskIdentity,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  &PSK_CBK1_TlsServerGetPskIdentityHint,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_TRUE
	},
	/* Details of Tls_PskIdentity : 10_TlsPskIdentity_8_server */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  CsmConf_CsmKey_PSK_8,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_8_PSK_8,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  20U,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0x4D, 0x79, 0x5F, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5F, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x64, 0x2D, 0x32}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_FALSE
	},
	/* Details of Tls_PskIdentity : 11_TlsPskIdentity_9_server */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_9_PSK_9,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  &PSK_CBK3_TlsServerGetPskIdentity,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  &PSK_CBK3_TlsServerGetPskIdentityHint,
	  
	  /* usTlsPskIdentityLen */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_TRUE
	},
	/* Details of Tls_PskIdentity : 12_TlsPskIdentity_6 */
	{
	  
	  /* ddTlsPSKHashType */
	  TLS_SHA_256,
	  
	  /* ulTlsPSKCsmKeyRefId */
	  CsmConf_CsmKey_PSK_6,
	  
	  /* ulTlsCsmBinderKeyRefId */
	  CsmConf_CsmKey_BinderKey_6_PSK_6,
	  
	  /* pTlsPskGetClientKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetServerKeyIdentityFunc */
	  NULL_PTR,
	  
	  /* pTlsPskGetKeyIdentityHintFunc */
	  NULL_PTR,
	  
	  /* usTlsPskIdentityLen */
	  21U,
	  
	  /* usTlsPskIdentityHintLen */
	  TLS_INVALID_SHORT,
	  
	  /* aaPskIdentity */
	  {0x4D, 0x79, 0x5F, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5F, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6F, 0x72, 0x64, 0x2D, 0x36, 0x36}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* aaPresharedKeyIdentityHint */
	  {0xFFU}, // parasoft-suppress MISRAC2012-RULE_9_3-a-2 "Reason: Tls_Cfg_c_REF_9",
	  
	  /* blIsDynPskAvail */
	  TLS_FALSE
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_CiphersuiteDefinition  Tls_GaaCiphersuiteDef[TLS_NUM_OF_CIPHERSUITE_DEFINITION] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of Tls_CiphersuiteDefinition : 0_TlsCiphersuiteDefinition_0 */
	{
	  
	  /* ddTlsVersion */
	  TLS_VERSION_V13,
	  
	  /* usTlsCiphersuiteId */
	  4865U,
	  
	  /* usTlsCiphersuitePriority */
	  1U,
	  
	  /* ucTlsCiphersuiteNameLen */
	  22U,
	  
	  /* blTlsUseAEADCipher */
	  TLS_FALSE,
	  
	  /* blTlsUsePresharedKeys */
	  TLS_FALSE,
	  
	  /* blTlsUseSecurityExtensionForceEncryptThenMac */
	  TLS_FALSE
	},
	/* Details of Tls_CiphersuiteDefinition : 1_TlsCiphersuiteDefinition_1 */
	{
	  
	  /* ddTlsVersion */
	  TLS_VERSION_V13,
	  
	  /* usTlsCiphersuiteId */
	  4866U,
	  
	  /* usTlsCiphersuitePriority */
	  2U,
	  
	  /* ucTlsCiphersuiteNameLen */
	  22U,
	  
	  /* blTlsUseAEADCipher */
	  TLS_FALSE,
	  
	  /* blTlsUsePresharedKeys */
	  TLS_FALSE,
	  
	  /* blTlsUseSecurityExtensionForceEncryptThenMac */
	  TLS_FALSE
	},
	/* Details of Tls_CiphersuiteDefinition : 2_TlsCiphersuiteDefinition_2 */
	{
	  
	  /* ddTlsVersion */
	  TLS_VERSION_V13,
	  
	  /* usTlsCiphersuiteId */
	  4867U,
	  
	  /* usTlsCiphersuitePriority */
	  3U,
	  
	  /* ucTlsCiphersuiteNameLen */
	  TLS_INVALID_STRING_LEN,
	  
	  /* blTlsUseAEADCipher */
	  TLS_FALSE,
	  
	  /* blTlsUsePresharedKeys */
	  TLS_FALSE,
	  
	  /* blTlsUseSecurityExtensionForceEncryptThenMac */
	  TLS_FALSE
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_CiphersuiteWorkerType  Tls_GaaCiphrSuiteWrkr[TLS_NUM_OF_CIPHERSUITE_WORKER] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of Tls_CiphersuiteWorker : 0_TlsCiphersuiteWorker_2 */
	{
	  
	  /* ulTlsCipherCsmDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationTrafficSecretKey_2,
	  
	  /* ulTlsCsmServerApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationTrafficSecretKey_2,
	  
	  /* ulTlsCsmClientApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteKey_2,
	  
	  /* ulTlsCsmServerApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_2,
	  
	  /* ulTlsCsmClientApplWriteIVRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteIV_2,
	  
	  /* ulTlsCsmServerApplWriteIVRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteIV_2,
	  
	  /* ulTlsCipherCsmEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmMacGenerateJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacGenerateJob_2,
	  
	  /* ulTlsCipherCsmMacGenerateKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacGenerateKey_2,
	  
	  /* ulTlsCipherCsmMacVerifyJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacVerifyJob_2,
	  
	  /* ulTlsCipherCsmMacVerifyKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacVerifyKey_2,
	  
	  /* ulTlsCiphrSutDefRefIdx */
	  0U,
	  
	  /* usTlsCipherAEADCipherKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherEncryptKeyLength */
	  82U,
	  
	  /* usTlsCipherMacKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsConnHandshakeRefBaseIndx */
	  0
	},
	/* Details of Tls_CiphersuiteWorker : 1_TlsCiphersuiteWorker_3 */
	{
	  
	  /* ulTlsCipherCsmDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationTrafficSecretKey_3,
	  
	  /* ulTlsCsmServerApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationTrafficSecretKey_3,
	  
	  /* ulTlsCsmClientApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteKey_3,
	  
	  /* ulTlsCsmServerApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_3,
	  
	  /* ulTlsCsmClientApplWriteIVRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteIV_3,
	  
	  /* ulTlsCsmServerApplWriteIVRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteIV_3,
	  
	  /* ulTlsCipherCsmEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmMacGenerateJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacGenerateJob_3,
	  
	  /* ulTlsCipherCsmMacGenerateKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacGenerateKey_3,
	  
	  /* ulTlsCipherCsmMacVerifyJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacVerifyJob_3,
	  
	  /* ulTlsCipherCsmMacVerifyKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacVerifyKey_3,
	  
	  /* ulTlsCiphrSutDefRefIdx */
	  0U,
	  
	  /* usTlsCipherAEADCipherKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherEncryptKeyLength */
	  82U,
	  
	  /* usTlsCipherMacKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsConnHandshakeRefBaseIndx */
	  2
	},
	/* Details of Tls_CiphersuiteWorker : 2_TlsCiphersuiteWorker_1 */
	{
	  
	  /* ulTlsCipherCsmDecryptJobRefIdx */
	  CsmConf_CsmJob_CipherCsmDecryptJob_1,
	  
	  /* ulTlsCipherCsmDecryptKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmDecryptKey_1,
	  
	  /* ulTlsCsmClientApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationTrafficSecretKey_1,
	  
	  /* ulTlsCsmServerApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationTrafficSecretKey_1,
	  
	  /* ulTlsCsmClientApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteKey_1,
	  
	  /* ulTlsCsmServerApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_1,
	  
	  /* ulTlsCsmClientApplWriteIVRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteIV_1,
	  
	  /* ulTlsCsmServerApplWriteIVRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteIV_1,
	  
	  /* ulTlsCipherCsmEncryptJobRefIdx */
	  CsmConf_CsmJob_CipherCsmEncryptJob_1,
	  
	  /* ulTlsCipherCsmEncryptKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmEncryptKey_1,
	  
	  /* ulTlsCipherCsmMacGenerateJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacGenerateJob_1,
	  
	  /* ulTlsCipherCsmMacGenerateKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacGenerateKey_1,
	  
	  /* ulTlsCipherCsmMacVerifyJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacVerifyJob_1,
	  
	  /* ulTlsCipherCsmMacVerifyKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacVerifyKey_1,
	  
	  /* ulTlsCiphrSutDefRefIdx */
	  1U,
	  
	  /* usTlsCipherAEADCipherKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherEncryptKeyLength */
	  82U,
	  
	  /* usTlsCipherMacKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsConnHandshakeRefBaseIndx */
	  1
	},
	/* Details of Tls_CiphersuiteWorker : 3_TlsCiphersuiteWorker_0 */
	{
	  
	  /* ulTlsCipherCsmDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationTrafficSecretKey_0,
	  
	  /* ulTlsCsmServerApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationTrafficSecretKey_0,
	  
	  /* ulTlsCsmClientApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteKey_0,
	  
	  /* ulTlsCsmServerApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_0,
	  
	  /* ulTlsCsmClientApplWriteIVRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteIV_0,
	  
	  /* ulTlsCsmServerApplWriteIVRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteIV_0,
	  
	  /* ulTlsCipherCsmEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCipherCsmMacGenerateJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacGenerateJob_0,
	  
	  /* ulTlsCipherCsmMacGenerateKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacGenerateKey_0,
	  
	  /* ulTlsCipherCsmMacVerifyJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacVerifyJob_0,
	  
	  /* ulTlsCipherCsmMacVerifyKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacVerifyKey_0,
	  
	  /* ulTlsCiphrSutDefRefIdx */
	  2U,
	  
	  /* usTlsCipherAEADCipherKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherEncryptKeyLength */
	  82U,
	  
	  /* usTlsCipherMacKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsConnHandshakeRefBaseIndx */
	  0
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_HandshakeType Tls_GaaHandshake[TLS_NUM_OF_HANDSHAKE] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of Tls_Handshake : 0_TlsHandshake_0 */
	{
	  
	  /* ulTlsCsmHashVerifyJobRefIdx */
	  CsmConf_CsmJob_HashVerifyJob_0,
	  
	  /* ulTlsCsmKeyExchangeCalcPubValJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcPubValJobRef_0,
	  
	  /* ulTlsCsmKeyExchangeCalcSecretJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcSecretJobRef_0,
	  
	  /* ulTlsCsmKeyExchangeDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeTrafficSecretKey_0,
	  
	  /* ulTlsCsmClientHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWriteIV_0,
	  
	  /* ulTlsCsmClientHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWritekey_0,
	  
	  /* ulTlsCsmServerHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeTrafficSecretKey_0,
	  
	  /* ulTlsCsmServerHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteIV_0,
	  
	  /* ulTlsCsmServerHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWritekey_0,
	  
	  /* ulTlsCsmDerivedKeyRefIdx */
	  CsmConf_CsmKey_DerivedKey_0,
	  
	  /* ulTlsCsmEarlySecretKeyRefIdx */
	  CsmConf_CsmKey_EarlySecretKey_0,
	  
	  /* ulTlsCsmHKDFExpandJobRefIdx */
	  CsmConf_CsmJob_HKDFExpandJob_0,
	  
	  /* ulTlsCsmHKDFExpandKeyRefIdx */
	  CsmConf_CsmKey_HKDFExpandKey_0,
	  
	  /* ulTlsCsmHKDFExtractJobRefIdx */
	  CsmConf_CsmJob_HKDFExtractJob_0,
	  
	  /* ulTlsCsmHKDFExtractKeyRefIdx */
	  CsmConf_CsmKey_HKDFExtractKey_0,
	  
	  /* ulTlsCsmHandshakeSecretKeyRefIdx */
	  CsmConf_CsmKey_HandshakeSecretKey_0,
	  
	  /* ulTlsCsmKeyExchangeEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeKeyRefIdx */
	  CsmConf_CsmKey_TlsCsmKeyExchangeKeyRef_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateJobRefIdx */
	  CsmConf_CsmJob_SigGenJob_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateKeyRefIdx */
	  CsmConf_CsmKey_SigGenKey_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyJobRefIdx */
	  CsmConf_CsmJob_SigVerifyJob_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyKeyRefIdx */
	  CsmConf_CsmKey_SigVerifyKey_0,
	  
	  /* ulTlsCsmMasterSecretKeyRefIdx */
	  CsmConf_CsmKey_MasterKey_0,
	  
	  /* ulTlsCsmPrfMacJobRefIdx */
	  CsmConf_CsmJob_PrfMacJob_0,
	  
	  /* ulTlsCsmPrfMacKeyRefIdx */
	  CsmConf_CsmKey_PrfMacKey_0,
	  
	  /* ddTlsCsmPRFSupportType */
	  TLS_PRF_NO_SUPPORT,
	  
	  /* usTlsSupportedGrpId */
	  (uint16)TLS_SECP256R1,
	  
	  /* usTlsSignatureId */
	  (uint16)TLS_RSA_PKCS1_SHA256,
	  
	  /* usTlsGroupPriority */
	  TLS_INVALID_SHORT
	},
	/* Details of Tls_Handshake : 1_TlsHandshake_1 */
	{
	  
	  /* ulTlsCsmHashVerifyJobRefIdx */
	  CsmConf_CsmJob_HashVerifyJob_1,
	  
	  /* ulTlsCsmKeyExchangeCalcPubValJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcPubValJobRef_1,
	  
	  /* ulTlsCsmKeyExchangeCalcSecretJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcSecretJobRef_1,
	  
	  /* ulTlsCsmKeyExchangeDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeTrafficSecretKey_1,
	  
	  /* ulTlsCsmClientHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWriteIV_1,
	  
	  /* ulTlsCsmClientHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWritekey_1,
	  
	  /* ulTlsCsmServerHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeTrafficSecretKey_1,
	  
	  /* ulTlsCsmServerHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWriteIV_1,
	  
	  /* ulTlsCsmServerHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_1,
	  
	  /* ulTlsCsmDerivedKeyRefIdx */
	  CsmConf_CsmKey_DerivedKey_1,
	  
	  /* ulTlsCsmEarlySecretKeyRefIdx */
	  CsmConf_CsmKey_EarlySecretKey_1,
	  
	  /* ulTlsCsmHKDFExpandJobRefIdx */
	  CsmConf_CsmJob_HKDFExpandJob_1,
	  
	  /* ulTlsCsmHKDFExpandKeyRefIdx */
	  CsmConf_CsmKey_HKDFExpandKey_1,
	  
	  /* ulTlsCsmHKDFExtractJobRefIdx */
	  CsmConf_CsmJob_HKDFExtractJob_1,
	  
	  /* ulTlsCsmHKDFExtractKeyRefIdx */
	  CsmConf_CsmKey_HKDFExtractKey_1,
	  
	  /* ulTlsCsmHandshakeSecretKeyRefIdx */
	  CsmConf_CsmKey_HandshakeSecretKey_1,
	  
	  /* ulTlsCsmKeyExchangeEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeKeyRefIdx */
	  CsmConf_CsmKey_TlsCsmKeyExchangeKeyRef_1,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateJobRefIdx */
	  CsmConf_CsmJob_SigGenJob_1,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateKeyRefIdx */
	  CsmConf_CsmKey_SigGenKey_1,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyJobRefIdx */
	  CsmConf_CsmJob_SigVerifyJob_1,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyKeyRefIdx */
	  CsmConf_CsmKey_SigVerifyKey_1,
	  
	  /* ulTlsCsmMasterSecretKeyRefIdx */
	  CsmConf_CsmKey_MasterKey_1,
	  
	  /* ulTlsCsmPrfMacJobRefIdx */
	  CsmConf_CsmJob_PrfMacJob_1,
	  
	  /* ulTlsCsmPrfMacKeyRefIdx */
	  CsmConf_CsmKey_PrfMacKey_1,
	  
	  /* ddTlsCsmPRFSupportType */
	  TLS_PRF_INVALID,
	  
	  /* usTlsSupportedGrpId */
	  (uint16)TLS_X25519,
	  
	  /* usTlsSignatureId */
	  (uint16)TLS_RSA_PSS_PSS_SHA256,
	  
	  /* usTlsGroupPriority */
	  TLS_INVALID_SHORT
	},
	/* Details of Tls_Handshake : 2_TlsHandshake_2 */
	{
	  
	  /* ulTlsCsmHashVerifyJobRefIdx */
	  CsmConf_CsmJob_HashVerifyJob_2,
	  
	  /* ulTlsCsmKeyExchangeCalcPubValJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeCalcSecretJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeTrafficSecretKey_2,
	  
	  /* ulTlsCsmClientHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWriteIV_2,
	  
	  /* ulTlsCsmClientHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWritekey_2,
	  
	  /* ulTlsCsmServerHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeTrafficSecretKey_2,
	  
	  /* ulTlsCsmServerHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWriteIV_2,
	  
	  /* ulTlsCsmServerHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWritekey_2,
	  
	  /* ulTlsCsmDerivedKeyRefIdx */
	  CsmConf_CsmKey_DerivedKey_2,
	  
	  /* ulTlsCsmEarlySecretKeyRefIdx */
	  CsmConf_CsmKey_EarlySecretKey_2,
	  
	  /* ulTlsCsmHKDFExpandJobRefIdx */
	  CsmConf_CsmJob_HKDFExpandJob_2,
	  
	  /* ulTlsCsmHKDFExpandKeyRefIdx */
	  CsmConf_CsmKey_HKDFExtractKey_2,
	  
	  /* ulTlsCsmHKDFExtractJobRefIdx */
	  CsmConf_CsmJob_HKDFExtractJob_2,
	  
	  /* ulTlsCsmHKDFExtractKeyRefIdx */
	  CsmConf_CsmKey_HKDFExtractKey_2,
	  
	  /* ulTlsCsmHandshakeSecretKeyRefIdx */
	  CsmConf_CsmKey_HandshakeSecretKey_2,
	  
	  /* ulTlsCsmKeyExchangeEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmMasterSecretKeyRefIdx */
	  CsmConf_CsmKey_MasterKey_2,
	  
	  /* ulTlsCsmPrfMacJobRefIdx */
	  CsmConf_CsmJob_PrfMacJob_2,
	  
	  /* ulTlsCsmPrfMacKeyRefIdx */
	  CsmConf_CsmKey_PrfMacKey_2,
	  
	  /* ddTlsCsmPRFSupportType */
	  TLS_PRF_INVALID,
	  
	  /* usTlsSupportedGrpId */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsSignatureId */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsGroupPriority */
	  TLS_INVALID_SHORT
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_0        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_0(void)
{
  Tls_MainFunction(0); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_1        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_1(void)
{
  Tls_MainFunction(1); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_2        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_2(void)
{
  Tls_MainFunction(2); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_3        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_3(void)
{
  Tls_MainFunction(3); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_4        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_4(void)
{
  Tls_MainFunction(4); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_5        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_5(void)
{
  Tls_MainFunction(5); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"



#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_CertificateIdentityType  Tls_GaaCertificateIdentity[TLS_NUM_OF_CERTIFICATE_IDENTITYS] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of TlsCertificateIdentity Container : 0_TlsCertificateIdentity_0 */
	{
	  
	  /* ddTlsCipherKeyMLocalCertificateIdx  */
	  TLS_INVALID_SHORT,
	  
	  /* ddTlsCipherKeyMRemoteCertificateIdx  */
	  KeyMConf_KeyMCertificate_KeyMCertificate_Server_0,
	  
	  /* ddTlsCipherKeyMRemoteCertElementIdx  */
	  KeyMConf_KeyMCertificateElement_KeyMCertificateElement_0,
	  
	  /* ddTlsCipherKeyMRemoteCertElementPublicKeyIdx  */
	  KeyMConf_KeyMCertificateElement_KeyMCertificateElement_1
	},
	/* Details of TlsCertificateIdentity Container : 1_TlsCertificateIdentity_1 */
	{
	  
	  /* ddTlsCipherKeyMLocalCertificateIdx  */
	  KeyMConf_KeyMCertificate_KeyMCertificate_Server_0,
	  
	  /* ddTlsCipherKeyMRemoteCertificateIdx  */
	  TLS_INVALID_SHORT,
	  
	  /* ddTlsCipherKeyMRemoteCertElementIdx  */
	  TLS_INVALID_SHORT,
	  
	  /* ddTlsCipherKeyMRemoteCertElementPublicKeyIdx  */
	  TLS_INVALID_SHORT
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

        /****************************************************************************
        **                   Parasoft violations end Section                       **
        ****************************************************************************/
        /* parasoft-end-suppress MISRAC2012-RULE_20_1-a-4 */
        /* parasoft-end-suppress MISRAC2012-RULE_5_4-d-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_5_4-c-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_5_1-a-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_1_1-b-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_1_1-a-2 */

/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
