/*******************************************************************************
**  FILE-NAME: EthIf_Cfg.h                                                  **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_2/PC_Config/xml/EthIf_Config_2.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:41:46 IST
 */
#ifndef ETHIF_CFG_H
#define ETHIF_CFG_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "ComStack_Types.h"
#include "EthTrcv.h"


/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define ETHIF_AR_RELEASE_MAJOR_VERSION    4
#define ETHIF_AR_RELEASE_MINOR_VERSION    10
#define ETHIF_AR_RELEASE_REVISION_VERSION 0
#define ETHIF_SW_MAJOR_VERSION            0
#define ETHIF_SW_MINOR_VERSION            7
#define ETHIF_SW_PATCH_VERSION            0
#define ETHIF_VENDOR_ID                   (uint16)39
#define ETHIF_MODULE_ID                   (uint16)65

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/
/* Design_ID :  ETHIF_SDD_0401 */
/* Safetyksar inclusion required */
#define ETHIF_SAFE_KSAR                         STD_OFF
 /* Design ID : ETHIF_SDD_0592 */
 /*  Pre-compile option for variant-support */
 #define ETHIF_PRE_COMPILE_SINGLE                STD_ON
 /* Design ID : ETHIF_SDD_0595*/
 /* Precompile option to check if Version Info API is Enabled */
 #define ETHIF_VERSIONINFO_API                   STD_ON
 /* Design ID : ETHIF_SDD_0709*/
 /* Precompile option to check if WETH API is Enabled */
 #define ETHIF_ENABLE_WETH_API                   STD_OFF
 /* Design ID : ETHIF_SDD_0588*/
 /* Precompile option to check if Development Error is Enabled */
 #define ETHIF_DEV_ERROR_DETECT                  STD_OFF
 /* Design ID : ETHIF_SDD_0331*/
 /* Precompile option to check if Rx Polling is Enabled */
 #define ETHIF_ENABLE_RX_INTERRUPT               STD_OFF
 /* Design ID : ETHIF_SDD_0332*/
 /* Precompile option to check if Tx Polling is Enabled */
 #define ETHIF_ENABLE_TX_INTERRUPT               STD_OFF
 /* Design ID : ETHIF_SDD_0590*/
 /* Precompile option to check if Get Baud Rate API is Enabled */
 #define ETHIF_GET_BAUDRATE                      STD_ON
 /* Design ID : ETHIF_SDD_0357*/
 /* Precompile option to check if Get Counter State API is Enabled */
 #define ETHIF_GET_COUNTER_STATE                 STD_ON
 /* Design ID : ETHIF_SDD_0350*/
 /* Precompile option to check if Global Time Support API is Enabled */
 #define ETHIF_GLOBALTIME_SUPPORT                STD_ON
 /* Design ID : ETHIF_SDD_0351*/
 /* Precompile option to check if Start Auto Negotiation API is Enabled */
 #define ETHIF_START_AUTO_NEGOTIATION            STD_ON
 /* Design ID : ETHIF_SDD_0322*/
 /* Precompile option to check if WakeUp Support is Enabled */
 #define ETHIF_WAKEUP_SUPPORT                    STD_OFF
 /* Design ID : ETHIF_SDD_0320*/
 /* Value of EthIfTrcvLinkStateChgMainReload */
 #define ETHIF_TRCVLINKSTATECHGMAINRELOAD        2
 /* Design ID : ETHIF_SDD_0335*/
 /* Maximum number of iterations done in Mainfunction Rx */
 #define ETHIF_RXINDICATION_ITERATIONS           5
 /* Design ID : ETHIF_SDD_0569*/
 /* Maximum transmission unit (MTU) of the EthIfCtrl in [bytes] */
 #define ETHIF_MAXIMUM_TRANSMIT_UNIT             1500
 /* Design ID : ETHIF_SDD_0572 */
 /* Total number of controllers*/
 #define ETHIF_NUM_OF_CONTROLLERS                8U

 /* Design ID : ETHIF_SDD_0573 */
 /*Total number of physical controllers */
 #define ETHIF_NUM_OF_PHYSICAL_CONTROLLERS      2U

 #define ETHIF_NUM_OF_CLKUNIT                   2U

 #define ETHIF_CLKUNIT_INDEX                    2U

 /* Total number of ClkUnits */
 #define ETHIF_ETH_CLKUNIT_COUNT                3U

 /* Design ID : ETHIF_SDD_0575*/
 /* Total number of Transceivers*/
 #define ETHIF_NUM_OF_TRANSCEIVERS               1U

 /* Design ID : ETHIF_SDD_0574*/
 /* Total number of switches */
 #define ETHIF_NUM_OF_SWITCHES                   1U
 /* Design ID : ETHIF_SDD_0584*/
 /* Number of containers configured of EthIfTxConfirmationConfig */
 #define ETHIF_UL_TXCONFIRMATION_NUM             1U
 /* Design ID : ETHIF_SDD_0582 */
 /* Number of containers configured of EthIfTrcvLinkStateChgConfig */
 #define ETHIF_UL_LINKSTATECHANGE_NUM            1U
 /* Design ID : ETHIF_SDD_0582 */
 /* Number of containers configured of EthIfTrcvLinkStateChgConfig */
 #define ETHIF_MKA_LINKSTATECHANGE_NUM            0U
 /* Design ID : ETHIF_SDD_0583 */
 /* Number of containers configured of EthIfRxIndicationConfig */
 #define ETHIF_UL_RXINDICATION_NUM               2U
 /* Design ID : ETHIF_SDD_0571*/
 /* Number of containers configured of EthIfFrameOwnerConfig */
 #define ETHIF_NUM_FRAME_OWNER                   2U
 /* Design ID : ETHIF_SDD_0319 */
 /* Total number of Transceiver drivers */
 #define ETHIF_TRCV_DRIVER_COUNT                 1U
 /* Design ID : ETHIF_SDD_0568 */
 /* Total number of Controller drivers */
 #define ETHIF_ETH_DRIVER_COUNT                  1U
 /* Design ID : ETHIF_SDD_0579 */
 /* Total number of Switch drivers */
 #define ETHIF_SWT_DRIVER_COUNT                  1U
 /* Design ID : ETHIF_SDD_0355*/
 /* period of main function EthIf_MainFunctionRx and EthIf_MainFunctionTx
    in seconds */
 #define ETHIF_MAIN_FUNC_PERIOD                  0.005


/* Precompile option for EthIf_GetPortMacAddr API */
#define ETHIF_GET_PORT_MAC_ADDR_API              STD_OFF

/* Precompile option for EthIf_GetArlTable API */
#define ETHIF_GET_ARL_TABLE                     STD_OFF

/* Precompile option for EthIf_StoreConfiguration API */
#define ETHIF_STORE_CONFIGURATION_API          STD_OFF


  /* Precompile option for EthIf_ResetConfiguration API */
 #define ETHIF_RESET_CONFIGURATION_API           STD_OFF

 /* Design ID : ETHIF_SDD_0586*/
 /* Macro to check whether VLAN is supported */
 #define ETHIF_VLAN_SUPPORT                      STD_ON
/* Design ID : ETHIF_SDD_0567*/
 /* Macro to check whether CDD is supported */
 #define ETHIF_CDD_SUPPORT                       STD_ON

 /* Design ID : ETHIF_SDD_0018 */
 /* Precompile option to check if SecurityEventReporting is Enabled */
 #define ETHIF_SECURITY_EVENT_ENABLED            STD_ON

 /* Design ID : ETHIF_SDD_0019 */
 /* Precompile option to check if GetAndResetMeasurementData API is Enabled */
 #define ETHIF_MEASUREMENT_DATA_API            STD_ON

 /* Design ID : ETHIF_SDD_0021 */
 /* Precompile option to check if GetCtrlIdxList API is Enabled */
 #define ETHIF_GET_CTRLIDXLIST_API            STD_ON

 /* Design ID : ETHIF_SDD_0022 */
 /* Precompile option to check if GetVlanId API is Enabled */
 #define ETHIF_GET_VLANID_SUPPORT            STD_ON

 /* Macros for Security Event Refs*/
 /* Design ID will be updated once EA tool is active */
 #define ETHIF_SEV_ETH_DROP_INV_VLAN          IdsMConf_IdsMEvent_IdsMEvent_15

 #define ETHIF_SEV_ETH_DROP_MAC_COLLISION     IdsMConf_IdsMEvent_IdsMEvent_16

 #define ETHIF_SEV_ETH_DROP_UNKNOWN_ETHERTYPE IdsMConf_IdsMEvent_IdsMEvent_17


 #define ETHIF_NO_OF_TXPOOLS                 2
 #define ETHIF_NO_OF_RXPOOLS                 0
 #define ETHIF_RXPOOLIDX_MAP_SIZE            1
 #define ETHIF_NO_OF_TXPDUS                  3
 #define ETHIF_NO_OF_RXPDUS                  0
 #define ETHIF_RELEASERXBUFF_SUPPORT         STD_OFF
 #define ETHIF_METADATA_SUPPORT              STD_ON

 /* Design ID : ETHIF_SDD_0xxx */
 /* Total number of PAE INSTANCES */
 #define ETHIF_NUM_OF_PAE_INSTANCES             0U

 /* Design ID : ETHIF_SDD_0xxx */
 /* Precompile option to check if Macsec is Enabled */
 #define ETHIF_MACSEC_SUPPORT_ENABLED             STD_OFF

 #define ETHIF_SW_MACSEC_CTRL_COUNT               0x0u

 #define ETHIF_NO_OF_TXMETADATAITEMS           1u
 #define ETHIF_NO_OF_RXMETADATAITEMS           0u

/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/
/* Handle IDs for EthIfCtrlIdx */
#define EthIfConf_EthIfController_EthIfController_0                          (uint8)0
#define EthIfConf_EthIfController_EthIfController_1                          (uint8)1
#define EthIfConf_EthIfController_EthIfController_2                          (uint8)2
#define EthIfConf_EthIfController_EthIfController_3                          (uint8)3
#define EthIfConf_EthIfController_EthIfController_4                          (uint8)4
#define EthIfConf_EthIfController_EthIfController_5                          (uint8)5
#define EthIfConf_EthIfController_EthIfController_6                          (uint8)6
#define EthIfConf_EthIfController_EthIfController_7                          (uint8)7

/* Handle IDs for EthIfPhysControllerIdx */
#define EthIfConf_EthIfPhysController_EthIfPhysController_0                      (uint8)0
#define EthIfConf_EthIfPhysController_EthIfPhysController_1                      (uint8)1

/* Handle IDs for EthIfSwitchIdx */
#define EthIfConf_EthIfSwitch_EthIfSwitch_0                              (uint8)0

/* Handle IDs for EthIfTransceiverIdx */
#define EthIfConf_EthIfTransceiver_EthIfTransceiver_0                         (uint8)0

/* Handle IDs for EthIfClkUnitIdx  */
#define EthIfConf_EthIfPhysController_0_EthIfClkUnit_EthIfClkUnit_0   (uint8)0
#define EthIfConf_EthIfPhysController_1_EthIfClkUnit_EthIfClkUnit_0   (uint8)0


/* Handle IDs for TxPdus */
#define EthIfConf_EthIfFrameTxPdu_EthIfFrameTxPdu_0                          (PduIdType)0
#define EthIfConf_EthIfFrameTxPdu_EthIfFrameTxPdu_1                          (PduIdType)1
#define EthIfConf_EthIfFrameTxPdu_EthIfFrameTxPdu_2                          (PduIdType)2


/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/
/* Design ID : ETHIF_SDD_0524 */
typedef void (*EthIf_RxIndFuncPtr)
(uint8 CtrlIdx, Eth_FrameType FrameType,
boolean IsBroadcast,
const uint8*  PhysAddrPtr,
const uint8*  DataPtr,
uint16 LenByte);

/* Design ID : ETHIF_SDD_0531 */
typedef void (*EthIf_TxConFuncPtr)
(uint8 CtrlIdx, Eth_BufIdxType BufIdx,
  Std_ReturnType Result);

/* Design ID : ETHIF_SDD_0523 */
typedef void (*EthIf_LinkStateChangeFuncPtr)
(uint8 CtrlIdx,
EthTrcv_LinkStateType LinkState);

/* Design ID : ETHIF_SDD_0523 */
typedef void (*EthIf_MkaLinkStateChangeFuncPtr)
(uint8 PaeIdx,
EthTrcv_LinkStateType LinkState);

typedef Std_ReturnType (*EthIf_EthTrcvSetTransceiverModeFuncPtr)
(uint8 TrcvIdx, Eth_ModeType TrcvMode);


typedef Std_ReturnType (*EthIf_EthTrcvGetTransceiverModeFuncPtr)
(uint8 TrcvIdx, Eth_ModeType*  TrcvModePtr);


typedef Std_ReturnType (*EthIf_EthTrcvGetLinkStateFuncPtr)
(uint8 TrcvIdx, EthTrcv_LinkStateType* LinkStatePtr);


typedef Std_ReturnType (*EthIf_EthTrcvTransceiverLinkStateRequestFuncPtr)
(uint8 TrcvIdx, EthTrcv_LinkStateType LinkState);


/* Design ID : ETHIF_SDD_0530 */
/* Structure for Transciever: */
typedef struct STag_EthIf_TrcvApis
{

  /* EthTrcvSetTransceiverMode */
  const EthIf_EthTrcvSetTransceiverModeFuncPtr  pEthTrcvSetTransceiverMode;

  /* EthTrcvGetTransceiverMode */
  const EthIf_EthTrcvGetTransceiverModeFuncPtr  pEthTrcvGetTransceiverMode;

  /* EthTrcvGetLinkState */
  const EthIf_EthTrcvGetLinkStateFuncPtr  pEthTrcvGetLinkState;


  /* EthTrcvTransceiverLinkStateRequest */
   const EthIf_EthTrcvTransceiverLinkStateRequestFuncPtr  pEthTrcvTransceiverLinkStateRequest;


}EthIf_TrcvApis;

 /* Design ID : ETHIF_SDD_0521 */




/* Structure for ConfigType: */
/* Design ID : ETHIF_SDD_0520  */
typedef struct STagEthIf_ConfigType
{
  uint8 ucDummy;

}EthIf_ConfigType;

/* Structure for the EthIfClkUnit */
typedef struct STag_EthIf_StaticClkUnit
{
  /*EthIf controller clk index*/
  const uint8* pclkindx;

  /* Controller's clk unit*/
  uint8 ucclksize;
}EthIf_StaticClkUnit;

/* Design ID : ETHIF_SDD_0526  */
/* Structure for the EthIfPhysController */
typedef struct STag_EthIf_StaticPhyController
{
  /*EthIf PhysController index*/
  uint8 ucPhysCtrlIdx;

  /* Index of ClkUnit w.r.t EthIf */
  const EthIf_StaticClkUnit*  pEthClk;

}EthIf_StaticPhyController;

/* Design ID : ETHIF_SDD_0620  */
typedef struct STag_EthIf_StaticPhyController_PB
{

  /* ucEthCtrlIdx - IDx of actual ethernet driver */
  uint8 ucCtrlIdx;


  /* WEthCtrlIdx - IDx of actual ethernet driver */
  uint8 ucWEthCtrlIdx;

  /* blCtrlHWDataTransfer - hardware supported data transfer */
  boolean blCtrlHWDataTransfer;

}EthIf_StaticPhyController_PB;


/* Design ID : ETHIF_SDD_0528  */
/* Structure for the EthIfTransceiver*/
typedef struct STag_EthIf_StaticTransceiver
{
  /* EthIf Transceiver index */
  uint8 ucEthIfTrcvIdx;
}EthIf_StaticTransceiver;


/* Design ID : ETHIF_SDD_0053  */
typedef struct STag_EthIf_StaticTransceiver_PB
{
  /* pTrcvDriver */
  const EthIf_TrcvApis*  pTrcvDriver;
  /* Transceiver index to be fetched from reference*/
  uint8 ucTrcvIdx;
  /*Wireless Transceiver index to be fetched from reference*/
  uint8 ucWEthTrcvIdx;
  /* ucTrcvDriver */
  uint8 ucTrcvDriver;
}EthIf_StaticTransceiver_PB;

/* Design ID : ETHIF_SDD_0xxx */
typedef enum ETag_EthIf_MacsecType
{
  ETHIF_HW_MACSEC = 0x01U,
  ETHIF_NO_MACSEC,
  ETHIF_SW_MACSEC
}EthIf_MacsecType;

/* Design ID : ETHIF_SDD_0xxx */
typedef struct STag_EthIf_StaticPaeInstance
{
  /* PaeIdx */
  uint8 ucPaeIdx;
}EthIf_StaticPaeInstance;

/* Design ID : ETHIF_SDD_0525 */
typedef struct STag_EthIf_StaticController
{
  /* ucEthIfMaxTxBufsTotal */
  uint32 ucEthIfMaxTxBufsTotal;

  /*ucEthIfCtrlIdx*/
  uint8 ucEthIfCtrlIdx;

}EthIf_StaticController;

typedef struct STag_EthIf_ICVHandlerType
{
  uint8 ucICVGenRefJobId;
  uint8 ucICKKeyRefKeyId;
  uint8 ucICVValidateRefJobId;
}EthIf_ICVHandlerType;

/* Design ID : ETHIF_SDD_0621 */
typedef struct STag_EthIf_StaticController_PB
{
  /*pPhysCtrl*/
  const EthIf_StaticPhyController*  pPhysCtrl;
  /* pTrcv */
  const EthIf_StaticTransceiver*  pTrcv;
  /* pTrcv_PB */
  const EthIf_StaticTransceiver_PB*  pTrcv_PB;
  #if (ETHIF_MACSEC_SUPPORT_ENABLED == STD_ON)
  uint8 ucSWMacSecIndex;
  #endif
  /* VlanTag Configured per controller */
  uint16 usEthIfVlanTagLsb;
  /* MTU for Each EthIF Controller */
  uint16 ucCtrlMTU;
  /* MACSEC Support */
  EthIf_MacsecType usmacsec;
  /* PAEInstance */
  const EthIf_StaticPaeInstance* pPaeInst;
}EthIf_StaticController_PB;

/* Structure for Switch: */
/* Design ID : ETHIF_SDD_0527 */
typedef struct STag_EthIf_StaticSwitch_PB
{
  /* Swicth index to be feteched from the ref. */
  uint8 ucSwtIdx;
}EthIf_StaticSwitch_PB;


/* Structure for the frame type */
/* Design ID : ETHIF_SDD_0522 */
typedef struct STag_EthIf_FrameTypeToRxIndFunc_PB
{
  /* FrameType configured - Taken from the configuration */
  uint16 usEthIfFrameType;
  /* index to the rx indication function */
  uint8 ucRxIndex;
}EthIf_FrameTypeToRxIndFunc_PB;

typedef enum ETag_EthIf_MetaDataItem{
  ETHIF_MATADATA_ITEM_PRIORITY_8 = (uint8)0u,
  ETHIF_MATADATA_ITEM_BROADCAST_8,
  ETHIF_MATADATA_ITEM_VLAN_16,
  ETHIF_MATADATA_ITEM_LISTELEM_PTR,
  ETHIF_MATADATA_ITEM_TIMETUPLE_TYPE_PTR,
  ETHIF_MATADATA_ITEM_ETHERNET_MAC_64
}EthIf_MetaDataItem;

typedef struct STag_EthIf_MetaDataItemInfo{
  /* MetaDataItemType */
  EthIf_MetaDataItem ddMetaDataItemType;
  /* MetaDataItemLength */
  uint8 ucMetaDataItemLength;
}EthIf_MetaDataItemInfo;

typedef struct STag_EthIf_TxPoolType
{
  Eth_FrameType ddFrameType;
  uint8 ucCtrlIdx;
  uint8 ucPriorityId;
}EthIf_TxPoolType;

typedef struct STag_EthIf_TxPduType
{
  const EthIf_TxPoolType * pTxPool;
  #ifdef ETHIF_IMMEDIATE_TRANSMIT_SUPPORT
  Eth_BufIdxType ddTxHandleId;
  #endif
  #if (ETHIF_METADATA_SUPPORT == STD_ON)
  const uint8 ucMetaDataMask;
  #endif
  PduIdType ddConfPduId;
  boolean blKeepTxBuffer;
}EthIf_TxPduType;

typedef struct STag_EthIf_RxPoolType
{
  uint8 ucPduIDsIndex;
  uint8 ucPdusize;
  uint8 ucPhyCtrlIdx;
}EthIf_RxPoolType;

typedef struct STag_EthIf_RxPduType
{
  #if (ETHIF_METADATA_SUPPORT == STD_ON)
  uint8 * pMetadataBuffer;
  const uint8 ucMetaDataMask;
  #endif
  uint8 ucRxPduId;
  boolean blKeepTxBuffer;
}EthIf_RxPduType;



/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/

#endif /* ETHIF_CFG_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
