/*******************************************************************************
**  FILE-NAME: EthIf_Cfg.c                                                  **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_1/PC_Config/xml/EthIf_Config_1.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:41:27 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/**
  *
  * #section EthIf_Cfg_C_REF_1
  * Violates MISRA 2012 Advisory Rule 20.1,
  * #include directives should only be preceded by preprocessor directives or
  * comments.
  *
**/

/* PRQA S 0380 EOF */
/* violates Number of macro definitions exceeds 4095 - program does not */
/* conform strictly to ISO:C99 */ /*invalid QAC as total number of macros in */
/* code are less than 4095*/

/* Violates #ref EthIf_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
/* PRQA S 5087 EOF */
/* PRQA S 1290 EOF */
/* PRQA S 4640 EOF */
/******************************************************************************/
/* Design ID : ETHIF_SDD_0726 */
#include "EthIf.h"
#include "EthIf_Cfg.h"
#include "EthIf_IntTypes.h"
#include "TcpIp.h"
#include "EthSM.h"
#include "EthIf_Version.h"
#include "LSduR_EthIf.h"
#include "Cdd.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (ETHIF_VERSION_AR_RELEASE_MAJOR_VERSION != ETHIF_AR_RELEASE_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Major Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_MINOR_VERSION != ETHIF_AR_RELEASE_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Minor Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_REVISION_VERSION != ETHIF_AR_RELEASE_REVISION_VERSION)
  #error "ETHIF Code : Mismatch in Specification Revision Version"
#endif

#if (ETHIF_VERSION_SW_MAJOR_VERSION != ETHIF_SW_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Major Version"
#endif

#if (ETHIF_VERSION_SW_MINOR_VERSION != ETHIF_SW_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/



/* EthIf_GaaClkUnitIndx with EthUlkUnitID */
#define ETHIF_START_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"
const uint8  EthIf_GaaClkUnitIndx
 [ETHIF_NUM_OF_PHYSICAL_CONTROLLERS][ETHIF_CLKUNIT_INDEX]
  = {
  	/*EthIf_GaaClkUnitIndx: 0*/
  	{0x0},
  	/*EthIf_GaaClkUnitIndx: 1*/
  	{0x0}
  };
#define ETHIF_STOP_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0611 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxIndFuncPtr EthIf_GaaRxIndicationFunc_PB[ETHIF_UL_RXINDICATION_NUM] =
{
  &TcpIp_RxIndication,
  &TcpIp_RxIndication
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0618 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxConFuncPtr
  EthIf_GaaTxConfirmationFunc_PB[ETHIF_UL_TXCONFIRMATION_NUM] =
{
  &Cdd_EthIfTxConfirmation
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0610 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_LinkStateChangeFuncPtr
  EthIf_GaaLinkStateChangeFunc_PB[ETHIF_UL_LINKSTATECHANGE_NUM] =
{
  
  /* UL_LinkStateChange */
  &Cdd_EthIfLinkStateChange
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0617 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TrcvApis  EthIf_GaaTrcvApis[1] =
{
  /* EthIf_GaaTrcvApis :0 */
  {
    &EthTrcv_SetTransceiverMode,

    &EthTrcv_GetTransceiverMode,

    &EthTrcv_GetLinkState,


    &EthTrcv_TransceiverLinkStateRequest
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"




/* Design ID : ETHIF_SDD_0612 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticController EthIf_GaaStaticController[ETHIF_NUM_OF_CONTROLLERS] =
{
/* EthIf_GaaStaticController : EthIfController_0 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      0

  },
/* EthIf_GaaStaticController : EthIfController_1 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      1

  },
/* EthIf_GaaStaticController : EthIfController_2 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      2

  },
/* EthIf_GaaStaticController : EthIfController_3 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      3

  },
/* EthIf_GaaStaticController : EthIfController_4 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      4

  },
/* EthIf_GaaStaticController : EthIfController_5 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      5

  },
/* EthIf_GaaStaticController : EthIfController_6 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      6

  },
/* EthIf_GaaStaticController : EthIfController_7 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      7

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0622 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticController_PB EthIf_GaaStaticController_PB[ETHIF_NUM_OF_CONTROLLERS] =
{
/* EthIf_GaaStaticController : EthIfController_0 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
      /* pTrcv */
      &EthIf_GaaStaticTransceiver[EthIfConf_EthIfTransceiver_EthIfTransceiver_0],
      /* pTrcv_PB */
      &EthIf_GaaStaticTransceiver_PB[EthIfConf_EthIfTransceiver_EthIfTransceiver_0],
      /* usEthIfVlanTagLsb */
      0x8002U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_1 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* usEthIfVlanTagLsb */
      0x0U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_2 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* usEthIfVlanTagLsb */
      0x8002U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_3 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* usEthIfVlanTagLsb */
      0x8007U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_4 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* usEthIfVlanTagLsb */
      0x8008U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_5 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* usEthIfVlanTagLsb */
      0x8009U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_6 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* usEthIfVlanTagLsb */
      0x81F4U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_7 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* usEthIfVlanTagLsb */
      0x0U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticClkUnit EthIf_GaaStaticClkUnit
[ETHIF_NUM_OF_CLKUNIT] =
{
/* EthIf_GaaStaticClkUnit - EthIfPhysController_0 */
{
  
  /* ucClkUnitIdx */
  &EthIf_GaaClkUnitIndx[0][0],
  
  /* ucClkUnitSize */
  0x1
},
/* EthIf_GaaStaticClkUnit - EthIfPhysController_1 */
{
  
  /* ucClkUnitIdx */
  &EthIf_GaaClkUnitIndx[1][0],
  
  /* ucClkUnitSize */
  0x1
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0613 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticPhyController EthIf_GaaStaticPhyController[ETHIF_NUM_OF_PHYSICAL_CONTROLLERS] =
{
  /* EthIf_GaaStaticPhyController : EthIfPhysController_0 */
  {
    /*ucPhysCtrlIdx*/
    0x0,

    /* ClkUnit Index */
    &EthIf_GaaStaticClkUnit[0]

  },
  /* EthIf_GaaStaticPhyController : EthIfPhysController_1 */
  {
    /*ucPhysCtrlIdx*/
    0x1,

    /* ClkUnit Index */
    &EthIf_GaaStaticClkUnit[1]

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0623 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticPhyController_PB EthIf_GaaStaticPhyController_PB
  [ETHIF_NUM_OF_PHYSICAL_CONTROLLERS] =
{
  /* EthIf_GaaStaticPhyController : EthIfPhysController_0 */
  {


    /* ucEthCtrlIdx  - IDx of actual ethernet driver */
    0x0,

    /* WEthCtrlIdx - IDx of actual wireless ethernet driver */
    ETHIF_INVALID,

    /* blCtrlHWDataTransfer - hardware supported data transfer */
    ETHIF_FALSE


  },
  /* EthIf_GaaStaticPhyController : EthIfPhysController_1 */
  {


    /* ucEthCtrlIdx  - IDx of actual ethernet driver */
    0x1,

    /* WEthCtrlIdx - IDx of actual wireless ethernet driver */
    ETHIF_INVALID,

    /* blCtrlHWDataTransfer - hardware supported data transfer */
    ETHIF_FALSE


  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0615 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticTransceiver EthIf_GaaStaticTransceiver[ETHIF_NUM_OF_TRANSCEIVERS] =
{
  /* EthIf_GaaStaticTransceiver : EthIfTransceiver_0 */
  {
    /* ucEthIfTrcvIdx */
    0x0

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0624 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticTransceiver_PB EthIf_GaaStaticTransceiver_PB[ETHIF_NUM_OF_TRANSCEIVERS] =
{
  /* EthIf_GaaStaticTransceiver : EthIfTransceiver_0 */
  {
    /* pTrcvDriver */
    &EthIf_GaaTrcvApis[0],

    /*EthIfTransceiver_0*/
    /* ucEthTrcvIdx - Index of the actual transceiver */
    0x0U,
    /* ucWEthTrcvIdx - IDx of actual wireless ethernet driver */
    ETHIF_INVALID,


    /* ucTrcvDriver */
    ETHIF_INVALID
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"



/* Design ID : ETHIF_SDD_0614 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticSwitch_PB EthIf_GaaStaticSwitch_PB[1] =
{
  /* EthIf_GaaStaticSwitch : EthIfSwitch_0 */
  {
    /* ucSwtIdx */
    0x00
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxPduType EthIf_GaaRxPdus[ETHIF_NO_OF_RXPDUS] =
{
  /* EthIf_GaaRxPdu : EthIf_RxMsg_0 */
  {
    
    /* pMetadataBuffer */
    &EthIf_GaaBufferMetaDataType_2[0],
    
    /* ucMetaDataMask */
    3u,
    
    /* ucRxPduId */
    LSduRConf_LSduRPathSourcePdu_EthMsg_R_0,
    
    /* blKeepTxBuffer */
    ETHIF_FALSE
  },
  /* EthIf_GaaRxPdu : EthIf_RxMsg_2 */
  {
    
    /* pMetadataBuffer */
    &EthIf_GaaBufferMetaDataType_3[0],
    
    /* ucMetaDataMask */
    2u,
    
    /* ucRxPduId */
    LSduRConf_LSduRPathSourcePdu_EthMsg_R_2,
    
    /* blKeepTxBuffer */
    ETHIF_FALSE
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxPoolType EthIf_GaaRxPools[ETHIF_NO_OF_RXPOOLS] =
{
  /* EthIf_GaaRxPool : EthIfFrameConfig_0_EthIfFrameRxPool_0 */
  {
    
    /* ucPduIDsIndex */
    0u,
    
    /* ucPdusize */
    1u,
    
    /* ucPhyCtrlIdx */
    0u
  },
  /* EthIf_GaaRxPool : EthIfFrameConfig_1_EthIfFrameRxPool_0 */
  {
    
    /* ucPduIDsIndex */
    1u,
    
    /* ucPdusize */
    1u,
    
    /* ucPhyCtrlIdx */
    ETHIF_INVALID
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"


#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_MetaDataItemInfo EthIf_GaaRxMetaDataItemInfo[2] =
{
  /* EthIf_GaaMetaDataItemInfo : 3 */
  {
    
    /* ddMetaDataItemType */
    ETHIF_MATADATA_ITEM_ETHERNET_MAC_64,
    
    /* ucMetaDataItemLength */
    8
  },
  /* EthIf_GaaMetaDataItemInfo : 4 */
  {
    
    /* ddMetaDataItemType */
    ETHIF_MATADATA_ITEM_BROADCAST_8,
    
    /* ucMetaDataItemLength */
    1
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0609 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_FrameTypeToRxIndFunc_PB
EthIf_GaaFrameTypeToRxIndFunc_PB[ETHIF_NUM_FRAME_OWNER] =
{
  /* EthIf_GaaFrameTypeToRxIndFunc : EthIfFrameConfig_0 */
  {
    
    /* usEthIfFrameType */
    0x800u,
    
    /* ucRxFixedPoolIndex */
    0u,
    
    /* ucRxFixedPoolSize */
    1u,
    
    /* ucRxFloatPoolIndex */
    ETHIF_INVALID,
    
    /* ucRxFloatPoolSize */
    0u,
    
    /* ucRxIndex */
    0x0u
  },
  /* EthIf_GaaFrameTypeToRxIndFunc : EthIfFrameConfig_1 */
  {
    
    /* usEthIfFrameType */
    0x88F7u,
    
    /* ucRxFixedPoolIndex */
    ETHIF_INVALID,
    
    /* ucRxFixedPoolSize */
    0u,
    
    /* ucRxFloatPoolIndex */
    1u,
    
    /* ucRxFloatPoolSize */
    1u,
    
    /* ucRxIndex */
    0x1u
  }
};
/* PRQA S 5002 3 */
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPoolType EthIf_GaaTxPools[ETHIF_NO_OF_TXPOOLS] =
{
  /* EthIf_GaaTxPool : EthIfFrameTxPool_0 */
  {
    
    /* ddFrameType */
    0x800u,
    
    /* ucCtrlIdx */
    2u,
    
    /* ucPriorityId */
    1u
  },
  /* EthIf_GaaTxPool : EthIfFrameTxPool_0 */
  {
    
    /* ddFrameType */
    0x88F7u,
    
    /* ucCtrlIdx */
    1u,
    
    /* ucPriorityId */
    ETHIF_INVALID
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_MetaDataItemInfo EthIf_GaaTxMetaDataItemInfo[3] =
{
  /* EthIf_GaaMetaDataItemInfo : 0 */
  {
    
    /* ddMetaDataItemType */
    ETHIF_MATADATA_ITEM_ETHERNET_MAC_64,
    
    /* ucMetaDataItemLength */
    8
  },
  /* EthIf_GaaMetaDataItemInfo : 1 */
  {
    
    /* ddMetaDataItemType */
    ETHIF_MATADATA_ITEM_LISTELEM_PTR,
    
    /* ucMetaDataItemLength */
    4
  },
  /* EthIf_GaaMetaDataItemInfo : 2 */
  {
    
    /* ddMetaDataItemType */
    ETHIF_MATADATA_ITEM_PRIORITY_8,
    
    /* ucMetaDataItemLength */
    1
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPduType EthIf_GaaTxPdus[ETHIF_NO_OF_TXPDUS] =
{
  /* EthIf_GaaTxPdu : EthIf_TxMsg_0 */
  {
    
    /* pTxPool */
    &EthIf_GaaTxPools[0],
    
    /* ucMetaDataMask */
    6u,
    
    /* ddConfPduId */
    LSduRConf_LSduRPathDestinationPdu_EthMsg_T_0,
    
    /* blKeepTxBuffer */
    ETHIF_FALSE
  },
  /* EthIf_GaaTxPdu : EthIf_TxMsg_1 */
  {
    
    /* pTxPool */
    &EthIf_GaaTxPools[1],
    
    /* ucMetaDataMask */
    7u,
    
    /* ddConfPduId */
    LSduRConf_LSduRPathDestinationPdu_EthMsg_T_1,
    
    /* blKeepTxBuffer */
    ETHIF_FALSE
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
uint8 EthIf_GaaBufferMetaDataType_2[ETHIF_METADATATYPE_2_LENGTH];
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
uint8 EthIf_GaaBufferMetaDataType_3[ETHIF_METADATATYPE_3_LENGTH];
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

/*******************************************************************************
** Function Name        : EthIf_TxMacAddrAllign                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This function converts the MacAddress MetaDataItem  **
**                        from Platform ByteOrder to Network ByteOrder        **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : LpSrcMac, LucMetaDatalengh                          **
**                                                                            **
** InOut parameter      : LpDestMac                                           **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : void                                                **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_memcpy                     **
**                                             EthIf_ReverseCopy              **
**                                                                            **
** Design ID            : ETHIF_SDD_0801                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
static inline void EthIf_TxMacAddrAllign(uint8 * LpDestMac, const uint8 * LpSrcMac, uint8 LucMetaDatalength)
{
  #if (CPU_BYTE_ORDER == HIGH_BYTE_FIRST)
  if (LucMetaDatalength == ETHIF_MAC_ADDRESS_LENGTH + ETHIF_TWO)
  {
    LpSrcMac += ETHIF_TWO;
  }
  ETHIF_MEMCPY(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  #else
  EthIf_ReverseCopy(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  ETHIF_UNUSED(LucMetaDatalength);
  #endif
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"
/*******************************************************************************
** Function Name        : EthIf_GetMetaDataInfo                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This function fetches metadata items from           **
**                        Metadata pointer                                    **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : MetaDataPtr, LucMetaDataMask                        **
**                                                                            **
** InOut parameter      : MetaData                                            **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : Std_ReturnType                                      **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_memcpy                     **
**                                             EthIf_CopyToUint16             **
**                                                                            **
** Design ID            : ETHIF_SDD_0738                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
Std_ReturnType EthIf_GetMetaDataInfo(EthIf_MetaDataInfo * MetaData,
  uint8 * MetaDataPtr, const uint8 LucMetaDataMask)
/* PRQA S 4640 1 */
{
  uint8 LucIterCount;
  EthIf_MetaDataItem LddMetaDataItem;
  const EthIf_MetaDataItemInfo * LpMetaDataItemInfo;

  Std_ReturnType LddReturnValue  = (Std_ReturnType)E_OK;

  /* Initializing The metadata fileds, Mac Address is not initialized as it
     is mandatory */

  if ((MetaData != NULL_PTR) && (MetaDataPtr != NULL_PTR))
  {
    /* Meta Data Item ETHERNET_MAC_64 is not Initialized as it is mandatory */
    MetaData->TimeTuplePtr = NULL_PTR;
    MetaData->ListElemTypePtr = NULL_PTR;
    MetaData->Vlan16 = (uint16)ETHIF_ZERO;
    MetaData->Priority = ETHIF_ZERO;

    LpMetaDataItemInfo = &EthIf_GaaTxMetaDataItemInfo[ETHIF_ZERO];
    for (LucIterCount = ETHIF_NO_OF_TXMETADATAITEMS; LucIterCount > ETHIF_ZERO;
         LucIterCount--)
    {
      LddMetaDataItem = LpMetaDataItemInfo->ddMetaDataItemType;
      if (ETHIF_TRUE ==
          ETHIF_BITSET_CHECK(LucMetaDataMask, (LucIterCount - ETHIF_ONE)))
      {
        switch (LddMetaDataItem)
        {
          case ETHIF_MATADATA_ITEM_PRIORITY_8:
            MetaData->Priority = *MetaDataPtr;
            MetaDataPtr += LpMetaDataItemInfo->ucMetaDataItemLength;
            break;
          case ETHIF_MATADATA_ITEM_ETHERNET_MAC_64:
            /* Copy bytes of mac address received from metadataptr to the
               MacAddress */
            EthIf_TxMacAddrAllign(MetaData->MacAddress, MetaDataPtr,
              LpMetaDataItemInfo->ucMetaDataItemLength);
            MetaDataPtr += LpMetaDataItemInfo->ucMetaDataItemLength;
            break;
          case ETHIF_MATADATA_ITEM_LISTELEM_PTR:
            /* Copy the ListElemType address received from metadataptr to the
               pointer of ListElemType */
            ETHIF_MEMCPY(&MetaData->ListElemTypePtr, MetaDataPtr, sizeof(ETHIF_PTR_TYPE));
            MetaDataPtr += LpMetaDataItemInfo->ucMetaDataItemLength;
            break;
          default :
            /* No other metadataitem supported */
            LddReturnValue  = (Std_ReturnType)E_NOT_OK;
            break;
        }
      }
      LpMetaDataItemInfo++;
    }
  }
  else
  {
    LddReturnValue  = (Std_ReturnType)E_NOT_OK;
  }
  return LddReturnValue;
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"

/*******************************************************************************
** Function Name        : EthIf_RxMacAddrAllign                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This function converts the MacAddress MetaDataItem  **
**                        from Network ByteOrder to Platform ByteOrder        **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : LpSrcMac, LucMetaDatalength                          **
**                                                                            **
** InOut parameter      : LpDestMac                                           **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : void                                                **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_memcpy                     **
**                                             EthIf_ReverseCopy              **
**                                                                            **
** Design ID            : ETHIF_SDD_0802                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
static inline void EthIf_RxMacAddrAllign(uint8 * LpDestMac, const uint8 * LpSrcMac, uint8 LucMetaDatalength)
{
  #if (CPU_BYTE_ORDER == HIGH_BYTE_FIRST)
  if (LucMetaDatalength == ETHIF_MAC_ADDRESS_LENGTH + ETHIF_TWO)
  {
    *LpDestMac++ = 0x00;
    *LpDestMac++ = 0x00;
  }
  ETHIF_MEMCPY(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  #else
  /* If the System Endiness id Low Byte first,
     Copy it after reversing with zero padding last two bytes */
  EthIf_ReverseCopy(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  LpDestMac += ETHIF_MAC_ADDRESS_LENGTH;
  if (LucMetaDatalength == ETHIF_MAC_ADDRESS_LENGTH + ETHIF_TWO)
  {
    *LpDestMac++ = 0x00;
    *LpDestMac++ = 0x00;
  }
  #endif
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"
/*******************************************************************************
** Function Name        : EthIf_PutMetaDataInfo                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This API service of the Ethernet Interface          **
**                        processes configured metadata                       **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : LucMetaDataMask, PhysAddrPtr, IngressTimeTuplePtr,  **
**                        IsBroadcast                                         **
**                                                                            **
** InOut parameter      : MetaDataPtr                                         **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : void                                                **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_Memcpy                     **
**                                                                            **
** Design ID            : ETHIF_SDD_0216                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
void EthIf_PutMetaDataInfo(uint8 * MetaDataPtr,
  const uint8 LucMetaDataMask, const uint8* PhysAddrPtr,
  #ifdef ETHIF_RXINDICATION_INGRESSTIME_SUPPORT
  const TimeTupleType* IngressTimeTuplePtr,
  #endif
  boolean IsBroadcast)
/* PRQA S 4640 1 */
{
  uint8 LucIterCount;
  EthIf_MetaDataItem LddMetaDataItem;
  const EthIf_MetaDataItemInfo * LpMetaDataItemInfo;

  if (MetaDataPtr != NULL_PTR)
  {
    LpMetaDataItemInfo = &EthIf_GaaRxMetaDataItemInfo[ETHIF_ZERO];
    for (LucIterCount = ETHIF_NO_OF_RXMETADATAITEMS; LucIterCount > ETHIF_ZERO;
         LucIterCount--)
    {
      LddMetaDataItem = LpMetaDataItemInfo->ddMetaDataItemType;
      if (ETHIF_TRUE ==
          ETHIF_BITSET_CHECK(LucMetaDataMask, (LucIterCount - ETHIF_ONE)))
      {
        switch (LddMetaDataItem)
        {
          case ETHIF_MATADATA_ITEM_ETHERNET_MAC_64:
            /* Copy the received PhysAddrPtr to MetaDataPtr */
            EthIf_RxMacAddrAllign(MetaDataPtr, PhysAddrPtr,
              LpMetaDataItemInfo->ucMetaDataItemLength);
            MetaDataPtr += LpMetaDataItemInfo->ucMetaDataItemLength;
          break;
          case ETHIF_MATADATA_ITEM_BROADCAST_8:
            *MetaDataPtr = IsBroadcast;
            MetaDataPtr += LpMetaDataItemInfo->ucMetaDataItemLength;
            break;
          default :
            /* No other metadataitem supported */
            break;
        }
      }
      LpMetaDataItemInfo++;
    }
  }
  (void) IsBroadcast;
  #ifdef ETHIF_RXINDICATION_INGRESSTIME_SUPPORT
  (void) IngressTimeTuplePtr;
  #endif
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"

/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
