/*******************************************************************************
**  FILE-NAME: EthIf_Lcfg.c                                                 **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_6/PB_Config/xml/EthIf_Config_6.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:43:29 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/**
  *
  * #section EthIf_Cfg_C_REF_1
  * Violates MISRA 2012 Advisory Rule 20.1,
  * #include directives should only be preceded by preprocessor directives or
  * comments.
  *
**/

/* PRQA S 0380 EOF */
/* violates Number of macro definitions exceeds 4095 - program does not */
/* conform strictly to ISO:C99 */ /*invalid QAC as total number of macros in */
/* code are less than 4095*/

/* Violates #ref EthIf_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
/* PRQA S 5087 EOF */
/* PRQA S 1290 EOF */
/* PRQA S 5002 EOF */
/* PRQA S 1582 EOF */
/* PRQA S 4640 EOF */
/******************************************************************************/
#include "EthIf.h"
#include "EthIf_Cfg.h"
#include "EthIf_IntTypes.h"
#include "TcpIp.h"
#include "EthSM.h"
#include "EthIf_Version.h"
#include "Cdd.h"
#include "LSduR_EthIf.h"
#include "EthTSyn.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (ETHIF_VERSION_AR_RELEASE_MAJOR_VERSION != ETHIF_AR_RELEASE_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Major Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_MINOR_VERSION != ETHIF_AR_RELEASE_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Minor Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_REVISION_VERSION != ETHIF_AR_RELEASE_REVISION_VERSION)
  #error "ETHIF Code : Mismatch in Specification Revision Version"
#endif

#if (ETHIF_VERSION_SW_MAJOR_VERSION != ETHIF_SW_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Major Version"
#endif

#if (ETHIF_VERSION_SW_MINOR_VERSION != ETHIF_SW_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/



/* Design ID : ETHIF_SDD_0619*/
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_WakeupSourceType
  EthIf_GaaWakeupSource[ETHIF_TOTAL_NUM_OF_WAKEUPSOURCE] =
{
/* EthIf_WakeupSourceType - EthTrcvWakeupMap_0 */
{
  
  /* WakeupSource */
  0x1U,
  
  /* pTrcvDriver */
  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
  
  /* Referred Trcv Idx */
  0x00U
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPoolType EthIf_GaaTxPools[ETHIF_NO_OF_TXPOOLS] =
{
  /* EthIf_GaaTxPool : EthIfFrameTxPool_0 */
  {
    
    /* ddFrameType */
    0x800u,
    
    /* ucCtrlIdx */
    0u,
    
    /* ucPriorityId */
    ETHIF_INVALID
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"


#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPduType EthIf_GaaTxPdus[ETHIF_NO_OF_TXPDUS] =
{
  /* EthIf_GaaTxPdu : EthIfFrameTxPdu_0 */
  {
    
    /* pTxPool */
    &EthIf_GaaTxPools[0],
    
    /* ddConfPduId */
    LSduRConf_LSduRPathDestinationPdu_LSduRPathDestinationPdu_0,
    
    /* blKeepTxBuffer */
    ETHIF_FALSE
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

  /* Design ID : ETHIF_SDD_XXXX */
  #define ETHIF_START_SEC_CONST_UNSPECIFIED
  #include "EthIf_MemMap.h"
  const EthIf_ICVHandlerType EthIf_ICVHandlers[ETHIF_SW_MACSEC_CTRL_COUNT] =
  {
    /* EthIf_ICVRef : EthIfICVHandler_0 */
    {
      
      /* ucICVGenRefJobId */
      0u,
      
      /* ucICKKeyRefJobId */
      2u,
      
      /* ucICVValidateRefJobId */
      1u
    }
  };
  #define ETHIF_STOP_SEC_CONST_UNSPECIFIED
  #include "EthIf_MemMap.h"




/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
