/*******************************************************************************
**  FILE-NAME: EthIf_PBcfg.c                                                **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_6/PB_Config/xml/EthIf_Config_6.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:43:29 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/**
  *
  * #section EthIf_Cfg_C_REF_1
  * Violates MISRA 2012 Advisory Rule 20.1,
  * #include directives should only be preceded by preprocessor directives or
  * comments.
  *
**/

/* PRQA S 0380 EOF */
/* violates Number of macro definitions exceeds 4095 - program does not */
/* conform strictly to ISO:C99 */ /*invalid QAC as total number of macros in */
/* code are less than 4095*/

/* Violates #ref EthIf_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
/* PRQA S 5087 EOF */
/* PRQA S 1290 EOF */
/* PRQA S 5002 EOF */
/* PRQA S 1582 EOF */
/* PRQA S 4640 EOF */
/******************************************************************************/
/* Design ID : ETHIF_SDD_0726 */
#include "EthIf.h"
#include "EthIf_Cfg.h"
#include "EthIf_IntTypes.h"
#include "TcpIp.h"
#include "EthSM.h"
#include "EthIf_Version.h"
#include "Cdd.h"
#include "EthTSyn.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (ETHIF_VERSION_AR_RELEASE_MAJOR_VERSION != ETHIF_AR_RELEASE_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Major Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_MINOR_VERSION != ETHIF_AR_RELEASE_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Minor Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_REVISION_VERSION != ETHIF_AR_RELEASE_REVISION_VERSION)
  #error "ETHIF Code : Mismatch in Specification Revision Version"
#endif

#if (ETHIF_VERSION_SW_MAJOR_VERSION != ETHIF_SW_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Major Version"
#endif

#if (ETHIF_VERSION_SW_MINOR_VERSION != ETHIF_SW_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/

/*Con: EthIfPhysController para: ethIfCtrlIdx,,, ethIfPhysControllerIdx */
/* Design ID : ETHIF_SDD_0608 */
#define ETHIF_START_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"
const uint8  EthIf_GaaDrvToCtrlMapArray[2]
  = {  0x3,0x7  };
#define ETHIF_STOP_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"

/* EthIf_GaaClkUnitIndx with EthUlkUnitID */
#define ETHIF_START_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"
const uint8  EthIf_GaaClkUnitIndx
 [ETHIF_NUM_OF_PHYSICAL_CONTROLLERS][ETHIF_CLKUNIT_INDEX]
  = {
  	/*EthIf_GaaClkUnitIndx: 0*/
  	{0x0},
  	/*EthIf_GaaClkUnitIndx: 1*/
  	{0x0}
  };
#define ETHIF_STOP_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"

/* Generates EthTrcv module's API details*/
/* Design ID : ETHIF_SDD_0617 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TrcvApis  EthIf_GaaTrcvApis[1] =
{
  /* EthIf_GaaTrcvApis :0 */
  {
    &EthTrcv_SetTransceiverMode,

    &EthTrcv_GetTransceiverMode,

    &EthTrcv_GetLinkState,

    &EthTrcv_CheckWakeup,

    &EthTrcv_GetBusWuReason,

    &EthTrcv_TransceiverLinkStateRequest
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0610 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_LinkStateChangeFuncPtr EthIf_GaaLinkStateChangeFunc
[ETHIF_UL_LINKSTATECHANGE_NUM * ETHIF_CONFIGSET_COUNT] =
{
   &Cdd_EthIfLinkStateChange,
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "EthIf_MemMap.h"
    const EthIf_MkaLinkStateChangeFuncPtr EthIf_GaaMkaLinkStateChangeFunc
    [ETHIF_MKA_LINKSTATECHANGE_NUM * ETHIF_CONFIGSET_COUNT] =
{
  
  /* Mka_LinkStateChange */
  &Mka_LinkStateChange
};
    #define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0618 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxConFuncPtr EthIf_GaaTxConfirmationFunc
[ETHIF_UL_TXCONFIRMATION_NUM * ETHIF_CONFIGSET_COUNT] =
{
&Cdd_EthIfTxConfirmation,
&EthTSyn_TxConfirmation
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0611 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxIndFuncPtr EthIf_GaaRxIndicationFunc
[ETHIF_UL_RXINDICATION_NUM * ETHIF_CONFIGSET_COUNT] =
{

  NULL_PTR,
  &TcpIp_RxIndication

};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0609 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_FrameTypeToRxIndFunc EthIf_GaaFrameTypeToRxIndFunc
[ETHIF_NUM_FRAME_OWNER * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaFrameTypeToRxIndFunc : 0 - EthIfFrameConfig_0  */
 	{
 	  
 	  /* ucFrameType */
 	  0x800u,
 	  
 	  /* ucOwner */
 	  0x0u
 	},
 	/* EthIf_GaaFrameTypeToRxIndFunc : 1 - EthIfFrameConfig_1  */
 	{
 	  
 	  /* ucFrameType */
 	  0x88F7u,
 	  
 	  /* ucOwner */
 	  0x1u
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
    #include "EthIf_MemMap.h"
    const EthIf_StaticPaeInstance EthIf_GaaStaticPaeInstance
     [ETHIF_NUM_OF_PAE_INSTANCES * ETHIF_CONFIGSET_COUNT] =
    {
/* EthIf_GaaStaticPaeInstance_0  */
{
  
  /* PaeIdx */
  0x0U
}
};
    #define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0622 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticController EthIf_GaaStaticController
[ETHIF_NUM_OF_CONTROLLERS * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticController : 0 - EthIfController_0 - EthIfController_0 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0000u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x8002u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  &EthIf_GaaStaticTransceiver[EthIfConf_EthIfTransceiver_EthIfTransceiver_0],
 	  
 	  /* ucSWMacSecIndex */
 	  ETHIF_INVALID,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 1 - EthIfController_1 - EthIfController_1 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0001u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x0u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* ucSWMacSecIndex */
 	  0u,
 	  
 	  /* usmacsec */
 	  ETHIF_SW_MACSEC,
 	  
 	  /* pPaeInst */
 	  &EthIf_GaaStaticPaeInstance[0]
 	},
 	/* EthIf_GaaStaticController : 2 - EthIfController_2 - EthIfController_2 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0002u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x8002u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* ucSWMacSecIndex */
 	  ETHIF_INVALID,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 3 - EthIfController_3 - EthIfController_3 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0003u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x8007u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* ucSWMacSecIndex */
 	  ETHIF_INVALID,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 4 - EthIfController_4 - EthIfController_4 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0004u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x8008u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* ucSWMacSecIndex */
 	  ETHIF_INVALID,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 5 - EthIfController_5 - EthIfController_5 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0005u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x8009u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* ucSWMacSecIndex */
 	  ETHIF_INVALID,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 6 - EthIfController_6 - EthIfController_6 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0006u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x81F4u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* ucSWMacSecIndex */
 	  ETHIF_INVALID,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 7 - EthIfController_7 - EthIfController_7 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0007u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x0u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* ucSWMacSecIndex */
 	  ETHIF_INVALID,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"


/* Struc call for PhyController_ClkUnit */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticClkUnit EthIf_GaaStaticClkUnit
[ETHIF_NUM_OF_CLKUNIT] =
{
/* EthIf_GaaStaticClkUnit - EthIfPhysController_0 */
{
  
  /* ucclkunitIdx */
  &EthIf_GaaClkUnitIndx[0][0],
  
  /* ucclkunitsize */
  0x1
},
/* EthIf_GaaStaticClkUnit - EthIfPhysController_1 */
{
  
  /* ucclkunitIdx */
  &EthIf_GaaClkUnitIndx[1][0],
  
  /* ucclkunitsize */
  0x1
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0623 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticPhyController EthIf_GaaStaticPhyController
[ETHIF_NUM_OF_PHYSICAL_CONTROLLERS * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticPhyController : 0 - EthIfPhysController_0  */
 	{
 	  
 	  /* pEthDriver */
 	  &EthIf_GaaDriverApis[ETHIF_ETH_DRIVERA],
 	  
 	  /* ucCtrlIdx */
 	  0x0,
 	  
 	  /* blCtrlHWDataTransfer */
 	  ETHIF_FALSE,
 	  
 	  /* ucWEthCtrlRef */
 	  ETHIF_INVALID,
 	  
 	  /* ucCV2xCtrlRef */
 	  ETHIF_INVALID,
 	  
 	  /* ucPhysController */
 	  0x0u,
 	  
 	  /* ClkUnit */
 	  &EthIf_GaaStaticClkUnit[0]
 	},
 	/* EthIf_GaaStaticPhyController : 1 - EthIfPhysController_1  */
 	{
 	  
 	  /* pEthDriver */
 	  &EthIf_GaaDriverApis[ETHIF_ETH_DRIVERB],
 	  
 	  /* ucCtrlIdx */
 	  0x1,
 	  
 	  /* blCtrlHWDataTransfer */
 	  ETHIF_FALSE,
 	  
 	  /* ucWEthCtrlRef */
 	  ETHIF_INVALID,
 	  
 	  /* ucCV2xCtrlRef */
 	  ETHIF_INVALID,
 	  
 	  /* ucPhysController */
 	  0x1u,
 	  
 	  /* ClkUnit */
 	  &EthIf_GaaStaticClkUnit[1]
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0611 */

/* Design ID : ETHIF_SDD_0614 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticSwitch EthIf_GaaStaticSwitch
[ETHIF_NUM_OF_SWITCHES * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticSwitch : 0 - EthIfSwitch_0 */
 	{
 	  
 	  /* ucSwtIdx */
 	  0x00u
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0624 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticTransceiver EthIf_GaaStaticTransceiver
[ETHIF_NUM_OF_TRANSCEIVERS * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticTransceiver : 0 - EthIfTransceiver_0  */
 	{
 	  
 	  /* pTrcvDriver */
 	  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
 	  
 	  /* ucEthIfTrcvIdx */
 	  0x0000u,
 	  
 	  /* ucWEthTrcvIdx */
 	  ETHIF_INVALID
 	},
 	/* EthIf_GaaStaticTransceiver : 1 - EthIfTransceiver_1  */
 	{
 	  
 	  /* pTrcvDriver */
 	  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
 	  
 	  /* ucEthIfTrcvIdx */
 	  0x0001u,
 	  
 	  /* ucWEthTrcvIdx */
 	  ETHIF_INVALID
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0618 */

/* Design ID : ETHIF_SDD_0610 */

/* Design ID : ETHIF_SDD_0607 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_DrvApis  EthIf_GaaDriverApis
[ETHIF_ETH_DRIVER_COUNT * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaDriverApis : 0 - 0 */
 	{
 	  
 	  /* pEthSetControllerMode */
 	  &Eth_39_DriverA_SetControllerMode,
 	  
 	  /* pEthGetControllerMode */
 	  &Eth_39_DriverA_GetControllerMode,
 	  
 	  /* pEthGetPhysAddr */
 	  &Eth_39_DriverA_GetPhysAddr,
 	  
 	  /* pEthSetPhysAddr */
 	  &Eth_39_DriverA_SetPhysAddr,
 	  
 	  /* pEthUpdatePhysAddrFilter */
 	  &Eth_39_DriverA_UpdatePhysAddrFilter,
 	  
 	  /* pEthProvideTxBuffer */
 	  &Eth_39_DriverA_ProvideTxBuffer,
 	  
 	  /* pEthTransmit */
 	  &Eth_39_DriverA_Transmit,
 	  
 	  /* pEthReceive */
 	  &Eth_39_DriverA_Receive,
 	  
 	  /* pEthTxConfirmation */
 	  &Eth_39_DriverA_TxConfirmation,
 	  
 	  /* pEthGetCurrentTimeTuple */
 	  &Eth_39_DriverA_GetCurrentTimeTuple,
 	  
 	  /* pEthEnableEgressTimeStamp */
 	  &Eth_39_DriverA_EnableEgressTimeStamp,
 	  
 	  /* pEthGetEgressTimeStamp */
 	  &Eth_39_DriverA_GetEgressTimeStamp,
 	  
 	  /* pEthGetIngressTimeStamp */
 	  &Eth_39_DriverA_GetIngressTimeStamp,
 	  
 	  /* pEthSetPhcTime */
 	  &Eth_39_DriverA_SetPhcTime,
 	  
 	  /* pEthSetPhcCorrection */
 	  &Eth_39_DriverA_SetPhcCorrection,
 	  
 	  /* pEthGetPhcTime */
 	  &Eth_39_DriverA_GetPhcTime,
 	  
 	  /* pEthSetPpsSignalMode */
 	  &Eth_39_DriverA_SetPpsSignalMode
 	},
 	/* EthIf_GaaDriverApis : 1 - 1 */
 	{
 	  
 	  /* pEthSetControllerMode */
 	  &Eth_39_DriverB_SetControllerMode,
 	  
 	  /* pEthGetControllerMode */
 	  &Eth_39_DriverB_GetControllerMode,
 	  
 	  /* pEthGetPhysAddr */
 	  &Eth_39_DriverB_GetPhysAddr,
 	  
 	  /* pEthSetPhysAddr */
 	  &Eth_39_DriverB_SetPhysAddr,
 	  
 	  /* pEthUpdatePhysAddrFilter */
 	  &Eth_39_DriverB_UpdatePhysAddrFilter,
 	  
 	  /* pEthProvideTxBuffer */
 	  &Eth_39_DriverB_ProvideTxBuffer,
 	  
 	  /* pEthTransmit */
 	  &Eth_39_DriverB_Transmit,
 	  
 	  /* pEthReceive */
 	  &Eth_39_DriverB_Receive,
 	  
 	  /* pEthTxConfirmation */
 	  &Eth_39_DriverB_TxConfirmation,
 	  
 	  /* pEthGetCurrentTimeTuple */
 	  &Eth_39_DriverB_GetCurrentTimeTuple,
 	  
 	  /* pEthEnableEgressTimeStamp */
 	  &Eth_39_DriverB_EnableEgressTimeStamp,
 	  
 	  /* pEthGetEgressTimeStamp */
 	  &Eth_39_DriverB_GetEgressTimeStamp,
 	  
 	  /* pEthGetIngressTimeStamp */
 	  &Eth_39_DriverB_GetIngressTimeStamp,
 	  
 	  /* pEthSetPhcTime */
 	  &Eth_39_DriverB_SetPhcTime,
 	  
 	  /* pEthSetPhcCorrection */
 	  &Eth_39_DriverB_SetPhcCorrection,
 	  
 	  /* pEthGetPhcTime */
 	  &Eth_39_DriverB_GetPhcTime,
 	  
 	  /* pEthSetPpsSignalMode */
 	  &Eth_39_DriverB_SetPpsSignalMode
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_ConfigType  EthIf_GaaConfig
  [ETHIF_CONFIGSET_COUNT] =
{
  /* EthIf_GaaConfig : 0 -  */
  {
    
    /* pEthIfController */
    &EthIf_GaaStaticController[0],
    
    /* pEthIfFrameTypeToRxIndFunc */
    &EthIf_GaaFrameTypeToRxIndFunc[0],
    
    /* pEthIfPhyController */
    &EthIf_GaaStaticPhyController[0],
    
    /* pEthIfRxIndicationFunc */
    &EthIf_GaaRxIndicationFunc[0],
    
    /* pEthIfStaticSwitch */
    &EthIf_GaaStaticSwitch[0],
    
    /* EthIfTransceiver */
    &EthIf_GaaStaticTransceiver[0],
    
    /* EthIfLinkStateChangeFunc */
    &EthIf_GaaLinkStateChangeFunc[0],
    
    /* EthIfMkaLinkStateChangeFunc */
    &EthIf_GaaMkaLinkStateChangeFunc[0],
    
    /* EthIfTxConfirmationFunc */
    &EthIf_GaaTxConfirmationFunc[0],
    
    /* ulStartOfDbToc */
    0x550B2A59u,
    
    /* ucEthIfController */
    8u,
    
    /* ucFrameTypeToRxIndFunc */
    2u,
    
    /* ucPhyController */
    2u,
    
    /* ucRxIndicationFunc */
    2u,
    
    /* ucStaticSwitch */
    1u,
    
    /* ucTransceiver */
    2u,
    
    /* ucLinkStateChangeFunc */
    1u,
    
    /* ucTxConfirmationFunc */
    2u
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"



/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
