/*******************************************************************************
**  FILE-NAME: Tls_Cfg.c                                                    **
**                                                                            **
**  MODULE-NAME: Tls                                                          **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.4.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../170_Tls_TESTING/Code_Compliance/Config/Tls_Config_2/PC_Config/xml/Tls_Config_2.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/Csm/xml/Csm.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/KeyM/xml/KeyM.arxml
 *   ../../../170_Tls_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2026 Apr 22 15:04:33 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
        /*******************************************************************************
        **                      Parasoft violations Section                           **
        *******************************************************************************/
/** 
*
* #section Tls_Cfg_c_REF_1
* Violates MISRAC2012-RULE_20_1-a-4: Do not precede the #include directive with
* executable code
* Justification: Macros are defined by AUTOSAR standards and internal
* specifications.
*
* #section Tls_Cfg_c_REF_2
* Violates MISRAC2012-RULE_5_4-d-2: The '' macro has the same name (or the first
* 31 characters of the name) as the '' macro previously defined in the current
* file
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted
*
* #section Tls_Cfg_c_REF_3
* Violates MISRAC2012-RULE_5_4-c-2: The '' macro has the same name (or the first
* 31 characters of the name) as the '' macro previously defined in the current
* file
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted
*
* #section Tls_Cfg_c_REF_4
* Violates MISRAC2012-RULE_2_8-a-4:  A project should not contain unused variables with external linkage
* Justification: The global variable is declared with external linkage to allow access from other translation units
* Although it is not directly referenced within Tls_Cfg.c it is used in other static source files as 
  part of the TLS configuration. 
* This design is intentional and necessary for modularity and separation of configuration from implementation
*
* #section Tls_Cfg_c_REF_5
* Violates MISRAC2012-RULE_5_1-a-2: The '' macro has the same name (or the first
* 31 characters of the name) as the '' macro previously defined in the current
* file
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted
*
* #section Tls_Cfg_c_REF_6
* Violates MISRAC2012-RULE_1_1-b-2: More than 31 initial characters in an
* external identifier: 35
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted.
*
* #section Tls_Cfg_c_REF_7
* Violates MISRAC2012-RULE_1_1-a-2: More than 31 initial characters in an
* internal identifier: 34
* Justification: As macros are defined by AUTOSAR standards and internal
* specifications the length of name shall not be restricted.
*
* #section Tls_Cfg_c_REF_8
* Violates CERT_C-DCL06-a-3:  Use meaningful symbolic constants to represent literal values
* Justification: The message can be suppressed in case of generated file
*  Based on configuration size, array size is generated and hence exact value is being used instead of Macro.
*
        * #section Tls_Cfg_c_REF_9
        * Violates MISRAC2012-RULE_9_3-a-2:  Arrays shall not be partially initialized
        * Justification: This warning is generated for an array initialized with one value , 
* the rest elements are automatically initiallized with 0 for the global variable. No specific initiallization is mandatory.
*/


/* parasoft-begin-suppress MISRAC2012-RULE_20_1-a-4 "Reason: Tls_Cfg_c_REF_1" */
/* parasoft-begin-suppress MISRAC2012-RULE_5_4-d-2 "Reason: Tls_Cfg_c_REF_2" */
/* parasoft-begin-suppress MISRAC2012-RULE_5_4-c-2 "Reason: Tls_Cfg_c_REF_3" */
/* parasoft-begin-suppress MISRAC2012-RULE_5_1-a-2 "Reason: Tls_Cfg_c_REF_5" */
/* parasoft-begin-suppress MISRAC2012-RULE_1_1-b-2 "Reason: Tls_Cfg_c_REF_6" */
/* parasoft-begin-suppress MISRAC2012-RULE_1_1-a-2 "Reason: Tls_Cfg_c_REF_7" */

#include "KeyM.h"
	
	#include "Tls_Version.h"
	#include "Tls_InternalTypes.h"
	#include "Csm.h"	
	#include "Tls_Internal.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (TLS_VERSION_AR_RELEASE_MAJOR_VERSION != TLS_AR_RELEASE_MAJOR_VERSION)
  #error "TLS Code : Mismatch in Specification Major Version"
#endif

#if (TLS_VERSION_AR_RELEASE_MINOR_VERSION != TLS_AR_RELEASE_MINOR_VERSION)
  #error "TLS Code : Mismatch in Specification Minor Version"
#endif

#if (TLS_VERSION_AR_RELEASE_REVISION_VERSION != TLS_AR_RELEASE_REVISION_VERSION)
  #error "TLS Code : Mismatch in Specification Revision Version"
#endif

#if (TLS_VERSION_SW_MAJOR_VERSION != TLS_SW_MAJOR_VERSION)
  #error "TLS Code : Mismatch in Software Major Version"
#endif

#if (TLS_VERSION_SW_MINOR_VERSION != TLS_SW_MINOR_VERSION)
  #error "TLS Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/
#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_ConfigType   Tls_GaaConfig[TLS_ONE] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of TlsConfig : TlsConfig_0 */
	{
	  
	  /* usTlsMaxConnections */
	  2U
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"



/* Tls_GaaHSLookUp , index value basically represents which Handshake conatiners to be referred to */
#define TLS_START_SEC_CONST_16
#include "Tls_MemMap.h"
const uint16  Tls_GaaHSLookUp[TLS_NUM_OF_REFFERED_HANDSHAKE] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	0, 1, 2, 0
};
#define TLS_STOP_SEC_CONST_16
#include "Tls_MemMap.h"

/* Tls_GaaCiphrWrkrLookUp , index value basically represents which TlsCipherSuiteWorker conatiners to be referred to */
#define TLS_START_SEC_CONST_16
#include "Tls_MemMap.h"
const uint16  Tls_GaaCiphrWrkrLookUp[TLS_NUM_OF_REFFERED_CIPHERSUITE_WORKER] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	0, 1
};
#define TLS_STOP_SEC_CONST_16
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const TlsConnectionStrType  Tls_GaaConnection[TLS_TOTAL_CONNECTIONS] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of TlsConnection : 0_TlsConnection_0 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_CERT,
	  
	  /* ddTlsConnectionType */
	  TLS_SERVER,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_0,
	  
	  /* ulTlsCertIdnRefIdx */
	  1u,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  1U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  0u,
	  
	  /* usTlsMaxFragmentLen */
	  10U,
	  
	  /* usHSWrkrIdx */
	  0u,
	  
	  /* usNumOfHSWorkers */
	  3u,
	  
	  /* usTlsWaitingTimeout */
	  2u,
	  
	  /* ddTlsConnectionId */
	  0U,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE
	},
	/* Details of TlsConnection : 1_TlsConnection_1 */
	{
	  
	  /* ddTlsAuthType */
	  TLS_AUTH_CERT,
	  
	  /* ddTlsConnectionType */
	  TLS_SERVER,
	  
	  /* ulTlsCsmRndmGenJobRefId */
	  CsmConf_CsmJob_RandomGen_1,
	  
	  /* ulTlsCertIdnRefIdx */
	  0u,
	  
	  /* ucNumOfTlsCiphersuiteWorkers */
	  1U,
	  
	  /* ucCiphersuiteWorkerandConnectionLookUpIndex */
	  1u,
	  
	  /* usTlsMaxFragmentLen */
	  20U,
	  
	  /* usHSWrkrIdx */
	  3u,
	  
	  /* usNumOfHSWorkers */
	  1u,
	  
	  /* usTlsWaitingTimeout */
	  4u,
	  
	  /* ddTlsConnectionId */
	  1U,
	  
	  /* blTlsUseClintAuthReq */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionRecordSizeLimit */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionCertificateStatusRequest */
	  TLS_FALSE,
	  
	  /* usTlsUseExtensionMaxFragmentLength */
	  TLS_FALSE,
	  
	  /* blTlsUseExtensionTrustedCAKeys */
	  TLS_FALSE
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"


#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_CiphersuiteDefinition  Tls_GaaCiphersuiteDef[TLS_NUM_OF_CIPHERSUITE_DEFINITION] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of Tls_CiphersuiteDefinition : 0_TlsCiphersuiteDefinition_0 */
	{
	  
	  /* ddTlsVersion */
	  TLS_VERSION_V13,
	  
	  /* usTlsCiphersuiteId */
	  4865U,
	  
	  /* usTlsCiphersuitePriority */
	  1U,
	  
	  /* ucTlsCiphersuiteNameLen */
	  TLS_INVALID_STRING_LEN,
	  
	  /* blTlsUseAEADCipher */
	  TLS_FALSE,
	  
	  /* blTlsUsePresharedKeys */
	  TLS_FALSE,
	  
	  /* blTlsUseSecurityExtensionForceEncryptThenMac */
	  TLS_FALSE
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_CiphersuiteWorkerType  Tls_GaaCiphrSuiteWrkr[TLS_NUM_OF_CIPHERSUITE_WORKER] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of Tls_CiphersuiteWorker : 0_TlsCiphersuiteWorker_0 */
	{
	  
	  /* ulTlsCipherCsmDecryptJobRefIdx */
	  CsmConf_CsmJob_CipherCsmDecryptJob_0,
	  
	  /* ulTlsCipherCsmDecryptKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmDecryptKey_0,
	  
	  /* ulTlsCsmClientApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationTrafficSecretKey_0,
	  
	  /* ulTlsCsmServerApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationTrafficSecretKey_0,
	  
	  /* ulTlsCsmClientApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteKey_0,
	  
	  /* ulTlsCsmServerApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_0,
	  
	  /* ulTlsCsmClientApplWriteIVRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteIV_0,
	  
	  /* ulTlsCsmServerApplWriteIVRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteIV_0,
	  
	  /* ulTlsCipherCsmEncryptJobRefIdx */
	  CsmConf_CsmJob_CipherCsmEncryptJob_0,
	  
	  /* ulTlsCipherCsmEncryptKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmEncryptKey_0,
	  
	  /* ulTlsCipherCsmMacGenerateJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacGenerateJob_0,
	  
	  /* ulTlsCipherCsmMacGenerateKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacGenerateKey_0,
	  
	  /* ulTlsCipherCsmMacVerifyJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacVerifyJob_0,
	  
	  /* ulTlsCipherCsmMacVerifyKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacVerifyKey_0,
	  
	  /* ulTlsCiphrSutDefRefIdx */
	  0U,
	  
	  /* usTlsCipherAEADCipherKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherEncryptKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherMacKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsConnHandshakeRefBaseIndx */
	  0
	},
	/* Details of Tls_CiphersuiteWorker : 1_TlsCiphersuiteWorker_1 */
	{
	  
	  /* ulTlsCipherCsmDecryptJobRefIdx */
	  CsmConf_CsmJob_CipherCsmDecryptJob_1,
	  
	  /* ulTlsCipherCsmDecryptKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmDecryptKey_1,
	  
	  /* ulTlsCsmClientApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationTrafficSecretKey_1,
	  
	  /* ulTlsCsmServerApplTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationTrafficSecretKey_1,
	  
	  /* ulTlsCsmClientApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteKey_1,
	  
	  /* ulTlsCsmServerApplWriteKeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_1,
	  
	  /* ulTlsCsmClientApplWriteIVRefIdx */
	  CsmConf_CsmKey_ClientApplicationWriteIV_1,
	  
	  /* ulTlsCsmServerApplWriteIVRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteIV_1,
	  
	  /* ulTlsCipherCsmEncryptJobRefIdx */
	  CsmConf_CsmJob_CipherCsmEncryptJob_1,
	  
	  /* ulTlsCipherCsmEncryptKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmEncryptKey_1,
	  
	  /* ulTlsCipherCsmMacGenerateJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacGenerateJob_1,
	  
	  /* ulTlsCipherCsmMacGenerateKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacGenerateKey_1,
	  
	  /* ulTlsCipherCsmMacVerifyJobRefIdx */
	  CsmConf_CsmJob_CipherCsmMacVerifyJob_1,
	  
	  /* ulTlsCipherCsmMacVerifyKeyRefIdx */
	  CsmConf_CsmKey_CipherCsmMacVerifyKey_1,
	  
	  /* ulTlsCiphrSutDefRefIdx */
	  0U,
	  
	  /* usTlsCipherAEADCipherKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherEncryptKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsCipherMacKeyLength */
	  TLS_INVALID_SHORT,
	  
	  /* usTlsConnHandshakeRefBaseIndx */
	  0
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_HandshakeType Tls_GaaHandshake[TLS_NUM_OF_HANDSHAKE] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of Tls_Handshake : 0_TlsHandshake_0 */
	{
	  
	  /* ulTlsCsmHashVerifyJobRefIdx */
	  CsmConf_CsmJob_HashVerifyJob_0,
	  
	  /* ulTlsCsmKeyExchangeCalcPubValJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcPubValJobRef_0,
	  
	  /* ulTlsCsmKeyExchangeCalcSecretJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcSecretJobRef_0,
	  
	  /* ulTlsCsmKeyExchangeDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeTrafficSecretKey_0,
	  
	  /* ulTlsCsmClientHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWriteIV_0,
	  
	  /* ulTlsCsmClientHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWritekey_0,
	  
	  /* ulTlsCsmServerHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeTrafficSecretKey_0,
	  
	  /* ulTlsCsmServerHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWriteIV_0,
	  
	  /* ulTlsCsmServerHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWritekey_0,
	  
	  /* ulTlsCsmDerivedKeyRefIdx */
	  CsmConf_CsmKey_DerivedKey_0,
	  
	  /* ulTlsCsmEarlySecretKeyRefIdx */
	  CsmConf_CsmKey_EarlySecretKey_0,
	  
	  /* ulTlsCsmHKDFExpandJobRefIdx */
	  CsmConf_CsmJob_HKDFExpandJob_0,
	  
	  /* ulTlsCsmHKDFExpandKeyRefIdx */
	  CsmConf_CsmKey_HKDFExpandKey_0,
	  
	  /* ulTlsCsmHKDFExtractJobRefIdx */
	  CsmConf_CsmJob_HKDFExtractJob_0,
	  
	  /* ulTlsCsmHKDFExtractKeyRefIdx */
	  CsmConf_CsmKey_HKDFExtractKey_0,
	  
	  /* ulTlsCsmHandshakeSecretKeyRefIdx */
	  CsmConf_CsmKey_HandshakeSecretKey_0,
	  
	  /* ulTlsCsmKeyExchangeEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeKeyRefIdx */
	  CsmConf_CsmKey_TlsCsmKeyExchangeKeyRef_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateJobRefIdx */
	  CsmConf_CsmJob_SigGenJob_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateKeyRefIdx */
	  CsmConf_CsmKey_SigGenKey_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmMasterSecretKeyRefIdx */
	  CsmConf_CsmKey_MasterKey_0,
	  
	  /* ulTlsCsmPrfMacJobRefIdx */
	  CsmConf_CsmJob_PrfMacJob_0,
	  
	  /* ulTlsCsmPrfMacKeyRefIdx */
	  CsmConf_CsmKey_PrfMacKey_0,
	  
	  /* ddTlsCsmPRFSupportType */
	  TLS_PRF_CSM_NO_SUPPORT,
	  
	  /* usTlsSupportedGrpId */
	  (uint16)TLS_SECP256R1,
	  
	  /* usTlsSignatureId */
	  (uint16)TLS_RSA_PKCS1_SHA256,
	  
	  /* usTlsGroupPriority */
	  TLS_INVALID_SHORT
	},
	/* Details of Tls_Handshake : 1_TlsHandshake_1 */
	{
	  
	  /* ulTlsCsmHashVerifyJobRefIdx */
	  CsmConf_CsmJob_HashVerifyJob_1,
	  
	  /* ulTlsCsmKeyExchangeCalcPubValJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcPubValJobRef_1,
	  
	  /* ulTlsCsmKeyExchangeCalcSecretJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcSecretJobRef_1,
	  
	  /* ulTlsCsmKeyExchangeDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeTrafficSecretKey_1,
	  
	  /* ulTlsCsmClientHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWriteIV_1,
	  
	  /* ulTlsCsmClientHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWritekey_1,
	  
	  /* ulTlsCsmServerHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeTrafficSecretKey_1,
	  
	  /* ulTlsCsmServerHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWriteIV_1,
	  
	  /* ulTlsCsmServerHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ServerApplicationWriteKey_1,
	  
	  /* ulTlsCsmDerivedKeyRefIdx */
	  CsmConf_CsmKey_DerivedKey_1,
	  
	  /* ulTlsCsmEarlySecretKeyRefIdx */
	  CsmConf_CsmKey_EarlySecretKey_1,
	  
	  /* ulTlsCsmHKDFExpandJobRefIdx */
	  CsmConf_CsmJob_HKDFExpandJob_1,
	  
	  /* ulTlsCsmHKDFExpandKeyRefIdx */
	  CsmConf_CsmKey_HKDFExpandKey_1,
	  
	  /* ulTlsCsmHKDFExtractJobRefIdx */
	  CsmConf_CsmJob_HKDFExtractJob_1,
	  
	  /* ulTlsCsmHKDFExtractKeyRefIdx */
	  CsmConf_CsmKey_HKDFExtractKey_1,
	  
	  /* ulTlsCsmHandshakeSecretKeyRefIdx */
	  CsmConf_CsmKey_HandshakeSecretKey_1,
	  
	  /* ulTlsCsmKeyExchangeEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeKeyRefIdx */
	  CsmConf_CsmKey_TlsCsmKeyExchangeKeyRef_1,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateJobRefIdx */
	  CsmConf_CsmJob_SigGenJob_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateKeyRefIdx */
	  CsmConf_CsmKey_SigGenKey_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmMasterSecretKeyRefIdx */
	  CsmConf_CsmKey_MasterKey_1,
	  
	  /* ulTlsCsmPrfMacJobRefIdx */
	  CsmConf_CsmJob_PrfMacJob_1,
	  
	  /* ulTlsCsmPrfMacKeyRefIdx */
	  CsmConf_CsmKey_PrfMacKey_1,
	  
	  /* ddTlsCsmPRFSupportType */
	  TLS_PRF_CSM_NO_SUPPORT,
	  
	  /* usTlsSupportedGrpId */
	  (uint16)TLS_SECP384R1,
	  
	  /* usTlsSignatureId */
	  (uint16)TLS_RSA_PKCS1_SHA384,
	  
	  /* usTlsGroupPriority */
	  TLS_INVALID_SHORT
	},
	/* Details of Tls_Handshake : 2_TlsHandshake_2 */
	{
	  
	  /* ulTlsCsmHashVerifyJobRefIdx */
	  CsmConf_CsmJob_HashVerifyJob_2,
	  
	  /* ulTlsCsmKeyExchangeCalcPubValJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcPubValJobRef_2,
	  
	  /* ulTlsCsmKeyExchangeCalcSecretJobRefIdx */
	  CsmConf_CsmJob_TlsCsmKeyExchangeCalcSecretJobRef_2,
	  
	  /* ulTlsCsmKeyExchangeDecryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeDecryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmClientHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeTrafficSecretKey_2,
	  
	  /* ulTlsCsmClientHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWriteIV_2,
	  
	  /* ulTlsCsmClientHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ClientHandshakeWritekey_2,
	  
	  /* ulTlsCsmServerHSTrafficSecretKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeTrafficSecretKey_2,
	  
	  /* ulTlsCsmServerHandshakeWriteIVKeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWriteIV_2,
	  
	  /* ulTlsCsmServerHandshakeWritekeyRefIdx */
	  CsmConf_CsmKey_ServerHandshakeWritekey_2,
	  
	  /* ulTlsCsmDerivedKeyRefIdx */
	  CsmConf_CsmKey_DerivedKey_2,
	  
	  /* ulTlsCsmEarlySecretKeyRefIdx */
	  CsmConf_CsmKey_EarlySecretKey_2,
	  
	  /* ulTlsCsmHKDFExpandJobRefIdx */
	  CsmConf_CsmJob_HKDFExpandJob_2,
	  
	  /* ulTlsCsmHKDFExpandKeyRefIdx */
	  CsmConf_CsmKey_HKDFExpandKey_2,
	  
	  /* ulTlsCsmHKDFExtractJobRefIdx */
	  CsmConf_CsmJob_HKDFExtractJob_2,
	  
	  /* ulTlsCsmHKDFExtractKeyRefIdx */
	  CsmConf_CsmKey_HKDFExtractKey_2,
	  
	  /* ulTlsCsmHandshakeSecretKeyRefIdx */
	  CsmConf_CsmKey_HandshakeSecretKey_2,
	  
	  /* ulTlsCsmKeyExchangeEncryptJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeEncryptKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeKeyRefIdx */
	  CsmConf_CsmKey_TlsCsmKeyExchangeKeyRef_2,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateJobRefIdx */
	  CsmConf_CsmJob_SigGenJob_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureGenerateKeyRefIdx */
	  CsmConf_CsmKey_SigGenKey_0,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyJobRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmKeyExchangeSignatureVerifyKeyRefIdx */
	  TLS_INVALID_WORD,
	  
	  /* ulTlsCsmMasterSecretKeyRefIdx */
	  CsmConf_CsmKey_MasterKey_2,
	  
	  /* ulTlsCsmPrfMacJobRefIdx */
	  CsmConf_CsmJob_PrfMacJob_2,
	  
	  /* ulTlsCsmPrfMacKeyRefIdx */
	  CsmConf_CsmKey_PrfMacKey_2,
	  
	  /* ddTlsCsmPRFSupportType */
	  TLS_PRF_CSM_NO_SUPPORT,
	  
	  /* usTlsSupportedGrpId */
	  (uint16)TLS_X25519,
	  
	  /* usTlsSignatureId */
	  (uint16)TLS_RSA_PKCS1_SHA512,
	  
	  /* usTlsGroupPriority */
	  TLS_INVALID_SHORT
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_0        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_0(void)
{
  Tls_MainFunction(0); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

/*******************************************************************************
** Function Name        : Tls_MainFunction_TlsConnection_1        **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This Service is Main function for a                 **
**                        Tls Connection                                      **
**                                                                            **
** Reentrancy           : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : None                                                **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : None                                                **
**                                                                            **
** Preconditions        : The Tls module must be initialized.                 **
**                                                                            **
** Remarks              : Global Variable(s)     :                            **
**                        None                                                **
**                        Function(s) invoked    :                            **
**                        Tls_MainFunction                                    **
**  Design ID           : TLS_SDD_0318                                        **
*******************************************************************************/

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

void Tls_MainFunction_TlsConnection_1(void)
{
  Tls_MainFunction(1); // parasoft-suppress CERT_C-DCL06-a-3 "Reason: Tls_Cfg_c_REF_8"
}
#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"



#define TLS_START_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"
const Tls_CertificateIdentityType  Tls_GaaCertificateIdentity[TLS_NUM_OF_CERTIFICATE_IDENTITYS] = // parasoft-suppress MISRAC2012-RULE_2_8-a-4 "Reason: Tls_Cfg_c_REF_4"
{
	/* Details of TlsCertificateIdentity Container : 0_TlsCertificateIdentity_0 */
	{
	  
	  /* ddTlsCipherKeyMLocalCertificateIdx  */
	  KeyMConf_KeyMCertificate_KeyMCertificate_Server_0,
	  
	  /* ddTlsCipherKeyMRemoteCertificateIdx  */
	  TLS_INVALID_SHORT,
	  
	  /* ddTlsCipherKeyMRemoteCertElementIdx  */
	  TLS_INVALID_SHORT,
	  
	  /* ddTlsCipherKeyMRemoteCertElementPublicKeyIdx  */
	  TLS_INVALID_SHORT
	},
	/* Details of TlsCertificateIdentity Container : 1_TlsCertificateIdentity_1 */
	{
	  
	  /* ddTlsCipherKeyMLocalCertificateIdx  */
	  KeyMConf_KeyMCertificate_KeyMCertificate_Server_1,
	  
	  /* ddTlsCipherKeyMRemoteCertificateIdx  */
	  TLS_INVALID_SHORT,
	  
	  /* ddTlsCipherKeyMRemoteCertElementIdx  */
	  TLS_INVALID_SHORT,
	  
	  /* ddTlsCipherKeyMRemoteCertElementPublicKeyIdx  */
	  TLS_INVALID_SHORT
	}
};
#define TLS_STOP_SEC_CONST_UNSPECIFIED
#include "Tls_MemMap.h"

        /****************************************************************************
        **                   Parasoft violations end Section                       **
        ****************************************************************************/
        /* parasoft-end-suppress MISRAC2012-RULE_20_1-a-4 */
        /* parasoft-end-suppress MISRAC2012-RULE_5_4-d-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_5_4-c-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_5_1-a-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_1_1-b-2 */
        /* parasoft-end-suppress MISRAC2012-RULE_1_1-a-2 */

/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
