/*******************************************************************************
**  FILE-NAME: EthIf_PBcfg.h                                                **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_8/PB_Config/xml/EthIf_Config_8.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthSwt_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthSwt_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:43:48 IST
 */
#ifndef ETHIF_PBCFG_H
#define ETHIF_PBCFG_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "EcuM_Types.h"
#include "ComStack_Types.h"
#include "EthTrcv.h"
#include "EthSwt_GeneralTypes.h"
#include "EthSwt_39_DriverA.h"
#include "EthSwt_39_DriverB.h"


/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define ETHIF_AR_RELEASE_MAJOR_VERSION    4
#define ETHIF_AR_RELEASE_MINOR_VERSION    10
#define ETHIF_AR_RELEASE_REVISION_VERSION 0
#define ETHIF_SW_MAJOR_VERSION            0
#define ETHIF_SW_MINOR_VERSION            7
#define ETHIF_SW_PATCH_VERSION            0
#define ETHIF_VENDOR_ID                   (uint16)39
#define ETHIF_MODULE_ID                   (uint16)65

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/
    /* Design ID : ETHIF_SDD_0592 */
    /*  Pre-compile option for variant-support */
    #define ETHIF_PRE_COMPILE_SINGLE                STD_OFF

    #define ETHIF_CONFIGSET_COUNT                   0x1u

    #define ETHIF_DBTOC_VALUE                       0x550B2A59u

    /* Design ID : ETHIF_SDD_0584*/
    /* Number of containers configured of EthIfTxConfirmationConfig */
    #define ETHIF_UL_TXCONFIRMATION_NUM             1U

    /* Design ID : ETHIF_SDD_0582 */
    /* Number of containers configured of EthIfTrcvLinkStateChgConfig */
    #define ETHIF_UL_LINKSTATECHANGE_NUM            1U

    /* Design ID : ETHIF_SDD_0582 */
    /* Number of containers configured of EthIfTrcvLinkStateChgConfig */
    #define ETHIF_MKA_LINKSTATECHANGE_NUM            0U

    /* Design_ID :  ETHIF_SDD_0401 */
    /* Safetyksar inclusion required */
    #define ETHIF_SAFE_KSAR                         STD_OFF

    /* Design ID : ETHIF_SDD_0595*/
      /* Precompile option to check if Version Info API is Enabled */
      #define ETHIF_VERSIONINFO_API                   STD_ON
      /* Design ID : ETHIF_SDD_0709*/
      /* Precompile option to check if WETH API is Enabled */
	  #define ETHIF_ENABLE_WETH_API                   STD_ON
/* Design ID : ETHIF_SDD_0588*/
      /* Precompile option to check if Development Error is Enabled */
      #define ETHIF_DEV_ERROR_DETECT                  STD_ON
      /* Design ID : ETHIF_SDD_0331*/
      /* Precompile option to check if Rx Polling is Enabled */
      #define ETHIF_ENABLE_RX_INTERRUPT               STD_OFF
      /* Design ID : ETHIF_SDD_0332*/
      /* Precompile option to check if Tx Polling is Enabled */
      #define ETHIF_ENABLE_TX_INTERRUPT               STD_ON
      /* Design ID : ETHIF_SDD_0590*/
      /* Precompile option to check if Get Baud Rate API is Enabled */
      #define ETHIF_GET_BAUDRATE                      STD_ON
      /* Design ID : ETHIF_SDD_0357*/
      /* Precompile option to check if Get Counter State API is Enabled */
      #define ETHIF_GET_COUNTER_STATE                 STD_ON
      /* Design ID : ETHIF_SDD_0350*/
      /* Precompile option to check if Global Time Support API is Enabled */
      #define ETHIF_GLOBALTIME_SUPPORT                STD_ON
      /* Design ID : ETHIF_SDD_0351*/
      /* Precompile option to check if Start Auto Negotiation API is Enabled */
      #define ETHIF_START_AUTO_NEGOTIATION            STD_ON
      /* Design ID : ETHIF_SDD_0322*/
      /* Precompile option to check if WakeUp Support is Enabled */
      #define ETHIF_WAKEUP_SUPPORT                    STD_ON
      /* Design ID : ETHIF_SDD_0320*/
      /* Value of EthIfTrcvLinkStateChgMainReload */
      #define ETHIF_TRCVLINKSTATECHGMAINRELOAD        2
      /* Design ID : ETHIF_SDD_0335*/
      /* Maximum number of iterations done in Mainfunction Rx */
      #define ETHIF_RXINDICATION_ITERATIONS           5
      /* Design ID : ETHIF_SDD_0569*/
      /* Maximum transmission unit (MTU) of the EthIfCtrl in [bytes] */
      #define ETHIF_MAXIMUM_TRANSMIT_UNIT             1500

      /* Design ID : ETHIF_SDD_0574*/
      /* Total number of switches */
      #define ETHIF_NUM_OF_SWITCHES                   2U
      /* Design ID : ETHIF_SDD_0584*/
      /* Number of containers configured of EthIfTxConfirmationConfig */
      #define ETHIF_UL_TXCONFIRMATION_NUM             1U

      /* Design ID : ETHIF_SDD_0319 */
      /* Total number of Transceiver drivers */
      #define ETHIF_TRCV_DRIVER_COUNT                 1U
      /* Design ID : ETHIF_SDD_0568 */
      /* Total number of Controller drivers */
      #define ETHIF_ETH_DRIVER_COUNT                  1U
      /* Design ID : ETHIF_SDD_0579 */
      /* Total number of Switch drivers */
      #define ETHIF_SWT_DRIVER_COUNT                  2U
      /* Design ID : ETHIF_SDD_0355*/
      /* period of main function EthIf_MainFunctionRx and EthIf_MainFunctionTx
	     in seconds */
      #define ETHIF_MAIN_FUNC_PERIOD                  0.005


     /* Precompile option for EthIf_GetPortMacAddr API */
     #define ETHIF_GET_PORT_MAC_ADDR_API              STD_ON

     /* Precompile option for EthIf_GetArlTable API */
     #define ETHIF_GET_ARL_TABLE                     STD_ON

     /* Precompile option for EthIf_StoreConfiguration API */
     #define ETHIF_STORE_CONFIGURATION_API           STD_ON


       /* Precompile option for EthIf_ResetConfiguration API */
      #define ETHIF_RESET_CONFIGURATION_API           STD_ON

      /* Design ID : ETHIF_SDD_0586*/
      /* Macro to check whether VLAN is supported */
      #define ETHIF_VLAN_SUPPORT                      STD_OFF
     /* Design ID : ETHIF_SDD_0567*/
      /* Macro to check whether CDD is supported */
      #define ETHIF_CDD_SUPPORT                       STD_ON
       /* Design ID : ETHIF_SDD_0580*/
      /* Macro for total number of WakeupSource configured */
      #define ETHIF_TOTAL_NUM_OF_WAKEUPSOURCE         2U


      /* Macro for EthTrcv Driver  */
      #define ETHIF_ETHTRCV_0_RTL82X1F                      0

      /* Design ID : ETHIF_SDD_0018 */
      /* Precompile option to check if SecurityEventReporting is Enabled */
      #define ETHIF_SECURITY_EVENT_ENABLED            STD_ON

      /* Design ID : ETHIF_SDD_0019 */
      /* Precompile option to check if GetAndResetMeasurementData API is Enabled */
      #define ETHIF_MEASUREMENT_DATA_API            STD_ON

      /* Design ID : ETHIF_SDD_0021 */
      /* Precompile option to check if GetCtrlIdxList API is Enabled */
      #define ETHIF_GET_CTRLIDXLIST_API            STD_OFF

      /* Design ID : ETHIF_SDD_0022 */
      /* Precompile option to check if GetVlanId API is Enabled */
      #define ETHIF_GET_VLANID_SUPPORT            STD_OFF


/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/

/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/

/* Design ID : ETHIF_SDD_0524 */
typedef void (*EthIf_RxIndFuncPtr)
(uint8 CtrlIdx, Eth_FrameType FrameType,
boolean IsBroadcast,
const uint8*  PhysAddrPtr,
const uint8*  DataPtr,
uint16 LenByte);

/* Design ID : ETHIF_SDD_0531 */
typedef void (*EthIf_TxConFuncPtr)
(uint8 CtrlIdx, Eth_BufIdxType BufIdx,
  Std_ReturnType Result);

/* Design ID : ETHIF_SDD_0523 */
typedef void (*EthIf_LinkStateChangeFuncPtr)
(uint8 CtrlIdx,
EthTrcv_LinkStateType LinkState);

/* Design ID : ETHIF_SDD_0523 */
typedef void (*EthIf_MkaLinkStateChangeFuncPtr)
(uint8 PaeIdx,
EthTrcv_LinkStateType LinkState);

typedef Std_ReturnType (*EthIf_EthTrcvSetTransceiverModeFuncPtr)
(uint8 TrcvIdx, Eth_ModeType TrcvMode);


typedef Std_ReturnType (*EthIf_EthTrcvGetTransceiverModeFuncPtr)
(uint8 TrcvIdx, Eth_ModeType*  TrcvModePtr);


typedef Std_ReturnType (*EthIf_EthTrcvGetLinkStateFuncPtr)
(uint8 TrcvIdx, EthTrcv_LinkStateType* LinkStatePtr);


typedef Std_ReturnType (*EthIf_EthTrcvCheckWakeupFuncPtr)
(uint8 TrcvIdx);

typedef Std_ReturnType (*EthIf_EthTrcvGetBusWuReasonFuncPtr)
(uint8 TrcvIdx, EthTrcv_WakeupReasonType*  WakeupReasonPtr);

typedef Std_ReturnType (*EthIf_EthTrcvTransceiverLinkStateRequestFuncPtr)
(uint8 TrcvIdx, EthTrcv_LinkStateType LinkState);


/* Design ID : ETHIF_SDD_0530 */
/* Structure for Transciever: */
typedef struct STag_EthIf_TrcvApis
{

  /* EthTrcvSetTransceiverMode */
  const EthIf_EthTrcvSetTransceiverModeFuncPtr  pEthTrcvSetTransceiverMode;

  /* EthTrcvGetTransceiverMode */
  const EthIf_EthTrcvGetTransceiverModeFuncPtr  pEthTrcvGetTransceiverMode;

  /* EthTrcvGetLinkState */
  const EthIf_EthTrcvGetLinkStateFuncPtr  pEthTrcvGetLinkState;

  /* EthTrcvCheckWakeup */
  const EthIf_EthTrcvCheckWakeupFuncPtr  pEthTrcvCheckWakeup;

  /* EthTrcvGetBusWuReason */
  const EthIf_EthTrcvGetBusWuReasonFuncPtr  pEthTrcvGetBusWuReason;

  /* EthTrcvTransceiverLinkStateRequest */
   const EthIf_EthTrcvTransceiverLinkStateRequestFuncPtr  pEthTrcvTransceiverLinkStateRequest;

}EthIf_TrcvApis;

 /* Design ID : ETHIF_SDD_0521 */

/* Structure for the EthIfClkUnit */
typedef struct STag_EthIf_StaticClkUnit
{
	/*EthIf controller clk index*/
	 const uint8* pclkindx;

	/* Controller's clk unit*/
	uint8 ucclksize;
}EthIf_StaticClkUnit;

/* Design ID : ETHIF_SDD_0620  */
typedef struct STag_EthIf_StaticPhyController
{

  /* ucCtrlIdx - IDx of actual ethernet driver */
  uint8 ucCtrlIdx;

  /* blCtrlHWDataTransfer - hardware supported data transfer */
  boolean blCtrlHWDataTransfer;

  /* WEthCtrlIdx - IDx of actual ethernet driver */
  uint8 ucWEthCtrlIdx;

  uint8 ucCV2xCtrlRef;

  uint8 ucPhysController;

  /* Index of ClkUnit w.r.t EthIf */
  const EthIf_StaticClkUnit*  pEthClk;
}EthIf_StaticPhyController;

typedef struct STag_EthIf_StaticTransceiver
{
  /* pTrcvDriver */
  const EthIf_TrcvApis*  pTrcvDriver;

  /* Transceiver index to be fetched from reference*/
  uint8 ucTrcvIdx;

  /* EthIf Transceiver index */
  uint8 ucWEthTrcvIdx;

}EthIf_StaticTransceiver;

/* Structure for Switch: */
/* Design ID : ETHIF_SDD_0527 */
typedef struct STag_EthIf_StaticSwitch
{
  /* Swicth index to be feteched from the ref. */
  uint8 ucSwtIdx;
  uint8 ucSwtDriverIdx;
}EthIf_StaticSwitch;

/* Design ID : ETHIF_SDD_0xxx */
typedef enum ETag_EthIf_MacsecType
{
  ETHIF_HW_MACSEC = 0x01U,
  ETHIF_NO_MACSEC,
  ETHIF_SW_MACSEC
}EthIf_MacsecType;

typedef struct STag_EthIf_StaticPaeInstance
{
  /* PaeIdx */
  uint8 ucPaeIdx;
}EthIf_StaticPaeInstance;

typedef struct STag_EthIf_ICVHandlerType
{
  uint8 ucICVGenRefJobId;
  uint8 ucICKKeyRefKeyId;
  uint8 ucICVValidateRefJobId;
}EthIf_ICVHandlerType;

/* Design ID : ETHIF_SDD_0525 */
typedef struct STag_EthIf_StaticController
{

  /*ucEthIfCtrlIdx*/
  uint8 ucEthIfCtrlIdx;

  uint16 ucCtrlMTU;

  /* ucEthIfMaxTxBufsTotal */
  uint32 ucEthIfMaxTxBufsTotal;

  /*ucVlanId*/
  uint16 ucVlanId;

  /*pPhysCtrl*/
    const EthIf_StaticPhyController*  pPhysCtrl;

  /*pTransceiver*/
    const EthIf_StaticTransceiver*  pTrancvr;

  #if (ETHIF_MACSEC_SUPPORT_ENABLED == STD_ON)
  uint8 ucSWMacSecIndex;
  #endif

  EthIf_MacsecType usmacsec;
  const EthIf_StaticPaeInstance* pPaeInst;

}EthIf_StaticController;



typedef Std_ReturnType (*EthIf_EthSwtGetArlTableFuncPtr)
(uint8 SwitchIdx, uint32 startEntry,
uint32 numberOfElements,
EthSwt_MacVlanType*  ArlTable);

typedef Std_ReturnType (*EthIf_EthSwtStoreConfigurationFuncPtr)
(uint8 SwitchIdx);

typedef Std_ReturnType (*EthIf_EthSwtResetConfigurationFuncPtr)
(uint8 SwitchIdx);

/* Design ID : ETHIF_SDD_0529 */
/* Structure for Switch drivers: */
typedef struct STag_EthIf_SwtApis
{
  /* EthSwtGetArlTable */
  const EthIf_EthSwtGetArlTableFuncPtr  pEthSwtGetArlTable;

  /* EthSwtStoreConfiguration */
  const EthIf_EthSwtStoreConfigurationFuncPtr
                                                      pEthSwtStoreConfiguration;

  /* EthSwtResetConfiguration */
  const EthIf_EthSwtResetConfigurationFuncPtr
                                                      pEthSwtResetConfiguration;
}EthIf_SwtApis;

/*Structure for WakeupType*/
/*Design ID : ETHIF_SDD_00532 */
typedef struct STagEthIf_WakeupSourceType
{
  /*Wakeupsource*/
  EcuM_WakeupSourceType ulWakeupSource;

  /* pTrcvDriver */
  const EthIf_TrcvApis*  pTrcvDriver;

  /*Index of referred EthTrcv*/
  uint8 ucTrcvIdx;

}EthIf_WakeupSourceType;



/* Design ID : ETHIF_SDD_0620  */
typedef struct STag_EthIf_StaticPhyController_PB
{

  /* ucCtrlIdx - IDx of actual ethernet driver */
  uint8 ucCtrlIdx;

  /* blCtrlHWDataTransfer - hardware supported data transfer */
  boolean blCtrlHWDataTransfer;

  /* WEthCtrlIdx - IDx of actual ethernet driver */
  uint8 ucWEthCtrlIdx;

}EthIf_StaticPhyController_PB;

/* Design ID : ETHIF_SDD_0053  */
typedef struct STag_EthIf_StaticTransceiver_PB
{
  /* pTrcvDriver */
  const EthIf_TrcvApis*  pTrcvDriver;
  /* Transceiver index to be fetched from reference*/
  uint8 ucTrcvIdx;
  /*Wireless Transceiver index to be fetched from reference*/
  uint8 ucWEthTrcvIdx;
  /* ucTrcvDriver */
  uint8 ucTrcvDriver;
}EthIf_StaticTransceiver_PB;

/* Design ID : ETHIF_SDD_0522 */
typedef struct STag_EthIf_FrameTypeToRxIndFunc
{
  /* FrameType configured - Taken from the configuration */
  uint16 usEthIfFrameType;

  /* index to the rx indication function */
  uint8 ucRxIndex;
}EthIf_FrameTypeToRxIndFunc;

/* Structure for the frame type */
/* Design ID : ETHIF_SDD_0522 */
typedef struct STag_EthIf_FrameTypeToRxIndFunc_PB
{
  /* FrameType configured - Taken from the configuration */
  uint16 usEthIfFrameType;
  uint8 ucRxFixedPoolIndex;
  uint8 ucRxFixedPoolSize;
  uint8 ucRxFloatPoolIndex;
  uint8 ucRxFloatPoolSize;
  /* index to the rx indication function */
  uint8 ucRxIndex;
}EthIf_FrameTypeToRxIndFunc_PB;

typedef enum ETag_EthIf_MetaDataItem{
  ETHIF_MATADATA_ITEM_PRIORITY_8 = (uint8)0u,
  ETHIF_MATADATA_ITEM_BROADCAST_8,
  ETHIF_MATADATA_ITEM_VLAN_16,
  ETHIF_MATADATA_ITEM_LISTELEM_PTR,
  ETHIF_MATADATA_ITEM_TIMETUPLE_TYPE_PTR,
  ETHIF_MATADATA_ITEM_ETHERNET_MAC_64
}EthIf_MetaDataItem;

typedef struct STag_EthIf_MetaDataItemInfo{
  /* MetaDataItemType */
  EthIf_MetaDataItem ddMetaDataItemType;
  /* MetaDataItemLength */
  uint8 ucMetaDataItemLength;
}EthIf_MetaDataItemInfo;

typedef struct STag_EthIf_TxPoolType
{
  Eth_FrameType ddFrameType;
  uint8 ucCtrlIdx;
  uint8 ucPriorityId;
}EthIf_TxPoolType;

typedef struct STag_EthIf_TxPduType
{
  const EthIf_TxPoolType * pTxPool;
  #ifdef ETHIF_IMMEDIATE_TRANSMIT_SUPPORT
  Eth_BufIdxType ddTxHandleId;
  #endif
  #if (ETHIF_METADATA_SUPPORT == STD_ON)
  const uint8 ucMetaDataMask;
  #endif
  PduIdType ddConfPduId;
  boolean blKeepTxBuffer;
}EthIf_TxPduType;

typedef struct STag_EthIf_RxPoolType
{
  uint8 ucPduIDsIndex;
  uint8 ucPdusize;
  uint8 ucPhyCtrlIdx;
}EthIf_RxPoolType;

typedef struct STag_EthIf_RxPduType
{
  #if (ETHIF_METADATA_SUPPORT == STD_ON)
  uint8 * pMetadataBuffer;
  const uint8 ucMetaDataMask;
  #endif
  uint8 ucRxPduId;
  boolean blKeepTxBuffer;
}EthIf_RxPduType;



/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/
/* Design ID : ETHIF_SDD_0727 */
#define EthIf_Config     EthIf_GaaConfig[0]

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/

#endif /* ETHIF_PBCFG_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
