/*******************************************************************************
**  FILE-NAME: EthIf_Lcfg.c                                                 **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_8/PB_Config/xml/EthIf_Config_8.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthSwt_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthSwt_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:43:48 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/**
  *
  * #section EthIf_Cfg_C_REF_1
  * Violates MISRA 2012 Advisory Rule 20.1,
  * #include directives should only be preceded by preprocessor directives or
  * comments.
  *
**/

/* PRQA S 0380 EOF */
/* violates Number of macro definitions exceeds 4095 - program does not */
/* conform strictly to ISO:C99 */ /*invalid QAC as total number of macros in */
/* code are less than 4095*/

/* Violates #ref EthIf_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
/* PRQA S 5087 EOF */
/* PRQA S 1290 EOF */
/* PRQA S 5002 EOF */
/* PRQA S 1582 EOF */
/* PRQA S 4640 EOF */
/******************************************************************************/
#include "EthIf.h"
#include "EthIf_Cfg.h"
#include "EthIf_IntTypes.h"
#include "TcpIp.h"
#include "EthSM.h"
#include "EthIf_Version.h"
#include "Cdd.h"
#include "LSduR_EthIf.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (ETHIF_VERSION_AR_RELEASE_MAJOR_VERSION != ETHIF_AR_RELEASE_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Major Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_MINOR_VERSION != ETHIF_AR_RELEASE_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Minor Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_REVISION_VERSION != ETHIF_AR_RELEASE_REVISION_VERSION)
  #error "ETHIF Code : Mismatch in Specification Revision Version"
#endif

#if (ETHIF_VERSION_SW_MAJOR_VERSION != ETHIF_SW_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Major Version"
#endif

#if (ETHIF_VERSION_SW_MINOR_VERSION != ETHIF_SW_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/

/* Design ID : ETHIF_SDD_0616 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_SwtApis  EthIf_GaaSwtApis[2] =
{
  /* EthIf_GaaSwtApis : 0 */
  {
    /* *pEthSwtGetArlTable */
    &EthSwt_39_DriverA_GetArlTable,


    /* *pEthSwtStoreConfiguration */
    &EthSwt_39_DriverA_StoreConfiguration,

    /* *pEthSwtResetConfiguration */
    &EthSwt_39_DriverA_ResetConfiguration
   },
  /* EthIf_GaaSwtApis : 1 */
  {
    /* *pEthSwtGetArlTable */
    &EthSwt_39_DriverB_GetArlTable,


    /* *pEthSwtStoreConfiguration */
    &EthSwt_39_DriverB_StoreConfiguration,

    /* *pEthSwtResetConfiguration */
    &EthSwt_39_DriverB_ResetConfiguration
   }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0619*/
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_WakeupSourceType
  EthIf_GaaWakeupSource[ETHIF_TOTAL_NUM_OF_WAKEUPSOURCE] =
{
/* EthIf_WakeupSourceType - EthTrcvWakeupMap_0 */
{
  
  /* WakeupSource */
  0x1U,
  
  /* pTrcvDriver */
  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
  
  /* Referred Trcv Idx */
  0x00U
},
/* EthIf_WakeupSourceType - EthTrcvWakeupMap_1 */
{
  
  /* WakeupSource */
  0x1U,
  
  /* pTrcvDriver */
  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
  
  /* Referred Trcv Idx */
  0x00U
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPoolType EthIf_GaaTxPools[ETHIF_NO_OF_TXPOOLS] =
{
  /* EthIf_GaaTxPool : EthIfFrameTxPool_0 */
  {
    
    /* ddFrameType */
    0x800u,
    
    /* ucCtrlIdx */
    0u,
    
    /* ucPriorityId */
    ETHIF_INVALID
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxPduType EthIf_GaaRxPdus[ETHIF_NO_OF_RXPDUS] =
{
  /* EthIf_GaaRxPdu : EthIfFrameRxPdu_0 */
  {
    
    /* pMetadataBuffer */
    &EthIf_GaaBufferMetaDataType_0[0],
    
    /* ucMetaDataMask */
    1u,
    
    /* ucRxPduId */
    LSduRConf_LSduRPathSourcePdu_LSduRPathSourcePdu_0,
    
    /* blKeepTxBuffer */
    ETHIF_TRUE
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxPoolType EthIf_GaaRxPools[ETHIF_NO_OF_RXPOOLS] =
{
  /* EthIf_GaaRxPool : EthIfFrameConfig_0_EthIfFrameRxPool_0 */
  {
    
    /* ucPduIDsIndex */
    0u,
    
    /* ucPdusize */
    1u,
    
    /* ucPhyCtrlIdx */
    0u
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const uint8 EthIf_RxPoolIdxMappingArray[ETHIF_RXPOOLIDX_MAP_SIZE] = {0};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPduType EthIf_GaaTxPdus[ETHIF_NO_OF_TXPDUS] =
{
  /* EthIf_GaaTxPdu : EthIfFrameTxPdu_0 */
  {
    
    /* pTxPool */
    &EthIf_GaaTxPools[0],
    
    /* ddTxHandleId */
    ETHIF_INVALID,
    
    /* ucMetaDataMask */
    1u,
    
    /* ddConfPduId */
    LSduRConf_LSduRPathDestinationPdu_LSduRPathDestinationPdu_0,
    
    /* blKeepTxBuffer */
    ETHIF_FALSE
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"


#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_MetaDataItemInfo EthIf_GaaTxMetaDataItemInfo[1] =
{
  /* EthIf_GaaMetaDataItemInfo : 0 */
  {
    
    /* ddMetaDataItemType */
    ETHIF_MATADATA_ITEM_ETHERNET_MAC_64,
    
    /* ucMetaDataItemLength */
    8
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_MetaDataItemInfo EthIf_GaaRxMetaDataItemInfo[1] =
{
  /* EthIf_GaaMetaDataItemInfo : 1 */
  {
    
    /* ddMetaDataItemType */
    ETHIF_MATADATA_ITEM_ETHERNET_MAC_64,
    
    /* ucMetaDataItemLength */
    8
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
uint8 EthIf_GaaBufferMetaDataType_0[ETHIF_METADATATYPE_0_LENGTH];
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

/*******************************************************************************
** Function Name        : EthIf_TxMacAddrAllign                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This function converts the MacAddress MetaDataItem  **
**                        from Platform ByteOrder to Network ByteOrder        **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : LpSrcMac, LucMetaDatalengh                          **
**                                                                            **
** InOut parameter      : LpDestMac                                           **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : void                                                **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_memcpy                     **
**                                             EthIf_ReverseCopy              **
**                                                                            **
** Design ID            : ETHIF_SDD_0801                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
static inline void EthIf_TxMacAddrAllign(uint8 * LpDestMac, const uint8 * LpSrcMac, uint8 LucMetaDatalength)
{
  #if (CPU_BYTE_ORDER == HIGH_BYTE_FIRST)
  if (LucMetaDatalength == ETHIF_MAC_ADDRESS_LENGTH + ETHIF_TWO)
  {
    LpSrcMac += ETHIF_TWO;
  }
  ETHIF_MEMCPY(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  #else
  EthIf_ReverseCopy(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  ETHIF_UNUSED(LucMetaDatalength);
  #endif
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"
/*******************************************************************************
** Function Name        : EthIf_GetMetaDataInfo                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This function fetches metadata items from           **
**                        Metadata pointer                                    **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : MetaDataPtr, LucMetaDataMask                        **
**                                                                            **
** InOut parameter      : MetaData                                            **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : Std_ReturnType                                      **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_memcpy                     **
**                                             EthIf_CopyToUint16             **
**                                                                            **
** Design ID            : ETHIF_SDD_0738                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
Std_ReturnType EthIf_GetMetaDataInfo(EthIf_MetaDataInfo * MetaData,
  uint8 * MetaDataPtr, const uint8 LucMetaDataMask)
/* PRQA S 4640 1 */
{
  uint8 LucIterCount;
  EthIf_MetaDataItem LddMetaDataItem;
  const EthIf_MetaDataItemInfo * LpMetaDataItemInfo;

  Std_ReturnType LddReturnValue  = (Std_ReturnType)E_OK;

  /* Initializing The metadata fileds, Mac Address is not initialized as it
     is mandatory */

  if ((MetaData != NULL_PTR) && (MetaDataPtr != NULL_PTR))
  {
    /* Meta Data Item ETHERNET_MAC_64 is not Initialized as it is mandatory */
    MetaData->TimeTuplePtr = NULL_PTR;
    MetaData->ListElemTypePtr = NULL_PTR;
    MetaData->Vlan16 = (uint16)ETHIF_ZERO;
    MetaData->Priority = ETHIF_ZERO;

    LpMetaDataItemInfo = &EthIf_GaaTxMetaDataItemInfo[ETHIF_ZERO];
    for (LucIterCount = ETHIF_NO_OF_TXMETADATAITEMS; LucIterCount > ETHIF_ZERO;
         LucIterCount--)
    {
      LddMetaDataItem = LpMetaDataItemInfo->ddMetaDataItemType;
      if (ETHIF_TRUE ==
          ETHIF_BITSET_CHECK(LucMetaDataMask, (LucIterCount - ETHIF_ONE)))
      {
        switch (LddMetaDataItem)
        {
          case ETHIF_MATADATA_ITEM_ETHERNET_MAC_64:
            /* Copy bytes of mac address received from metadataptr to the
               MacAddress */
            EthIf_TxMacAddrAllign(MetaData->MacAddress, MetaDataPtr,
              LpMetaDataItemInfo->ucMetaDataItemLength);
            MetaDataPtr += LpMetaDataItemInfo->ucMetaDataItemLength;
            break;
          default :
            /* No other metadataitem supported */
            LddReturnValue  = (Std_ReturnType)E_NOT_OK;
            break;
        }
      }
      LpMetaDataItemInfo++;
    }
  }
  else
  {
    LddReturnValue  = (Std_ReturnType)E_NOT_OK;
  }
  return LddReturnValue;
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"

/*******************************************************************************
** Function Name        : EthIf_RxMacAddrAllign                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This function converts the MacAddress MetaDataItem  **
**                        from Network ByteOrder to Platform ByteOrder        **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : LpSrcMac, LucMetaDatalength                          **
**                                                                            **
** InOut parameter      : LpDestMac                                           **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : void                                                **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_memcpy                     **
**                                             EthIf_ReverseCopy              **
**                                                                            **
** Design ID            : ETHIF_SDD_0802                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
static inline void EthIf_RxMacAddrAllign(uint8 * LpDestMac, const uint8 * LpSrcMac, uint8 LucMetaDatalength)
{
  #if (CPU_BYTE_ORDER == HIGH_BYTE_FIRST)
  if (LucMetaDatalength == ETHIF_MAC_ADDRESS_LENGTH + ETHIF_TWO)
  {
    *LpDestMac++ = 0x00;
    *LpDestMac++ = 0x00;
  }
  ETHIF_MEMCPY(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  #else
  /* If the System Endiness id Low Byte first,
     Copy it after reversing with zero padding last two bytes */
  EthIf_ReverseCopy(LpDestMac, LpSrcMac, ETHIF_MAC_ADDRESS_LENGTH);
  LpDestMac += ETHIF_MAC_ADDRESS_LENGTH;
  if (LucMetaDatalength == ETHIF_MAC_ADDRESS_LENGTH + ETHIF_TWO)
  {
    *LpDestMac++ = 0x00;
    *LpDestMac++ = 0x00;
  }
  #endif
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"
/*******************************************************************************
** Function Name        : EthIf_PutMetaDataInfo                               **
**                                                                            **
** Service ID           : NA                                                  **
**                                                                            **
** Description          : This API service of the Ethernet Interface          **
**                        processes configured metadata                       **
**                                                                            **
** Sync/Async           : Synchronous                                         **
**                                                                            **
** Re-entrancy          : Non-Reentrant                                       **
**                                                                            **
** Input Parameters     : LucMetaDataMask, PhysAddrPtr, IngressTimeTuplePtr,  **
**                        IsBroadcast                                         **
**                                                                            **
** InOut parameter      : MetaDataPtr                                         **
**                                                                            **
** Output Parameters    : None                                                **
**                                                                            **
** Return parameter     : void                                                **
**                                                                            **
** Preconditions        : EthIf_Init() should be invoked.                     **
**                                                                            **
** Remarks              : Global Variable(s):                                 **
**                                                                            **
**                        Function(s) invoked: Bsw_Memcpy                     **
**                                                                            **
** Design ID            : ETHIF_SDD_0216                                      **
*******************************************************************************/
/* PRQA S 4640 1 */
#define ETHIF_START_SEC_CODE
#include "EthIf_MemMap.h"
void EthIf_PutMetaDataInfo(uint8 * MetaDataPtr,
  const uint8 LucMetaDataMask, const uint8* PhysAddrPtr,
  #ifdef ETHIF_RXINDICATION_INGRESSTIME_SUPPORT
  const TimeTupleType* IngressTimeTuplePtr,
  #endif
  boolean IsBroadcast)
/* PRQA S 4640 1 */
{
  uint8 LucIterCount;
  EthIf_MetaDataItem LddMetaDataItem;
  const EthIf_MetaDataItemInfo * LpMetaDataItemInfo;

  if (MetaDataPtr != NULL_PTR)
  {
    LpMetaDataItemInfo = &EthIf_GaaRxMetaDataItemInfo[ETHIF_ZERO];
    for (LucIterCount = ETHIF_NO_OF_RXMETADATAITEMS; LucIterCount > ETHIF_ZERO;
         LucIterCount--)
    {
      LddMetaDataItem = LpMetaDataItemInfo->ddMetaDataItemType;
      if (ETHIF_TRUE ==
          ETHIF_BITSET_CHECK(LucMetaDataMask, (LucIterCount - ETHIF_ONE)))
      {
        switch (LddMetaDataItem)
        {
          case ETHIF_MATADATA_ITEM_ETHERNET_MAC_64:
            /* Copy the received PhysAddrPtr to MetaDataPtr */
            EthIf_RxMacAddrAllign(MetaDataPtr, PhysAddrPtr,
              LpMetaDataItemInfo->ucMetaDataItemLength);
            MetaDataPtr += LpMetaDataItemInfo->ucMetaDataItemLength;
          break;
          default :
            /* No other metadataitem supported */
            break;
        }
      }
      LpMetaDataItemInfo++;
    }
  }
  (void) IsBroadcast;
  #ifdef ETHIF_RXINDICATION_INGRESSTIME_SUPPORT
  (void) IngressTimeTuplePtr;
  #endif
}
#define ETHIF_STOP_SEC_CODE
#include "EthIf_MemMap.h"

/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
