/*******************************************************************************
**  FILE-NAME: EthIf_PBcfg.c                                                **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_8/PB_Config/xml/EthIf_Config_8.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthSwt_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthSwt_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:43:48 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/**
  *
  * #section EthIf_Cfg_C_REF_1
  * Violates MISRA 2012 Advisory Rule 20.1,
  * #include directives should only be preceded by preprocessor directives or
  * comments.
  *
**/

/* PRQA S 0380 EOF */
/* violates Number of macro definitions exceeds 4095 - program does not */
/* conform strictly to ISO:C99 */ /*invalid QAC as total number of macros in */
/* code are less than 4095*/

/* Violates #ref EthIf_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
/* PRQA S 5087 EOF */
/* PRQA S 1290 EOF */
/* PRQA S 5002 EOF */
/* PRQA S 1582 EOF */
/* PRQA S 4640 EOF */
/******************************************************************************/
/* Design ID : ETHIF_SDD_0726 */
#include "EthIf.h"
#include "EthIf_Cfg.h"
#include "EthIf_IntTypes.h"
#include "TcpIp.h"
#include "EthSM.h"
#include "EthIf_Version.h"
#include "Cdd.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (ETHIF_VERSION_AR_RELEASE_MAJOR_VERSION != ETHIF_AR_RELEASE_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Major Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_MINOR_VERSION != ETHIF_AR_RELEASE_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Minor Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_REVISION_VERSION != ETHIF_AR_RELEASE_REVISION_VERSION)
  #error "ETHIF Code : Mismatch in Specification Revision Version"
#endif

#if (ETHIF_VERSION_SW_MAJOR_VERSION != ETHIF_SW_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Major Version"
#endif

#if (ETHIF_VERSION_SW_MINOR_VERSION != ETHIF_SW_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/


/* EthIf_GaaClkUnitIndx with EthUlkUnitID */
#define ETHIF_START_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"
const uint8  EthIf_GaaClkUnitIndx
 [ETHIF_NUM_OF_PHYSICAL_CONTROLLERS][ETHIF_CLKUNIT_INDEX]
  = {
  	/*EthIf_GaaClkUnitIndx: 0*/
  	{0x0}
  };
#define ETHIF_STOP_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"

/* Generates EthTrcv module's API details*/
/* Design ID : ETHIF_SDD_0617 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TrcvApis  EthIf_GaaTrcvApis[1] =
{
  /* EthIf_GaaTrcvApis :0 */
  {
    &EthTrcv_SetTransceiverMode,

    &EthTrcv_GetTransceiverMode,

    &EthTrcv_GetLinkState,

    &EthTrcv_CheckWakeup,

    &EthTrcv_GetBusWuReason,

    &EthTrcv_TransceiverLinkStateRequest
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0610 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_LinkStateChangeFuncPtr EthIf_GaaLinkStateChangeFunc
[ETHIF_UL_LINKSTATECHANGE_NUM * ETHIF_CONFIGSET_COUNT] =
{
   &Cdd_EthIfLinkStateChange
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0618 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxConFuncPtr EthIf_GaaTxConfirmationFunc
[ETHIF_UL_TXCONFIRMATION_NUM * ETHIF_CONFIGSET_COUNT] =
{
&Cdd_EthIfTxConfirmation
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0611 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxIndFuncPtr EthIf_GaaRxIndicationFunc
[ETHIF_UL_RXINDICATION_NUM * ETHIF_CONFIGSET_COUNT] =
{

  NULL_PTR,
  &TcpIp_RxIndication

};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0609 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_FrameTypeToRxIndFunc EthIf_GaaFrameTypeToRxIndFunc
[ETHIF_NUM_FRAME_OWNER * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaFrameTypeToRxIndFunc : 0 - EthIfFrameConfig_0  */
 	{
 	  
 	  /* ucFrameType */
 	  0x800u,
 	  
 	  /* ucOwner */
 	  0x0u
 	},
 	/* EthIf_GaaFrameTypeToRxIndFunc : 1 - EthIfFrameConfig_1  */
 	{
 	  
 	  /* ucFrameType */
 	  0x88F7u,
 	  
 	  /* ucOwner */
 	  0x1u
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0622 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticController EthIf_GaaStaticController
[ETHIF_NUM_OF_CONTROLLERS * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticController : 0 - EthIfController_0 - EthIfController_0 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0000u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x0u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  &EthIf_GaaStaticTransceiver[EthIfConf_EthIfTransceiver_EthIfTransceiver_0],
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 1 - EthIfController_1 - EthIfController_1 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0001u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x0u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 2 - EthIfController_2 - EthIfController_2 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0002u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x0u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	},
 	/* EthIf_GaaStaticController : 3 - EthIfController_3 - EthIfController_3 */
 	{
 	  
 	  /* ucEthIfCtrlIdx */
 	  0x0003u,
 	  
 	  /* ucCtrlMTU */
 	  0x5DCu,
 	  
 	  /* ucEthIfMaxTxBufsTotal */
 	  0x000Au,
 	  
 	  /* ucVlanId */
 	  0x0u,
 	  
 	  /* pPhysCtrl */
 	  &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
 	  
 	  /* pTransceiver */
 	  NULL_PTR,
 	  
 	  /* usmacsec */
 	  ETHIF_NO_MACSEC,
 	  
 	  /* pPaeInst */
 	  NULL_PTR
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"


/* Struc call for PhyController_ClkUnit */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticClkUnit EthIf_GaaStaticClkUnit
[ETHIF_NUM_OF_CLKUNIT] =
{
/* EthIf_GaaStaticClkUnit - EthIfPhysController_0 */
{
  
  /* ucclkunitIdx */
  &EthIf_GaaClkUnitIndx[0][0],
  
  /* ucclkunitsize */
  0x1
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0623 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticPhyController EthIf_GaaStaticPhyController
[ETHIF_NUM_OF_PHYSICAL_CONTROLLERS * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticPhyController : 0 - EthIfPhysController_0  */
 	{
 	  
 	  /* ucCtrlIdx */
 	  0x0,
 	  
 	  /* blCtrlHWDataTransfer */
 	  ETHIF_FALSE,
 	  
 	  /* ucWEthCtrlRef */
 	  ETHIF_INVALID,
 	  
 	  /* ucCV2xCtrlRef */
 	  ETHIF_INVALID,
 	  
 	  /* ucPhysController */
 	  0x0u,
 	  
 	  /* ClkUnit */
 	  &EthIf_GaaStaticClkUnit[0]
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0611 */

/* Design ID : ETHIF_SDD_0614 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticSwitch EthIf_GaaStaticSwitch
[ETHIF_NUM_OF_SWITCHES * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticSwitch : 0 - EthIfSwitch_0 */
 	{
 	  
 	  /* ucSwtIdx */
 	  0x00u,
 	  
 	  /* ucSwtDriverIdx */
 	  0x0u
 	},
 	/* EthIf_GaaStaticSwitch : 1 - EthIfSwitch_1 */
 	{
 	  
 	  /* ucSwtIdx */
 	  0x01u,
 	  
 	  /* ucSwtDriverIdx */
 	  0x1u
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0624 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticTransceiver EthIf_GaaStaticTransceiver
[ETHIF_NUM_OF_TRANSCEIVERS * ETHIF_CONFIGSET_COUNT] =
{
 	/* EthIf_GaaStaticTransceiver : 0 - EthIfTransceiver_0  */
 	{
 	  
 	  /* pTrcvDriver */
 	  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
 	  
 	  /* ucEthIfTrcvIdx */
 	  0x0000u,
 	  
 	  /* ucWEthTrcvIdx */
 	  ETHIF_INVALID
 	}
 	};
 	#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
 	#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0618 */

/* Design ID : ETHIF_SDD_0610 */


#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_ConfigType  EthIf_GaaConfig
  [ETHIF_CONFIGSET_COUNT] =
{
  /* EthIf_GaaConfig : 0 -  */
  {
    
    /* pEthIfController */
    &EthIf_GaaStaticController[0],
    
    /* pEthIfFrameTypeToRxIndFunc */
    &EthIf_GaaFrameTypeToRxIndFunc[0],
    
    /* pEthIfPhyController */
    &EthIf_GaaStaticPhyController[0],
    
    /* pEthIfRxIndicationFunc */
    &EthIf_GaaRxIndicationFunc[0],
    
    /* pEthIfStaticSwitch */
    &EthIf_GaaStaticSwitch[0],
    
    /* EthIfTransceiver */
    &EthIf_GaaStaticTransceiver[0],
    
    /* EthIfLinkStateChangeFunc */
    &EthIf_GaaLinkStateChangeFunc[0],
    
    /* EthIfTxConfirmationFunc */
    &EthIf_GaaTxConfirmationFunc[0],
    
    /* ulStartOfDbToc */
    0x550B2A59u,
    
    /* ucEthIfController */
    4u,
    
    /* ucFrameTypeToRxIndFunc */
    2u,
    
    /* ucPhyController */
    1u,
    
    /* ucRxIndicationFunc */
    2u,
    
    /* ucStaticSwitch */
    2u,
    
    /* ucTransceiver */
    1u,
    
    /* ucLinkStateChangeFunc */
    1u,
    
    /* ucTxConfirmationFunc */
    1u
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"



/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
