/*******************************************************************************
**  FILE-NAME: EthIf_Cfg.c                                                  **
**                                                                            **
**  MODULE-NAME: EthIf                                                        **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.7.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../065_EthIf_TESTING/Code_Compliance/Config/EthIf_Config_3/PC_Config/xml/EthIf_Config_3.arxml
 *   ../../../065_EthIf_DELIVERY/bundle/com.kpit.c4k.bsw.ethif/resources/BSWMD/KPIT_AUTOSAR_R24-11_EthIf_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverA_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Eth_39_DriverB_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/EthTrcv_39_RTL82X1F_BSWMD.arxml
 *   ../../../065_EthIf_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Thu 2026 Apr 02 13:42:03 IST
 */

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/**
  *
  * #section EthIf_Cfg_C_REF_1
  * Violates MISRA 2012 Advisory Rule 20.1,
  * #include directives should only be preceded by preprocessor directives or
  * comments.
  *
**/

/* PRQA S 0380 EOF */
/* violates Number of macro definitions exceeds 4095 - program does not */
/* conform strictly to ISO:C99 */ /*invalid QAC as total number of macros in */
/* code are less than 4095*/

/* Violates #ref EthIf_Cfg_C_REF_1 Violates MISRA 2012 Required Rule 20.1 */
/* PRQA S 5087 EOF */
/* PRQA S 1290 EOF */
/* PRQA S 4640 EOF */
/******************************************************************************/
/* Design ID : ETHIF_SDD_0726 */
#include "EthIf.h"
#include "EthIf_Cfg.h"
#include "EthIf_IntTypes.h"
#include "TcpIp.h"
#include "Mka.h"
#include "EthSM.h"
#include "EthIf_Version.h"
#include "LSduR_EthIf.h"
#include "Cdd.h"
#include "EthTSyn.h"

/*******************************************************************************
**                               Version Check                                **
*******************************************************************************/

#if (ETHIF_VERSION_AR_RELEASE_MAJOR_VERSION != ETHIF_AR_RELEASE_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Major Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_MINOR_VERSION != ETHIF_AR_RELEASE_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Specification Minor Version"
#endif

#if (ETHIF_VERSION_AR_RELEASE_REVISION_VERSION != ETHIF_AR_RELEASE_REVISION_VERSION)
  #error "ETHIF Code : Mismatch in Specification Revision Version"
#endif

#if (ETHIF_VERSION_SW_MAJOR_VERSION != ETHIF_SW_MAJOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Major Version"
#endif

#if (ETHIF_VERSION_SW_MINOR_VERSION != ETHIF_SW_MINOR_VERSION)
  #error "ETHIF Code : Mismatch in Software Minor Version"
#endif

/*******************************************************************************
**                                Global Data                                 **
*******************************************************************************/

/*******************************************************************************
**                          Initialization Structure                          **
*******************************************************************************/

/* Design ID : ETHIF_SDD_0608 */
#define ETHIF_START_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"
const uint8  EthIf_GaaDrvToCtrlMapArray[2]
  = { 0x3,0x7 };
#define ETHIF_STOP_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"


/* EthIf_GaaClkUnitIndx with EthUlkUnitID */
#define ETHIF_START_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"
const uint8  EthIf_GaaClkUnitIndx
 [ETHIF_NUM_OF_PHYSICAL_CONTROLLERS][ETHIF_CLKUNIT_INDEX]
  = {
  	/*EthIf_GaaClkUnitIndx: 0*/
  	{0x0},
  	/*EthIf_GaaClkUnitIndx: 1*/
  	{0x0}
  };
#define ETHIF_STOP_SEC_CONFIG_DATA_8
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0611 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_RxIndFuncPtr EthIf_GaaRxIndicationFunc_PB[ETHIF_UL_RXINDICATION_NUM] =
{
  NULL_PTR,
  &TcpIp_RxIndication
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0618 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxConFuncPtr
  EthIf_GaaTxConfirmationFunc_PB[ETHIF_UL_TXCONFIRMATION_NUM] =
{
  &Cdd_EthIfTxConfirmation,
  &EthTSyn_TxConfirmation
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0610 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_LinkStateChangeFuncPtr
  EthIf_GaaLinkStateChangeFunc_PB[ETHIF_UL_LINKSTATECHANGE_NUM] =
{
  
  /* UL_LinkStateChange */
  &Cdd_EthIfLinkStateChange
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_MkaLinkStateChangeFuncPtr
  EthIf_GaaMkaLinkStateChangeFunc_PB[ETHIF_MKA_LINKSTATECHANGE_NUM] =
{
  
  /* Mka_LinkStateChange */
  &Mka_LinkStateChange
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0617 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TrcvApis  EthIf_GaaTrcvApis[1] =
{
  /* EthIf_GaaTrcvApis :0 */
  {
    &EthTrcv_SetTransceiverMode,

    &EthTrcv_GetTransceiverMode,

    &EthTrcv_GetLinkState,

    &EthTrcv_CheckWakeup,

    &EthTrcv_GetBusWuReason,

    &EthTrcv_TransceiverLinkStateRequest
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0619*/
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_WakeupSourceType
  EthIf_GaaWakeupSource[ETHIF_TOTAL_NUM_OF_WAKEUPSOURCE] =
{
/* EthIf_WakeupSourceType - EthTrcvWakeupMap_0 */
{
  
  /* WakeupSource */
  0x1U,
  
  /* pTrcvDriver */
  &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
  
  /* Referred Trcv Idx */
  0x00U
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticPaeInstance EthIf_GaaStaticPaeInstance
[ETHIF_NUM_OF_PAE_INSTANCES] =
{
/* EthIf_GaaStaticPaeInstance_0 */
{
  
  /* PaeIdx */
  0x0U
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_XXXX */
#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_ICVHandlerType EthIf_ICVHandlers[ETHIF_SW_MACSEC_CTRL_COUNT] =
{
  /* EthIf_ICVRef : EthIfICVHandler_0 */
  {
    
    /* ucICVGenRefJobId */
    0u,
    
    /* ucICKKeyRefJobId */
    2u,
    
    /* ucICVValidateRefJobId */
    5u
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0612 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticController EthIf_GaaStaticController[ETHIF_NUM_OF_CONTROLLERS] =
{
/* EthIf_GaaStaticController : EthIfController_0 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      0

  },
/* EthIf_GaaStaticController : EthIfController_1 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      1

  },
/* EthIf_GaaStaticController : EthIfController_2 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      2

  },
/* EthIf_GaaStaticController : EthIfController_3 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      3

  },
/* EthIf_GaaStaticController : EthIfController_4 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      4

  },
/* EthIf_GaaStaticController : EthIfController_5 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      5

  },
/* EthIf_GaaStaticController : EthIfController_6 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      6

  },
/* EthIf_GaaStaticController : EthIfController_7 */
    {
      /* ucEthIfMaxTxBufsTotal */
      10,

      /*ucEthIfCtrlIdx*/
      7

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0622 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticController_PB EthIf_GaaStaticController_PB[ETHIF_NUM_OF_CONTROLLERS] =
{
/* EthIf_GaaStaticController : EthIfController_0 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
      /* pTrcv */
      &EthIf_GaaStaticTransceiver[EthIfConf_EthIfTransceiver_EthIfTransceiver_0],
      /* pTrcv_PB */
      &EthIf_GaaStaticTransceiver_PB[EthIfConf_EthIfTransceiver_EthIfTransceiver_0],
      /* ucSWMacSecIndex */
      ETHIF_INVALID,
      /* usEthIfVlanTagLsb */
      0x8002U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_1 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* ucSWMacSecIndex */
      0u,
      /* usEthIfVlanTagLsb */
      0x0U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_SW_MACSEC,

      /* PAERef */
      &EthIf_GaaStaticPaeInstance[0]

  },
/* EthIf_GaaStaticController : EthIfController_2 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* ucSWMacSecIndex */
      ETHIF_INVALID,
      /* usEthIfVlanTagLsb */
      0x8002U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_3 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_0],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* ucSWMacSecIndex */
      ETHIF_INVALID,
      /* usEthIfVlanTagLsb */
      0x8007U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_4 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* ucSWMacSecIndex */
      ETHIF_INVALID,
      /* usEthIfVlanTagLsb */
      0x8008U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_5 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* ucSWMacSecIndex */
      ETHIF_INVALID,
      /* usEthIfVlanTagLsb */
      0x8009U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_6 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* ucSWMacSecIndex */
      ETHIF_INVALID,
      /* usEthIfVlanTagLsb */
      0x81F4U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  },
/* EthIf_GaaStaticController : EthIfController_7 */
    {
      /*pPhysCtrl*/
      &EthIf_GaaStaticPhyController[EthIfConf_EthIfPhysController_EthIfPhysController_1],
      /* pTrcv */
      NULL_PTR,
      /* pTrcv_PB */
      NULL_PTR,
      /* ucSWMacSecIndex */
      ETHIF_INVALID,
      /* usEthIfVlanTagLsb */
      0x0U,

      /* ucCtrlMTU */
      0x5DC,

      /* MacsecSupport */
      ETHIF_NO_MACSEC,

      /* PAERef */
      NULL_PTR

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticClkUnit EthIf_GaaStaticClkUnit
[ETHIF_NUM_OF_CLKUNIT] =
{
/* EthIf_GaaStaticClkUnit - EthIfPhysController_0 */
{
  
  /* ucClkUnitIdx */
  &EthIf_GaaClkUnitIndx[0][0],
  
  /* ucClkUnitSize */
  0x1
},
/* EthIf_GaaStaticClkUnit - EthIfPhysController_1 */
{
  
  /* ucClkUnitIdx */
  &EthIf_GaaClkUnitIndx[1][0],
  
  /* ucClkUnitSize */
  0x1
}
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0613 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticPhyController EthIf_GaaStaticPhyController[ETHIF_NUM_OF_PHYSICAL_CONTROLLERS] =
{
  /* EthIf_GaaStaticPhyController : EthIfPhysController_0 */
  {
    /*ucPhysCtrlIdx*/
    0x0,

    /* ClkUnit Index */
    &EthIf_GaaStaticClkUnit[0]

  },
  /* EthIf_GaaStaticPhyController : EthIfPhysController_1 */
  {
    /*ucPhysCtrlIdx*/
    0x1,

    /* ClkUnit Index */
    &EthIf_GaaStaticClkUnit[1]

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0623 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticPhyController_PB EthIf_GaaStaticPhyController_PB
  [ETHIF_NUM_OF_PHYSICAL_CONTROLLERS] =
{
  /* EthIf_GaaStaticPhyController : EthIfPhysController_0 */
  {

  	/* pEthDriver	 */
  	&EthIf_GaaDriverApis[ETHIF_ETH_DRIVERA],
  	

    /* ucEthCtrlIdx  - IDx of actual ethernet driver */
    0x0,

    /* WEthCtrlIdx - IDx of actual wireless ethernet driver */
    ETHIF_INVALID,

    /* blCtrlHWDataTransfer - hardware supported data transfer */
    ETHIF_FALSE


  },
  /* EthIf_GaaStaticPhyController : EthIfPhysController_1 */
  {

  	/* pEthDriver	 */
  	&EthIf_GaaDriverApis[ETHIF_ETH_DRIVERB],
  	

    /* ucEthCtrlIdx  - IDx of actual ethernet driver */
    0x1,

    /* WEthCtrlIdx - IDx of actual wireless ethernet driver */
    ETHIF_INVALID,

    /* blCtrlHWDataTransfer - hardware supported data transfer */
    ETHIF_FALSE


  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0615 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticTransceiver EthIf_GaaStaticTransceiver[ETHIF_NUM_OF_TRANSCEIVERS] =
{
  /* EthIf_GaaStaticTransceiver : EthIfTransceiver_0 */
  {
    /* ucEthIfTrcvIdx */
    0x0

  },
  /* EthIf_GaaStaticTransceiver : EthIfTransceiver_1 */
  {
    /* ucEthIfTrcvIdx */
    0x1

  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0624 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticTransceiver_PB EthIf_GaaStaticTransceiver_PB[ETHIF_NUM_OF_TRANSCEIVERS] =
{
  /* EthIf_GaaStaticTransceiver : EthIfTransceiver_0 */
  {
    /* pTrcvDriver */
    &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
    


    /*EthIfTransceiver_0*/
    /* ucEthTrcvIdx - Index of the actual transceiver */
    0x0U,
    /* ucWEthTrcvIdx - IDx of actual wireless ethernet driver */
    ETHIF_INVALID,


    /* ucTrcvDriver */
    ETHIF_ETHTRCV_0_RTL82X1F
  },
  /* EthIf_GaaStaticTransceiver : EthIfTransceiver_1 */
  {
    /* pTrcvDriver */
    &EthIf_GaaTrcvApis[ETHIF_ETHTRCV_0_RTL82X1F],
    


    /*EthIfTransceiver_1*/
    /* ucEthTrcvIdx - Index of the actual transceiver */
    0x0U,
    /* ucWEthTrcvIdx - IDx of actual wireless ethernet driver */
    ETHIF_INVALID,


    /* ucTrcvDriver */
    ETHIF_ETHTRCV_0_RTL82X1F
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

/* Design ID : ETHIF_SDD_0607 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_DrvApis  EthIf_GaaDriverApis[2] =
{
/* EthIf_GaaDriverApis : 0 */
{
  /* pEthSetControllerMode */
  &Eth_39_DriverA_SetControllerMode,

  /* pEthGetControllerMode */
  &Eth_39_DriverA_GetControllerMode,

  /* pEthGetPhysAddr */
  &Eth_39_DriverA_GetPhysAddr,

  /* pEthSetPhysAddr */
  &Eth_39_DriverA_SetPhysAddr,

  /* pEthUpdatePhysAddrFilter */
  &Eth_39_DriverA_UpdatePhysAddrFilter,

  /* pEthProvideTxBuffer */
  &Eth_39_DriverA_ProvideTxBuffer,

  /* pEthTransmit */
  &Eth_39_DriverA_Transmit,

  /* pEthReceive */
  &Eth_39_DriverA_Receive,

  /* pEthTxConfirmation */
  &Eth_39_DriverA_TxConfirmation,

  /* pEthGetCurrentTimeTuple */
  &Eth_39_DriverA_GetCurrentTimeTuple,

  /* pEthEnableEgressTimeStamp */
  &Eth_39_DriverA_EnableEgressTimeStamp,

  /* pEthGetEgressTimeStamp */
  &Eth_39_DriverA_GetEgressTimeStamp,

  /* pEthGetIngressTimeStamp */
  &Eth_39_DriverA_GetIngressTimeStamp,

  /* pEthSetPhcTime */
  &Eth_39_DriverA_SetPhcTime,

  /* pEthSetPhcCorrection */
  &Eth_39_DriverA_SetPhcCorrection,

  /* pEthGetPhcTime */
  &Eth_39_DriverA_GetPhcTime,

  /* pEthSetPpsSignalMode */
  &Eth_39_DriverA_SetPpsSignalMode

 },
/* EthIf_GaaDriverApis : 1 */
{
  /* pEthSetControllerMode */
  &Eth_39_DriverB_SetControllerMode,

  /* pEthGetControllerMode */
  &Eth_39_DriverB_GetControllerMode,

  /* pEthGetPhysAddr */
  &Eth_39_DriverB_GetPhysAddr,

  /* pEthSetPhysAddr */
  &Eth_39_DriverB_SetPhysAddr,

  /* pEthUpdatePhysAddrFilter */
  &Eth_39_DriverB_UpdatePhysAddrFilter,

  /* pEthProvideTxBuffer */
  &Eth_39_DriverB_ProvideTxBuffer,

  /* pEthTransmit */
  &Eth_39_DriverB_Transmit,

  /* pEthReceive */
  &Eth_39_DriverB_Receive,

  /* pEthTxConfirmation */
  &Eth_39_DriverB_TxConfirmation,

  /* pEthGetCurrentTimeTuple */
  &Eth_39_DriverB_GetCurrentTimeTuple,

  /* pEthEnableEgressTimeStamp */
  &Eth_39_DriverB_EnableEgressTimeStamp,

  /* pEthGetEgressTimeStamp */
  &Eth_39_DriverB_GetEgressTimeStamp,

  /* pEthGetIngressTimeStamp */
  &Eth_39_DriverB_GetIngressTimeStamp,

  /* pEthSetPhcTime */
  &Eth_39_DriverB_SetPhcTime,

  /* pEthSetPhcCorrection */
  &Eth_39_DriverB_SetPhcCorrection,

  /* pEthGetPhcTime */
  &Eth_39_DriverB_GetPhcTime,

  /* pEthSetPpsSignalMode */
  &Eth_39_DriverB_SetPpsSignalMode

 }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0614 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_StaticSwitch_PB EthIf_GaaStaticSwitch_PB[1] =
{
  /* EthIf_GaaStaticSwitch : EthIfSwitch_0 */
  {
    /* ucSwtIdx */
    0x00
  }
};
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"


/* Design ID : ETHIF_SDD_0609 */
#define ETHIF_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_FrameTypeToRxIndFunc_PB
EthIf_GaaFrameTypeToRxIndFunc_PB[ETHIF_NUM_FRAME_OWNER] =
{
  /* EthIf_GaaFrameTypeToRxIndFunc : EthIfFrameConfig_0 */
  {
    
    /* usEthIfFrameType */
    0x800u,
    
    /* ucRxIndex */
    0x0u
  },
  /* EthIf_GaaFrameTypeToRxIndFunc : EthIfFrameConfig_1 */
  {
    
    /* usEthIfFrameType */
    0x88F7u,
    
    /* ucRxIndex */
    0x1u
  }
};
/* PRQA S 5002 3 */
#define ETHIF_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "EthIf_MemMap.h"

#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPoolType EthIf_GaaTxPools[ETHIF_NO_OF_TXPOOLS] =
{
  /* EthIf_GaaTxPool : EthIfFrameTxPool_0 */
  {
    
    /* ddFrameType */
    0x800u,
    
    /* ucCtrlIdx */
    0u,
    
    /* ucPriorityId */
    ETHIF_INVALID
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"


#define ETHIF_START_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"
const EthIf_TxPduType EthIf_GaaTxPdus[ETHIF_NO_OF_TXPDUS] =
{
  /* EthIf_GaaTxPdu : EthIfFrameTxPdu_0 */
  {
    
    /* pTxPool */
    &EthIf_GaaTxPools[0],
    
    /* ddConfPduId */
    LSduRConf_LSduRPathDestinationPdu_LSduRPathDestinationPdu_0,
    
    /* blKeepTxBuffer */
    ETHIF_FALSE
  }
};
#define ETHIF_STOP_SEC_CONST_UNSPECIFIED
#include "EthIf_MemMap.h"


/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
