/*******************************************************************************
**  FILE-NAME: Tls_Generated_Callouts.h                                     **
**                                                                            **
**  MODULE-NAME: Tls                                                          **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.4.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../170_Tls_TESTING/Code_Compliance/Config/Tls_Config_3/PC_Config/xml/Tls_Config_3.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/Csm/xml/Csm.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/KeyM/xml/KeyM.arxml
 *   ../../../170_Tls_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2026 Apr 22 15:04:47 IST
 */
#ifndef TLS_GENERATED_CALLOUTS_H
#define TLS_GENERATED_CALLOUTS_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
#include "ComStack_Types.h"
#include "TcpIp.h"				

/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
#define TLS_AR_RELEASE_MAJOR_VERSION    4
#define TLS_AR_RELEASE_MINOR_VERSION    10
#define TLS_AR_RELEASE_REVISION_VERSION 0
#define TLS_SW_MAJOR_VERSION            0
#define TLS_SW_MINOR_VERSION            4
#define TLS_SW_PATCH_VERSION            0
#define TLS_VENDOR_ID                   (uint16)39
#define TLS_MODULE_ID                   (uint16)170

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/

/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/

/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/

/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/
extern Std_ReturnType PSK_CBK1_TlsClientGetPskIdentity(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16 PskIdentityHintLength, // no use for current TLS
												const uint8* PskIdentityHintPtr, // no use for current TLS
												uint16* PskKeyIdentityLengthPtr,
												uint8* PskKeyIdentityPtr,
												uint32* CsmKeyId
												);
extern Std_ReturnType PSK_CBK3_TlsClientGetPskIdentity(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16 PskIdentityHintLength, // no use for current TLS
												const uint8* PskIdentityHintPtr, // no use for current TLS
												uint16* PskKeyIdentityLengthPtr,
												uint8* PskKeyIdentityPtr,
												uint32* CsmKeyId
												);
extern Std_ReturnType PSK_CBK4_TlsClientGetPskIdentity(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16 PskIdentityHintLength, // no use for current TLS
												const uint8* PskIdentityHintPtr, // no use for current TLS
												uint16* PskKeyIdentityLengthPtr,
												uint8* PskKeyIdentityPtr,
												uint32* CsmKeyId
												);
extern Std_ReturnType PSK_CBK4_TlsServerGetPskIdentity(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16 PskKeyIdentityLength,
												const uint8* PskKeyIdentityPtr,
												uint32* CsmKeyId
												);
extern Std_ReturnType PSK_CBK1_TlsServerGetPskIdentity(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16 PskKeyIdentityLength,
												const uint8* PskKeyIdentityPtr,
												uint32* CsmKeyId
												);
extern Std_ReturnType PSK_CBK3_TlsServerGetPskIdentity(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16 PskKeyIdentityLength,
												const uint8* PskKeyIdentityPtr,
												uint32* CsmKeyId
												);
extern Std_ReturnType PSK_CBK4_TlsServerGetPskIdentityHint(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16* IdentityHintLengthPtr,
												uint8* IdentityHintPtr
												);
extern Std_ReturnType PSK_CBK1_TlsServerGetPskIdentityHint(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16* IdentityHintLengthPtr,
												uint8* IdentityHintPtr
												);
extern Std_ReturnType PSK_CBK3_TlsServerGetPskIdentityHint(
												TcpIp_TlsConnectionIdType TlsConnectionId,
												uint16* IdentityHintLengthPtr,
												uint8* IdentityHintPtr
												);

#endif /* TLS_GENERATED_CALLOUTS_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
