/*******************************************************************************
**  FILE-NAME: Tls_Cfg.h                                                    **
**                                                                            **
**  MODULE-NAME: Tls                                                          **
**                                                                            **
**  NOTE: This file is auto generated, do not edit this file manually.        **
**                                                                            **
********************************************************************************

********************************************************************************
**                           Generation Information                           **
********************************************************************************
**                                                                            **
**  Tool Version: 0.4.0                                                       **
**                                                                            **
********************************************************************************
**                        File Generation Information                         **
*******************************************************************************/

/*
 * INPUT FILE(s):
 *   ../../../170_Tls_TESTING/Code_Compliance/Config/Tls_Config_1/PC_Config/xml/Tls_Config_1.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/Csm/xml/Csm.arxml
 *   ../../../170_Tls_TESTING/Embedded/Bsw_Stubs/KeyM/xml/KeyM.arxml
 *   ../../../170_Tls_TESTING/Embedded/Swc_Stubs/Variant_Handling.arxml
 *
 * GENERATED ON : Wed 2026 Apr 22 15:04:19 IST
 */
#ifndef TLS_CFG_H
#define TLS_CFG_H

/*******************************************************************************
**                              Include Section                               **
*******************************************************************************/
/*******************************************************************************
**                        Common Published Information                        **
*******************************************************************************/
/* Design ID: TLS_SDD_0720, TLS_SDD_0721, TLS_SDD_0745, TLS_SDD_0722, TLS_SDD_0723, TLS_SDD_0724, TLS_SDD_0725, TLS_SDD_0726 */
#define TLS_AR_RELEASE_MAJOR_VERSION      4
#define TLS_AR_RELEASE_MINOR_VERSION      10
#define TLS_AR_RELEASE_REVISION_VERSION   0
#define TLS_SW_MAJOR_VERSION              0   
#define TLS_SW_MINOR_VERSION              4 
#define TLS_SW_PATCH_VERSION              0    
#define TLS_VENDOR_ID                   (uint16)39
#define TLS_MODULE_ID                   (uint16)170

/*******************************************************************************
**                             Precompile Macros                              **
*******************************************************************************/

/* Design ID: TLS_SDD_0712 */
/*Pre Compile option */  
#define TLS_PRE_COMPILE_SINGLE      STD_ON

/* Design ID: TLS_SDD_0713 */
/* error-reporting to the Development Error Tracer (DET) */  
#define TLS_DEV_ERROR_DETECT      STD_ON

/* Design ID: TLS_SDD_0714, TLS_SDD_0319 */
/* Macro which Defines when get Version is supported */  
#define TLS_VERSION_INFO_API      STD_ON

/* Design ID: TLS_SDD_0715 */
/* Checks if atleast one PSK container is configured */   
#define TLS_PSK_IDENTITY_SUPPORT_ENABLED   STD_ON

/* Design ID: TLS_SDD_0716 */
/* Checks if atleadt once connection  is configured with Certificate */   
#define TLS_CERTIFICATE_SUPPORT_ENABLED   STD_OFF
 
/* Design ID: TLS_SDD_0717 */
/* Macro to check if any one of the connection is configured with a TlsGroup */
#define TLS_GROUP_CONFIGURED                 STD_ON   
/* Design ID: TLS_SDD_0718 */
#define TLS_TIMER_SUPPORT      STD_ON

/* Design ID: TLS_SDD_0719 */
/* Macro to check TLS TIMER is Supported */
#define TLS_HKDF_CSM_SUPPORT                 STD_OFF   
  

/*******************************************************************************
**                                  Macros                                    **
*******************************************************************************/

/* Design ID: TLS_SDD_0727 */
/* Max Length of the cipher suite name configured */ 
#define TLS_MAX_LEN_OF_CIPHERSUITENAME                     22U

/* Design ID: TLS_SDD_0744 */
/* Finds out many PSK containers are configured */
#define TLS_NUM_OF_PSK_CONFIGURED                          13U

/* Design ID: TLS_SDD_0743 */
/* Max Length of the tlsPresharedKeyIdentityHint of Psk conatiner */   
#define TLS_PSK_IDENTITY_HINT_MAX_LEN                       20U

/* Design ID: TLS_SDD_0730 */
/* Max Length of the tlsPresharedKeyIdentity of Psk conatiner */
#define TLS_PSK_IDENTITY_MAX_LEN                       21U

/* Design ID: TLS_SDD_0731 */
/* Max Length of the TlsServerNameIdentification of TlsCertificateIdentitys */   
#define TLS_SNI_MAX_LEN                          1U
 
/* Design ID: TLS_SDD_0732 */
/* Total number of Tls connections configured */ 
#define TLS_TOTAL_CONNECTIONS                         6U

/* Design ID: TLS_SDD_0733 */
/* Total number of Tls CertificateIdentitys configured */ 
#define TLS_NUM_OF_CERTIFICATE_IDENTITYS               1U

/* Design ID: TLS_SDD_0741 */
/* Total number of Tls CiphersuiteDefinitions conatiners configured */  
#define TLS_NUM_OF_CIPHERSUITE_DEFINITION                  3U

/* Design ID: TLS_SDD_0740 */
/* Total number of Tls CiphersuiteWorkers conatiners configured */ 
#define TLS_NUM_OF_CIPHERSUITE_WORKER                      4U

/* Design ID: TLS_SDD_0736 */
/* Total number of Tls CiphersuiteWorkers conatiners refferd to al connections */ 
#define TLS_NUM_OF_REFFERED_CIPHERSUITE_WORKER                      12U

/* Design ID: TLS_SDD_0739 */
/* Total number of Tls Handshakes conatiners configured */    
#define TLS_NUM_OF_HANDSHAKE                               3U
 
/* Design ID: TLS_SDD_0738 */
/* Total number of Tls Handshakes conatiners refferd to all connections */ 
#define TLS_NUM_OF_REFFERED_HANDSHAKE                      12U

/* Design ID: TLS_SDD_0734 */
/* Total number of PSK conatiners refferd to all connections */ 
#define TLS_NUM_OF_REFFERED_PSK                      18U
  
/* Design ID: TLS_SDD_0742 */
/* Total TlsMaxConnections Opened  */    
#define TLS_MAX_ACTIVE_CONNECTIONS                               2U

/* Design ID: TLS_SDD_0729 */
/* Total Number of TlsConnectionGroups conatiners Configured */
#define TLS_TOTAL_GROUPS                  (uint16)0x0002

/* Design ID: TLS_SDD_0728 */
/* Total Number of Extra Bytes for the HandSHake buffer */
#define TLS_MAX_BUFFER_SIZE                  (uint16)0x0528

/* Design ID: TLS_SDD_0735 */
/* Total Number of Extra Bytes for the HandSHake buffer */
#define TLS_MAX_FRAGMENT_SIZE                  (uint16)0x0064

/* Design ID: TLS_SDD_0737 */
/* Size of the Array to be creted in static , for destroying key */
#define TLS_DESTROY_ARR_SIZE                  14U  



/*******************************************************************************
**                             Global Data Types                              **
*******************************************************************************/

/*******************************************************************************
**                         Configuration Set Handles                          **
*******************************************************************************/

/*******************************************************************************
**                            Function Prototypes                             **
*******************************************************************************/
#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

extern void Tls_MainFunction_TlsConnection_0(void);

#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

extern void Tls_MainFunction_TlsConnection_1(void);

#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

extern void Tls_MainFunction_TlsConnection_2(void);

#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

extern void Tls_MainFunction_TlsConnection_3(void);

#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

extern void Tls_MainFunction_TlsConnection_4(void);

#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"

#define TLS_START_SEC_CODE
#include "Tls_MemMap.h"

extern void Tls_MainFunction_TlsConnection_5(void);

#define TLS_STOP_SEC_CODE
#include "Tls_MemMap.h"


#endif /* TLS_CFG_H */
/*******************************************************************************
**                                End of File                                 **
*******************************************************************************/
